// A single quiet gameplay HUD. Actions live in the menu; machines have real switches.
const playHUD=document.createElement('div');playHUD.id='play-hud';playHUD.innerHTML='<div id="equipped-tool"></div><div id="play-state"></div><div id="interaction-hint"></div><div id="play-toast" role="status"></div>';document.body.appendChild(playHUD);
const menuLinks=document.createElement('div');menuLinks.className='menu-links';
for(const [id,title,action]of [['play-toys','Toybox',openToybox],['play-tune','Settings',()=>openPanel('tune')],['play-help','Controls',()=>{$('play-help-content').hidden=!$('play-help-content').hidden;}],['play-about','About',()=>openPanel('about')],['play-sound','Sound: on',()=>{soundOn=!soundOn;$('play-sound').textContent='Sound: '+(soundOn?'on':'off');updateScrape(0,0);} ]]){const b=document.createElement('button');b.id=id;b.textContent=title;b.onclick=action;menuLinks.append(b);}
$('play-resume').after(menuLinks);
const help=document.createElement('div');help.id='play-help-content';help.hidden=true;help.innerHTML='<p>WASD move · Shift run · Space jump · F fly<br>Mouse wheel: change tool · B: Toybox<br>E: use machine switch · 1: grab<br>While holding: wheel moves, Q/E rotates<br>R: reload (Grab: restore buddy) · I: inspect<br>K: kick · U: shove · T: slow motion<br>Tab: free mouse / capture · Esc: pause<br>Hold C: move aim without turning<br>F3: profiler · H: hide HUD</p>';$('play-cursor').before(help);help.append($('play-cursor'),$('play-defaults'));
controlStyle.textContent+=`#play-menu{background:#0b191a80}#play-menu section{box-sizing:border-box;width:min(390px,calc(100vw - 32px));padding:26px;max-height:calc(100vh - 40px);overflow:auto;box-shadow:none}#play-menu h1{font-size:30px;margin:10px 0}#play-menu .menu-links{display:grid;grid-template-columns:1fr 1fr;margin:10px 0 16px;gap:6px}#play-menu .menu-links button{background:none;color:#d9e1d7;border-color:#425a58;text-align:left;font-size:14px;padding:11px}#play-menu button:hover{filter:brightness(1.16)}#play-menu button:focus-visible{outline:2px solid #eee0bd;outline-offset:3px}#play-menu #play-defaults{font-size:11px!important}#play-help-content[hidden]{display:none}
#play-hud{pointer-events:none;color:#f3ead6;font:13px Arial;text-shadow:0 1px 3px #000,0 0 8px #0009}#play-hud[hidden]{display:none}#equipped-tool{position:fixed;bottom:39px;left:24px;font-size:15px;font-weight:700}#play-state{position:fixed;bottom:20px;left:24px;color:#d1dacf;font-size:11px}#interaction-hint{position:fixed;top:calc(50% + 27px);left:50%;transform:translateX(-50%);padding:6px 9px;background:#122021d9;border-radius:3px}#interaction-hint:empty{display:none}#play-toast{position:fixed;bottom:28px;left:50%;transform:translateX(-50%);max-width:min(560px,60vw);text-align:center;font-size:12px;line-height:1.5}
`;
function hudText(id,value){const element=$(id);if(element.textContent!==value)element.textContent=value;}
drawHUDLive=()=>{
 hideHUDLayer(badgeLayer);hideHUDLayer(demoLayer);if(footerHUD.style.display!=='none')footerHUD.style.display='none';
 const visible=window.__smearComputeReady&&showHUD&&!panel&&!paused&&toybox.hidden&&!runtimeProfiler.visible;if(playHUD.hidden===visible)playHUD.hidden=!visible;
 if(!visible){hideHUDLayer(aimLayer);return;}
 const aim=aimXY(),gap=tool===1?4+viewKick*19:4,hit=simTime<hitMarkerUntil;
 drawHUDLayer(aimLayer,[aim.x-16,aim.y-16,aim.x+16,aim.y+16],[aim.x,aim.y,gap,hit,hitMarkerColor],g=>{g.fillStyle='#f3ead6';g.strokeStyle='#132322';g.lineWidth=2;g.beginPath();g.arc(aim.x,aim.y,1.5,0,TAU);g.stroke();g.fill();if(hit){g.strokeStyle=hitMarkerColor;g.lineWidth=1.5;g.beginPath();for(const [x,y]of [[1,1],[-1,1],[1,-1],[-1,-1]]){g.moveTo(aim.x+x*6,aim.y+y*6);g.lineTo(aim.x+x*11,aim.y+y*11);}g.stroke();}});
 const words=compute.cache.toolbox||[];let resource='';if(tool===6)resource=' · '+Math.min(100,Math.round((words[0]||0)/16777216/.25*100))+'%';if(tool===9)resource=' · '+Math.min(100,Math.round((words[1]||0)/16777216/2*100))+'% · '+(words[2]||0)+' fragments';
 hudText('equipped-tool',toolLibrary[tool][0]+resource+(reloadAge<reloadDuration?' / '+Math.round(reloadAge/reloadDuration*100)+'%':''));hudText('play-state',[slow?'0.25× speed · T to restore':'',player.fly?'Flying':'',fpsControl.phase==='cursor'?'Tab to capture mouse':(tool?'R Reload · I Inspect · ':'')+'B Toybox · Esc Menu'].filter(Boolean).join(' · '));
 const target=compute.cache.control||0;const name=target?toyNames[compute.props[(target&255)-1]?.box.propKind]||'machine':'';
 hudText('interaction-hint',!grab&&!compute.placement&&target?'E · '+(target&256?'Stop ':'Start ')+name:'');
 hudText('play-toast',grab?'Wheel: move held object · Q/E: rotate':performance.now()/1000<toastUntil?toast:'');
};
