import fs from 'node:fs';import assert from 'node:assert/strict';import {resolve} from 'node:path';import {pathToFileURL} from 'node:url';import {spawnSync} from 'node:child_process';import {createHash} from 'node:crypto';import {launch,until,sleep} from './cdp.mjs';
import {installImpactFixture} from './impact-fixture.mjs';
const out=resolve('tools/out/arsenal-pass/recordings');fs.mkdirSync(out,{recursive:true});const receipt={at:new Date().toISOString(),clips:[]};
function encode(args){const p=spawnSync('ffmpeg',['-nostdin','-hide_banner','-loglevel','error','-y',...args],{encoding:'utf8',windowsHide:true,timeout:120000});assert.ifError(p.error);assert.equal(p.status,0,p.stderr);}
async function start(page){await page.eval(`(()=>{window.__chunks=[];const tap=__smear.compute.audioTap();window.__stream=new MediaStream([...__smearGPU.canvas.captureStream(30).getVideoTracks(),...tap.stream.getAudioTracks()]);window.__recorder=new MediaRecorder(__stream,{mimeType:'video/webm;codecs=vp9,opus',videoBitsPerSecond:14000000,audioBitsPerSecond:192000});__recorder.ondataavailable=e=>{if(e.data.size)__chunks.push(e.data)};__recorder.start(1000);__smear.manual(false);})()`);}
async function finish(page,name,title){await page.eval('__smear.manual(true)');const data=await page.eval(`new Promise(resolve=>{__recorder.onstop=()=>{const f=new FileReader();f.onload=()=>resolve(f.result.split(',')[1]);f.readAsDataURL(new Blob(__chunks,{type:'video/webm'}));__stream.getTracks().forEach(t=>t.stop());};__recorder.stop();})`);fs.writeFileSync(resolve(out,name+'.webm'),Buffer.from(data,'base64'));encode(['-i',resolve(out,name+'.webm'),'-vf',`fps=30,drawtext=font=Arial:text='${title}':x=24:y=h-50:fontsize=25:fontcolor=white:box=1:boxcolor=black@0.7:boxborderw=8`,'-c:v','libx264','-preset','fast','-crf','18','-pix_fmt','yuv420p','-c:a','aac','-b:a','192k','-movflags','+faststart',resolve(out,name+'.mp4')]);}

for(const [name,path,version] of [['before','tools/out/arsenal-pass/before/index.html','BEFORE'],['after','index.html','V36 CONTACT GRENADE'],['rocket','index.html','V36 ROCKET LAUNCHER']]){
 const page=await launch({port:9765,width:1600,height:1000,headless:true});const clip={name,version,profile:page.dir,buildSHA256:createHash('sha256').update(fs.readFileSync(path)).digest('hex')};receipt.clips.push(clip);
 try{
 await page.goto(pathToFileURL(resolve(path)).href+'?defaults=1');await until(()=>page.eval('!!window.__smearComputeReady'),{timeout:90000});await page.eval('__smear.manual(true)');await page.mouse('mousePressed',800,140);await page.mouse('mouseReleased',800,140);await installImpactFixture(page);await page.eval('__impactTest.setup({speed:0})');const h=(await page.eval('__smear.state()')).parts[name==='rocket'?0:2].p;
 await page.eval('__smear.view(['+h[0]+','+(h[1]-(name==='rocket'?0:.16))+','+(h[2]+(name==='rocket'?2.2:1.7))+'],'+JSON.stringify(h)+');__smear.pointer(800,500);__smear.tool('+(name==='rocket'?5:4)+')');await start(page);await sleep(35);await page.mouse('mousePressed',800,500);await sleep(45);await page.mouse('mouseReleased',800,500);await sleep(2000);await page.eval('__smear.view([-1.0,3,-3],[-3.5,.8,-7.3])');await sleep(2600);await page.shot(resolve(out,name+'-aftermath.png'));await finish(page,name,version);clip.state=await page.eval('__smear.state()');assert.deepEqual(clip.state.errors,[]);clip.audio=await page.eval('__smear.compute.audio()');assert(clip.audio.enabled&&clip.audio.state==='running');assert(!page.logs.some(s=>/^error:|^EXCEPTION:/.test(s)));console.log('Recorded '+name);
 }finally{clip.logs=page.logs;page.kill();fs.writeFileSync(resolve(out,'capture.json'),JSON.stringify(receipt,null,2));}
}
encode(['-i',resolve(out,'before.mp4'),'-i',resolve(out,'after.mp4'),'-filter_complex','[0:v]scale=960:600,setpts=PTS-STARTPTS[a];[1:v]scale=960:600,setpts=PTS-STARTPTS[b];[a][b]hstack=inputs=2:shortest=1[v]','-map','[v]','-map','1:a','-shortest','-c:v','libx264','-preset','fast','-crf','18','-pix_fmt','yuv420p','-c:a','aac','-b:a','192k','-movflags','+faststart',resolve(out,'grenade-contact-before-after.mp4')]);receipt.passed=true;fs.writeFileSync(resolve(out,'capture.json'),JSON.stringify(receipt,null,2));console.log('COMPLETE arsenal footage');
