import fs from 'node:fs';import assert from 'node:assert/strict';import {resolve} from 'node:path';import {pathToFileURL} from 'node:url';import {createHash} from 'node:crypto';
import {launch,until} from './cdp.mjs';import {installImpactFixture} from './impact-fixture.mjs';import {installDestructionFixture} from './destruction-fixture.mjs';
const out=resolve('tools/out/arsenal-pass/'+(process.argv[2]||'development'));fs.mkdirSync(out,{recursive:true});
const r={at:new Date().toISOString(),sha256:createHash('sha256').update(fs.readFileSync('index.html')).digest('hex'),checks:[]};let page;
const pass=s=>{r.checks.push(s);console.log('PASS '+s);};
try{
 page=await launch({port:9764,width:1600,height:1000,headless:true});r.profile=page.dir;await page.goto(pathToFileURL(resolve('index.html')).href+'?defaults=1');
 await until(async()=>{const a=await page.eval('({ready:!!window.__smearComputeReady,error:document.getElementById("failure")?.style.display==="block"?document.getElementById("failure").textContent:null})');if(a.error)throw Error(a.error);return a.ready;},{timeout:90000});await page.eval('__smear.manual(true)');await page.mouse('mousePressed',800,120);await page.mouse('mouseReleased',800,120);await installImpactFixture(page);await installDestructionFixture(page);
 await page.eval(`window.__arsenal={async words(){return Array.from(new Uint32Array(await __destructionFixture.read(__smearGPU.workBuffer,0,__smearGPU.workBuffer.size)));},async ord(){const g=__smearGPU,a=await __destructionFixture.read(g.workBuffer,(g.destructionBase+1440)*4,128*24*4),w=new Uint32Array(a),f=new Float32Array(a);return Array.from({length:128},(_,i)=>({kind:w[i*24+23],r:f[i*24+3],age:f[i*24+7],p:Array.from(f.slice(i*24,i*24+3)),v:Array.from(f.slice(i*24+4,i*24+7)),sleep:!!(w[i*24+20]&0x80000000)}));}}`);
 await page.eval('__impactTest.setup({speed:0})');const head=(await page.eval('__smear.state()')).parts[2].p;
 await page.eval(`__smear.view([${head[0]},${head[1]-.16},${head[2]+1.7}],${JSON.stringify(head)});__smear.pointer(800,500);__smear.tool(4)`);await page.mouse('mousePressed',800,500);await page.mouse('mouseReleased',800,500);await page.eval('__smear.render();__impactTest.advance(24)');
 r.grenade=await page.eval('__smear.state()');let w=await page.eval('__arsenal.words()'),meta=await page.eval('__smearGPU.destructionMeta');assert.equal(w[58],1);assert(w[meta+16]>0);assert(r.grenade.parts.some(p=>p.severed));assert(r.grenade.parts.reduce((n,p)=>n+p.reserve,0)<135);pass('Native grenade hits the ragdoll and detonates before its fuse with finite blood and dismemberment');await page.shot(resolve(out,'grenade-contact.png'));
 await page.eval('__impactTest.setup({speed:0})');
 // Isolate direct impact from blast damage and cross a head in one physics tick.
 await page.eval(String.raw`(async()=>{const g=__smearGPU,d=g.device,code=__smearComputeShaders.common+'\n'+__smearComputeShaders.compute+'\n@compute @workgroup_size(1) fn fastProbe(){let p=bodies[2].p.xyz;spawnOrdnance(1u,p+vec3f(1,0,0),vec3f(-260,0,0),.065,77u);}';const module=d.createShaderModule({code});const pipeline=await d.createComputePipelineAsync({layout:d.createPipelineLayout({bindGroupLayouts:[g.computeLayout]}),compute:{module,entryPoint:'fastProbe'}});g.uniforms(1);const e=d.createCommandEncoder(),p=e.beginComputePass();p.setBindGroup(0,g.computeGroup,[0]);p.setPipeline(pipeline);p.dispatchWorkgroups(1);p.setPipeline(g.computePipelines.ordnance);p.dispatchWorkgroups(2);p.setPipeline(g.computePipelines.projectileImpacts);p.dispatchWorkgroups(1);p.end();d.queue.submit([e.finish()]);await d.queue.onSubmittedWorkDone();})()`);
 r.direct=await page.eval('__smear.state()');w=await page.eval('__arsenal.words()');assert(w[meta+16]>0);assert(r.direct.parts[2].damage>0);assert(Math.hypot(...r.direct.parts[2].v)>2);assert(r.direct.parts[2].reserve<9);assert(r.direct.parts.every(p=>!p.severed));pass('A 260 m/s swept grenade cannot tunnel through a head; direct damage, impulse and paid spray occur before the blast pass');
 await page.eval('__smear.reset();__smear.step(0);__smearGPU.bodyCount=0;__smearGPU.syncCounts();__smear.view([-3,2,-6],[-3,2,-8]);__smear.pointer(800,500);__smear.tool(4);__smear.grenade();__smear.render();__smear.step(45)');w=await page.eval('__arsenal.words()');assert.equal(w[58],0);assert((await page.eval('__arsenal.ord()')).some(o=>o.kind===1));await page.eval('__smear.step(140)');assert.equal((await page.eval('__arsenal.words()'))[58],1);pass('A missed grenade still bounces off the room and detonates once on its fuse');
 await page.eval('__impactTest.setup({speed:0})');const aim=(await page.eval('__smear.state()')).parts[0].p;await page.eval(`__smear.view([${aim[0]},${aim[1]},${aim[2]+2.2}],${JSON.stringify(aim)});__smear.pointer(800,500)`);for(const type of ['keyDown','keyUp'])await page.call('Input.dispatchKeyEvent',{type,code:'Digit6',key:'6'});assert.equal((await page.eval('__smear.controls.state()')).tool,5);await page.mouse('mousePressed',800,500);await page.mouse('mouseReleased',800,500);await page.eval('__smear.render()');assert((await page.eval('__arsenal.ord()')).some(o=>o.kind===4));await page.eval('__smearGPU.updateToolPresentation(0,{tool:5,panel:null,time:0,left:false});__smear.render()');await page.shot(resolve(out,'rocket-flight.png'));await page.eval('__smear.step(24)');w=await page.eval('__arsenal.words()');assert.equal(w[meta+17],1);assert.equal(w[58],1);assert(w[meta+16]>0);pass('Digit 6 and native fire launch a visible 38 m/s rocket with a contact explosion');
 await page.eval('__smear.reset();__smear.step(0);__smearGPU.bodyCount=0;__smearGPU.syncCounts();__smear.view([-3,2,-5],[-3,2,-8]);__smear.pointer(800,500);__smear.tool(5);__smear.rocket();__smear.render();__smear.step(24)');assert.equal((await page.eval('__arsenal.words()'))[58],1);assert(!(await page.eval('__arsenal.ord()')).some(o=>o.kind===4));pass('Rocket contact with a room wall explodes once without waiting for a fuse');
 await page.eval('(async()=>{__smear.reset();await __smear.step(0);__smearGPU.bodyCount=0;__smearGPU.syncCounts();__smear.view([-6.45,.55,.5],[-6.45,.55,-1.8]);__smear.pointer(800,500);for(let i=0;i<3;i++){__smearGPU.shoot();__smear.render();await __smearGPU.device.queue.onSubmittedWorkDone();}})()');r.boards=await page.eval('__arsenal.ord()');assert.equal(r.boards.filter(o=>o.kind===5).length,6);assert.equal(r.boards.filter(o=>o.kind===3).length,16+3*5);assert(r.boards.filter(o=>o.kind===5).every(o=>o.r*6>.75));await page.eval('__smear.step(1080)');r.lasting=await page.eval('__arsenal.ord()');assert.equal(r.lasting.filter(o=>o.kind===5).length,6);assert(r.lasting.filter(o=>o.kind===5).some(o=>o.sleep));await page.eval('__smear.view([-4,2,1],[-6,.1,-1.8]);__smear.render()');await page.shot(resolve(out,'lasting-boards.png'));pass('Crates leave six substantial planks and sixteen fracture splinters plus five chips per bullet; boards settle and remain after nine seconds');
 r.audio=await page.eval('__smear.compute.audio()');assert(r.audio.enabled&&r.audio.state==='running');assert.deepEqual((await page.eval('__smear.state()')).errors,[]);r.logs=page.logs;assert(!page.logs.some(s=>/^error:|^EXCEPTION:/.test(s)));r.passed=true;console.log('COMPLETE '+r.checks.length+' arsenal checks passed');
}catch(e){r.error=e.stack;console.error(e.stack);process.exitCode=1;}finally{if(page){r.logs=page.logs;page.kill();}fs.writeFileSync(resolve(out,'receipt.json'),JSON.stringify(r,null,2));}
