import fs from 'node:fs';import assert from 'node:assert/strict';import {resolve} from 'node:path';import {pathToFileURL} from 'node:url';import {spawnSync} from 'node:child_process';import {createHash} from 'node:crypto';
import {launch,until,sleep} from './cdp.mjs';import {installBatFixture} from './bat-fixture.mjs';
const out=resolve('tools/out/bat-v42-pass/recordings');fs.mkdirSync(out,{recursive:true});const receipt={at:new Date().toISOString(),scenario:'One real mouse swing with damage 2.5 and fragility 2 (maximum saved tuning)',clips:[]};
const encode=args=>{const r=spawnSync('ffmpeg',['-nostdin','-hide_banner','-loglevel','error','-y',...args],{encoding:'utf8',windowsHide:true,timeout:120000});assert.ifError(r.error);assert.equal(r.status,0,r.stderr);};
for(const label of ['before','after']){
 const file=label==='before'?'tools/out/bat-v42-pass/before/index.html':'index.html',page=await launch({port:9794,width:1600,height:1000,headless:true}),clip={label,profile:page.dir,sha256:createHash('sha256').update(fs.readFileSync(file)).digest('hex')};receipt.clips.push(clip);
 try{
  await page.goto(pathToFileURL(resolve(file)).href+'?defaults=1');await until(()=>page.eval('!!window.__smearComputeReady'),{timeout:90000});await page.eval('__smear.manual(true)');await page.mouse('mousePressed',800,120);await page.mouse('mouseReleased',800,120);await installBatFixture(page);await page.eval('__batTest.setup({damage:2.5,fragility:2})');
  await page.eval(`(()=>{window.__chunks=[];const tap=__smear.compute.audioTap();window.__stream=new MediaStream([...__smearGPU.canvas.captureStream(30).getVideoTracks(),...tap.stream.getAudioTracks()]);window.__recorder=new MediaRecorder(__stream,{mimeType:'video/webm;codecs=vp9,opus',videoBitsPerSecond:14000000});__recorder.ondataavailable=e=>{if(e.data.size)__chunks.push(e.data)};__recorder.start(1000);__smear.render();})()`);
  await sleep(200);await page.eval('__smear.manual(false)');await page.mouse('mousePressed',800,500);await page.mouse('mouseReleased',800,500);await sleep(320);await page.shot(resolve(out,label+'-impact.png'));await sleep(250);await page.eval('__smear.fly();__smear.view([-5.5,2.7,6.7],[-3,.7,2])');await sleep(2200);await page.eval('__smear.manual(true)');await page.shot(resolve(out,label+'-settled.png'));clip.state=await page.eval('__batTest.snapshot()');assert.equal(clip.state.swings,1);assert.equal(clip.state.hits,1);assert.equal(clip.state.cuts.length,label==='before'?1:0);
  const data=await page.eval(`new Promise(resolve=>{__recorder.onstop=()=>{const f=new FileReader();f.onload=()=>resolve(f.result.split(',')[1]);f.readAsDataURL(new Blob(__chunks,{type:'video/webm'}));__stream.getTracks().forEach(t=>t.stop());};__recorder.stop();})`);fs.writeFileSync(resolve(out,label+'.webm'),Buffer.from(data,'base64'));encode(['-i',resolve(out,label+'.webm'),'-vf','fps=30','-c:v','libx264','-preset','fast','-crf','18','-pix_fmt','yuv420p','-c:a','aac','-b:a','192k','-movflags','+faststart',resolve(out,label+'.mp4')]);clip.audio=await page.eval('__smear.compute.audio()');assert(clip.audio.enabled&&clip.audio.state==='running');assert.deepEqual(page.logs.filter(s=>/^EXCEPTION:|^error:/i.test(s)),[]);console.log('Captured '+label);
 }finally{page.kill();fs.writeFileSync(resolve(out,'capture.json'),JSON.stringify(receipt,null,2));}
}
encode(['-i',resolve(out,'before.mp4'),'-i',resolve(out,'after.mp4'),'-filter_complex',"[0:v]scale=800:500,setpts=PTS-STARTPTS,drawtext=font=Arial:text='V41 / ONE SWING / MAX DAMAGE + FRAGILITY':x=15:y=15:fontsize=17:fontcolor=white:box=1:boxcolor=black@0.7[a];[1:v]scale=800:500,setpts=PTS-STARTPTS,drawtext=font=Arial:text='V42 / SAME SWING AND SETTINGS':x=15:y=15:fontsize=17:fontcolor=white:box=1:boxcolor=black@0.7[b];[a][b]hstack=inputs=2:shortest=1[v];[0:a]pan=stereo|c0=c0|c1=0*c0[al];[1:a]pan=stereo|c0=0*c0|c1=c0[ar];[al][ar]amix=inputs=2:normalize=0[a]",'-map','[v]','-map','[a]','-shortest','-c:v','libx264','-preset','fast','-crf','18','-pix_fmt','yuv420p','-c:a','aac','-movflags','+faststart',resolve(out,'compare-bat.mp4')]);
receipt.passed=true;fs.writeFileSync(resolve(out,'capture.json'),JSON.stringify(receipt,null,2));console.log('COMPLETE V41/V42 bat comparison');
