import fs from 'node:fs';import assert from 'node:assert/strict';import {resolve} from 'node:path';import {pathToFileURL} from 'node:url';import {createHash} from 'node:crypto';import {launchComputeBrowser} from './compute-browser.mjs';import {until} from './cdp.mjs';import {installDestructionFixture} from './destruction-fixture.mjs';
const browser=process.argv.includes('firefox')?'firefox':'chrome',label=process.argv.find(a=>/^(round-|final)/.test(a))||'round-01',out=resolve('tools/out/destruction-pass',label+'-bleeding-'+browser);fs.mkdirSync(out,{recursive:true});const page=await launchComputeBrowser({port:9728,width:1600,height:1000}),r={browser,browserProfile:page.dir,buildSHA256:createHash('sha256').update(fs.readFileSync('index.html')).digest('hex'),checks:[],wounds:[],ceiling:{}};
try{
 await page.goto(pathToFileURL(resolve('index.html')).href+'?defaults=1');await until(()=>page.eval('!!window.__smearComputeReady'),{timeout:90000});await page.eval('__smear.manual(true)');await installDestructionFixture(page);
 await page.eval(`(async()=>{const g=__smearGPU,d=g.device,module=d.createShaderModule({code:__smearComputeShaders.common+'\n'+__smearComputeShaders.compute+'\n@compute @workgroup_size(1) fn woundProbe(){var b=bodies[2];b.blood.y=10;bodies[2]=bleedPart(2u,b);}' });window.__woundProbe=await d.createComputePipelineAsync({layout:d.createPipelineLayout({bindGroupLayouts:[g.computeLayout]}),compute:{module,entryPoint:'woundProbe'}});})()`.replaceAll("+'\n'","+'\\n'").replace("+'\n@", "+'\\n@"));
 for(const scenario of ['finite','empty','full','stopped']){
  const reserve=scenario==='empty'?0:.08;await page.eval(`(async()=>{__smear.reset();__smear.preset('default');await __smear.step(0);const g=__smearGPU,d=g.device,e=d.createCommandEncoder();e.clearBuffer(g.workBuffer);e.clearBuffer(g.particleBuffer);d.queue.submit([e.finish()]);const a=new Float32Array(await __destructionFixture.read(g.seedBuffer,0,g.seedBuffer.size));a.set([0,0,0,${reserve}],2*104+32);a.set([1.6,10,0,100],2*104+36);d.queue.writeBuffer(g.bodyBuffer,0,a);d.queue.writeBuffer(g.workBuffer,(g.destructionBase+2*8)*4,new Uint32Array([1,0,0,0,0,4,${scenario==='stopped'?1:0},0]));${scenario==='full'?'d.queue.writeBuffer(g.workBuffer,64*4,new Uint32Array(900).fill(1));d.queue.writeBuffer(g.workBuffer,9*4,new Uint32Array([900]));':''}for(let k=0;k<40;k++){g.uniforms(1);const e=d.createCommandEncoder(),p=e.beginComputePass();p.setBindGroup(0,g.computeGroup,[0]);p.setPipeline(__woundProbe);p.dispatchWorkgroups(1);p.end();d.queue.submit([e.finish()]);g.steps+=20;}await d.queue.onSubmittedWorkDone();})()`);
  const a=await page.eval(`(async()=>{const g=__smearGPU,b=new Float32Array(await __destructionFixture.read(g.bodyBuffer,2*104*4,104*4)),p=new Float32Array(await __destructionFixture.read(g.particleBuffer,0,900*64)),slots=new Uint32Array(await __destructionFixture.read(g.workBuffer,256,3600)),w=new Uint32Array(await __destructionFixture.read(g.workBuffer,0,256));let volume=0;for(let i=0;i<900;i++)if(slots[i])volume+=p[i*16+12];return {reserve:b[35],coat:b[32],airborne:volume,emitted:w[62],particles:w[9]};})()`);r.wounds.push({scenario,...a});assert(Math.abs(a.reserve*.10+a.coat*.02+a.airborne-reserve*.10)<1e-7);if(scenario==='finite'){assert(a.reserve<1e-6);assert(a.emitted>=3);}else{assert.equal(a.emitted,0);assert(Math.abs(a.reserve-reserve)<1e-7);}
 }r.checks.push('Open sockets exhaust a finite reserve exactly; empty, stopped and saturated-pool wounds create no extra liquid');console.log('PASS '+r.checks.at(-1));
 for(const rate of [0,.35,1]){
  await page.eval(`__destructionFixture.ceiling(${rate})`);const before=await page.eval('__destructionFixture.liquid()');await page.eval('__destructionFixture.advance(120)');const one=await page.eval('__destructionFixture.liquid()');await page.eval('__destructionFixture.advance(600)');const six=await page.eval('__destructionFixture.liquid()');r.ceiling[rate]={before,one,six};assert(Math.abs(six.total/before.total-1)<.03);if(rate===1){assert(new Set(one.drops.map(p=>p.radius.toFixed(5))).size>8);assert(one.runoff>30);await page.shot(resolve(out,'ceiling-after-six-seconds.png'));}
 }assert.equal(r.ceiling[0].six.runoff,0);assert(r.ceiling[.35].one.runoff<r.ceiling[1].one.runoff*.7);assert(r.ceiling[.35].six.retained>r.ceiling[1].six.retained);r.checks.push('Ceiling releases varied droplets, conserves retained and airborne supply, and respects lower and zero drip settings');console.log('PASS '+r.checks.at(-1));r.errors=await page.eval('__smearGPU.errors');assert.deepEqual(r.errors,[]);r.passed=true;console.log('COMPLETE '+r.checks.length+' checks passed');
}catch(e){r.error=e.stack;console.error(e);process.exitCode=1;}finally{fs.writeFileSync(resolve(out,'receipt.json'),JSON.stringify(r,null,2));await page.kill();}
