import fs from 'node:fs';import assert from 'node:assert/strict';import {resolve} from 'node:path';import {pathToFileURL} from 'node:url';import {createHash} from 'node:crypto';import {launch,until,sleep} from './cdp.mjs';import {installBatFixture} from './bat-fixture.mjs';import {installJunkFixture} from './junk-fixture.mjs';
const label=process.argv[2]||'current',out=resolve('tools/out/junk-v43-pass/'+label+'-brawl');fs.mkdirSync(out,{recursive:true});let page;const r={at:new Date().toISOString(),sha256:createHash('sha256').update(fs.readFileSync('index.html')).digest('hex'),checks:[]};const check=s=>{r.checks.push(s);console.log('PASS '+s);};const tap=async code=>{for(const type of ['keyDown','keyUp'])await page.call('Input.dispatchKeyEvent',{type,code,key:code.slice(-1),windowsVirtualKeyCode:code.charCodeAt(code.length-1)});};
try{
 page=await launch({port:9794,width:1600,height:1000,headless:true});r.profile=page.dir;await page.goto(process.env.SMEAR_TEST_URL||pathToFileURL(resolve('index.html')).href+'?defaults=1');await until(()=>page.eval('!!window.__smearComputeReady'),{timeout:90000});await page.eval('__smear.manual(true)');await page.mouse('mousePressed',800,120);await page.mouse('mouseReleased',800,120);await installBatFixture(page);await installJunkFixture(page);
 r.actions=[];for(const [code,action]of [['KeyU',22],['KeyK',21]]){
  await page.eval('__batTest.setup({part:0})');await page.eval('__junkTest.standing()');await page.eval('__smear.manual(false)');await tap(code);await sleep(165);await page.shot(resolve(out,code+'-contact.png'));await sleep(650);await page.eval('__smear.manual(true)');const state=await page.eval('__batTest.snapshot()'),stats=await page.eval('__junkTest.stats()'),bodies=await page.eval('__junkTest.bodies()');r.actions.push({code,state,stats,bodies});assert.equal(stats.brawls,1);assert.equal(stats.hits,1);assert.equal(state.cuts.length,0);if(action===22){assert.equal(bodies[1*104+75],2);assert(state.jointDamage.every(n=>n<1));}else assert.equal(bodies[1*104+75],0);
 }check('Native U shoves a standing buddy into a brace; native K knocks him down, and neither directly severs joints');
 await page.eval('__batTest.setup({part:0})');await page.eval('__junkTest.standing()');const before=await page.eval('__junkTest.bodies()');await page.eval('__smearGPU.inputAction=22;__smearGPU.submit(0)');await page.eval('__utilityTest.advance(12)');const braced=await page.eval('__junkTest.bodies()');r.brace={before:before.slice(3*104+84,3*104+88),after:braced.slice(3*104+84,3*104+88)};assert(r.brace.after.some((v,i)=>Math.abs(v-r.brace.before[i])>.2));check('The hit reaction changes the upper-arm pose targets instead of merely displaying a hit effect');
 await page.eval('__batTest.setup({part:0})');await page.eval('__smear.manual(false)');await tap('KeyK');await sleep(30);await tap('KeyU');await sleep(30);await tap('KeyK');await sleep(600);await page.eval('__smear.manual(true)');assert.equal((await page.eval('__junkTest.stats()')).brawls,1);await page.eval('__batTest.setup({part:0})');await page.eval('__smear.kick();__smear.controls.pause();__smear.manual(false)');await sleep(300);await page.eval('__smear.manual(true)');assert.equal((await page.eval('__junkTest.stats()')).brawls,0);check('Kick/shove share a cooldown; pausing cancels a pending strike');
 await page.eval('__batTest.setup({part:0})');await page.eval('__smear.view([-3,1.2,9],[-3,1.2,4]);__smearGPU.inputAction=21;__smearGPU.submit(0)');assert.equal((await page.eval('__junkTest.stats()')).hits,0);check('Close-range actions cannot reach a buddy through the room wall');
 r.gait=[];for(const injured of [false,true]){
  await page.eval('__batTest.setup({part:0})');await page.eval('__junkTest.standing()');if(injured)await page.eval('__junkTest.injureLeg()');await page.eval(`(async()=>{const g=__smearGPU,a=new Float32Array(await __junkTest.bodies());for(let i=0;i<15;i++)a.set([-3,0,7,0],i*104+76);g.device.queue.writeBuffer(g.bodyBuffer,0,a);__smear.tune({walking:true,recover:false});await __utilityTest.advance(120);})()`);const a=await page.eval('__junkTest.bodies()');r.gait.push({injured,speed:a[104+92],root:a.slice(104+72,104+76),feet:[a.slice(8*104+92,8*104+96),a.slice(14*104+92,14*104+96)]});
 }assert(r.gait[1].speed<r.gait[0].speed*.85);assert(r.gait[1].speed>0);check('An injured attached leg produces a slower, asymmetric walking gait while the healthy buddy keeps the normal cadence');
 r.errors=await page.eval('__smearGPU.errors');assert.deepEqual(r.errors,[]);assert(!page.logs.some(s=>/^error:|^EXCEPTION:/.test(s)));r.result='COMPLETE brawl and buddy reaction checks';console.log(r.result);
}catch(e){r.result='FAIL';r.error=e.stack;console.error(e.stack);process.exitCode=1;}finally{if(page)page.kill();fs.writeFileSync(resolve(out,'verification.json'),JSON.stringify(r,null,2)+'\n');}
