import fs from 'node:fs';
import assert from 'node:assert/strict';
import {resolve} from 'node:path';
import {pathToFileURL} from 'node:url';
import {createHash} from 'node:crypto';
import {launch,until,sleep} from './cdp.mjs';
import {installDestructionFixture} from './destruction-fixture.mjs';
const out=resolve('tools/out/buddy-pass/'+(process.argv[2]||'round-01'));fs.mkdirSync(out,{recursive:true});
const page=await launch({port:9750,width:1600,height:1000,headless:true});
const receipt={at:new Date().toISOString(),profile:page.dir,buildSHA256:createHash('sha256').update(fs.readFileSync('index.html')).digest('hex'),checks:[]};
const pass=s=>{receipt.checks.push(s);console.log('PASS '+s);};
async function tap(code){for(const type of ['keyDown','keyUp'])await page.call('Input.dispatchKeyEvent',{type,code,key:code==='Escape'?'Escape':code.slice(-1),windowsVirtualKeyCode:code==='Escape'?27:code.at(-1).charCodeAt(0)});}
async function click(){await page.mouse('mousePressed',800,500);await page.mouse('mouseReleased',800,500);await until(()=>page.eval('!__smear.buddy.state().busy'));}
async function preview(p){await page.eval(`__smear.view([${p[0]},2,${p[2]+2}],${JSON.stringify(p)});__smear.pointer(800,500);__smear.render()`);return page.eval('__buddyRead()');}
try{
 await page.goto(pathToFileURL(resolve('index.html')).href+'?defaults=1');await until(()=>page.eval('!!window.__smearComputeReady'),{timeout:90000});
 await page.eval('__smear.manual(true)');await page.mouse('mousePressed',800,140);await page.mouse('mouseReleased',800,140);await installDestructionFixture(page);
 await page.eval(`(()=>{const g=__smearGPU;window.__buddyRead=async()=>Array.from(new Uint32Array(await __destructionFixture.read(g.workBuffer,1006*4,32)));window.__buddyHash=async()=>{const digest=async(b,o,n)=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',await __destructionFixture.read(b,o,n)))).join(',');return {paint:await digest(g.paintBuffer,0,g.paintBuffer.size),wet:await digest(g.wetBuffer,0,g.wetBuffer.size),otherBodies:await digest(g.bodyBuffer,15*104*4,30*104*4),otherCuts:await digest(g.workBuffer,(g.destructionBase+15*8)*4,30*8*4),props:await g.propsState(),drops:await digest(g.particleBuffer,0,g.particleBuffer.size)};};})()`);
 await tap('KeyR');assert.equal((await page.eval('__smear.buddy.state()')).placement,null);pass('Restore requires a selected buddy');
 await page.eval('__smear.reset();__smear.step(0)');const torso=await page.eval('__smear.project(0,"Torso")');await page.eval(`__smear.view([${torso.world[0]},3,${torso.world[2]+3}],${JSON.stringify(torso.world)});__smear.pointer(800,500);__smear.tool(0)`);
 await page.mouse('mousePressed',800,500);await page.eval('__smear.render()');await until(()=>page.eval('!!__smear.buddy.state().selected || !!(__smear.buddy.state().selected===0)'));assert.equal((await page.eval('__smear.buddy.state()')).selected,0);
 await tap('KeyR');assert.equal((await page.eval('__smear.state()')).grab,null);assert.equal((await page.eval('__smear.buddy.state()')).placement.base,0);await page.mouse('mouseReleased',800,500);await tap('Escape');pass('R selects the grabbed rig for restoration and cancels its grab without throwing');
 await page.eval(`(async()=>{const s=await __smear.state();__smear.blast(s.parts[0].p);__smear.render();const g=__smearGPU;g.device.queue.writeBuffer(g.workBuffer,(g.destructionMeta+32)*4,new Uint32Array([65536]));g.inputAction=2;__smear.render();await g.device.queue.onSubmittedWorkDone();})()`);
 const damaged=await page.eval('__smear.state()');assert(damaged.parts.slice(0,15).some(p=>p.severed));
 await tap('KeyR');receipt.beforePreview=await page.eval('({buddy:__smear.buddy.state(),controls:__smear.controls.state()})');let data=await preview([-3,0,5]);receipt.afterPreview=await page.eval('({buddy:__smear.buddy.state(),controls:__smear.controls.state(),errors:__smearGPU.errors})');receipt.validPreview=data;assert.equal(data[2],1);await page.shot(resolve(out,'restore-preview.png'));
 const before=await page.eval('__buddyHash()');await click();const restored=await page.eval('__smear.state()');const after=await page.eval('__buddyHash()');assert.deepEqual(after,before);assert.equal(restored.bodyCount,45);assert(restored.parts.slice(0,15).every(p=>!p.severed&&p.socketMask===0&&p.reserve===9&&p.damage===0&&p.bleeding===0));assert(restored.maxJoint<.025);assert(restored.parts.slice(0,15).every(p=>Math.hypot(...p.v)===0));assert.equal((await page.eval('__smear.buddy.state()')).placement,null);receipt.restored=restored.parts.slice(0,15);pass('Restoration reconnects all 15 parts and refills once, preserving exact room/skin paint, all liquid, airborne drops, other bodies/cuts and prop state');
 await page.eval('__smear.step(120)');assert((await page.eval('__smear.state()')).maxJoint<.15);await page.shot(resolve(out,'restored.png'));pass('The restored rig survives 120 physics ticks with bounded joints');
 await tap('KeyN');data=await preview([-3,0,5]);assert.equal(data[2],5);await click();assert.equal((await page.eval('__smear.state()')).bodyCount,45);assert((await page.eval('__smear.buddy.state()')).placement);pass('Occupied placement is rejected without consuming a buddy slot');
 await page.eval('__smear.view([0,2,4],[0,3,-8]);__smear.pointer(800,500);__smear.render()');assert.equal((await page.eval('__buddyRead()'))[2],2);await click();assert.equal((await page.eval('__smear.state()')).bodyCount,45);pass('Wall and non-floor aiming cannot place a buddy');
 data=await preview([7.5,0,2]);assert.equal(data[2],3);await click();assert.equal((await page.eval('__smear.state()')).bodyCount,45);
 data=await preview([5.65,0,4.2]);assert.equal(data[2],4);await click();assert.equal((await page.eval('__smear.state()')).bodyCount,45);
 await page.eval('__smear.view([3,2,5.3],[3,0,5]);__smear.pointer(800,500);__smear.render()');assert.equal((await page.eval('__buddyRead()'))[2],7);pass('Room edges, prop intersections and the player keep placement invalid');
 data=await preview([3,0,5]);assert.equal(data[2],1);await page.eval('__smearGPU.placement.yaw=Math.PI/2;__smear.render()');await page.shot(resolve(out,'add-preview.png'));await click();const added=await page.eval('__smear.state()');assert.equal(added.bodyCount,60);assert.equal(added.parts[46].reserve,9);assert(Math.abs(added.parts[46].q[1])>.69);assert(added.maxJoint<.15);pass('N and a normal click place a new, rotated buddy in the previewed clear location');
 await tap('KeyN');await preview([3,0,5]);await tap('Escape');assert.equal((await page.eval('__smear.buddy.state()')).placement,null);assert.equal((await page.eval('__buddyRead()'))[0],0);await tap('KeyN');await tap('Digit2');assert.equal((await page.eval('__smear.buddy.state()')).placement,null);pass('Escape and weapon switching remove the preview without placing or firing');
 await tap('KeyN');await page.eval('window.dispatchEvent(new Event("blur"))');assert.equal((await page.eval('__smear.buddy.state()')).placement,null);pass('Focus loss cancels placement');
 await page.eval('for(let i=0;i<20;i++)__smear.add()');assert.equal((await page.eval('__smear.state()')).bodyCount,180);await tap('KeyN');assert.equal((await page.eval('__smear.buddy.state()')).placement,null);pass('The 12-buddy limit refuses placement instead of silently adding nothing');
 await page.eval('__smear.reset();__smear.step(0)');await tap('KeyN');await preview([3,0,5]);await page.eval('__smear.buddy.confirm();__smear.reset()');await until(()=>page.eval('!__smear.buddy.state().busy'));await page.eval('__smear.step(0)');assert.equal((await page.eval('__smear.state()')).bodyCount,45);assert.equal((await page.eval('__smear.buddy.state()')).placement,null);pass('Reset invalidates an in-flight placement acknowledgement');
 await page.eval(`(async()=>{const g=__smearGPU,p=g.props[3].position;__smear.view([p[0],p[1],p[2]+1.75],p);__smear.pointer(800,500);for(let i=0;i<3;i++){g.shoot();g.submit(0);await g.device.queue.onSubmittedWorkDone();}})()`);
 const blastCount=()=>page.eval('(async()=>new Uint32Array(await __destructionFixture.read(__smearGPU.workBuffer,58*4,4))[0])()');const pausedBlasts=await blastCount();assert.equal(pausedBlasts,1);await tap('KeyN');await page.eval('(async()=>{for(let i=0;i<8;i++)__smear.render();await __smearGPU.device.queue.onSubmittedWorkDone();})()');assert.equal(await blastCount(),pausedBlasts);await tap('Escape');pass('Preview rendering cannot advance a pending barrel chain while simulation is paused');
 await page.eval('__smear.reset();__smear.step(0)');
 await page.eval('__smear.view([-3,2,7],[-3,0,3]);__smear.manual(false);__smear.controls.mode("fps")');
 const resume=await page.eval('(()=>{const r=document.getElementById("play-resume").getBoundingClientRect();return {x:r.x+r.width/2,y:r.y+r.height/2};})()');await page.mouse('mousePressed',resume.x,resume.y);await page.mouse('mouseReleased',resume.x,resume.y);await until(()=>page.eval('__smear.controls.state().locked&&!__smear.controls.state().paused'));
 await tap('KeyN');assert((await page.eval('__smear.buddy.state()')).placement);await page.call('Input.dispatchKeyEvent',{type:'keyDown',code:'KeyE',key:'e',windowsVirtualKeyCode:69});await sleep(250);await page.call('Input.dispatchKeyEvent',{type:'keyUp',code:'KeyE',key:'e',windowsVirtualKeyCode:69});assert((await page.eval('__smear.buddy.state()')).placement.yaw>.2);
 await tap('Escape');assert.equal((await page.eval('__smear.buddy.state()')).placement,null);assert((await page.eval('__smear.controls.state()')).locked);await tap('Escape');await until(()=>page.eval('__smear.controls.state().paused&&!__smear.controls.state().locked'));
 await tap('KeyB');for(const selector of ['[data-category="room"]','#toy-add']){const p=await page.eval(`(()=>{const e=document.querySelector('${selector}');e.scrollIntoView({block:'center'});const b=e.getBoundingClientRect();return{x:b.x+20,y:b.y+15};})()`);await page.mouse('mousePressed',p.x,p.y);await page.mouse('mouseReleased',p.x,p.y);}await until(()=>page.eval('!!__smear.buddy.state().placement'));assert(!(await page.eval('__smear.controls.state()')).locked);assert(!(await page.eval('__smear.controls.state()')).paused);assert.equal(await page.eval('document.getElementById("play-menu").style.display'),'none');await tap('Escape');assert(!(await page.eval('__smear.controls.state()')).paused);assert(!(await page.eval('__smear.controls.state()')).locked);pass('Locked N/E placement keeps lock; Add from pause uses an unobstructed free-cursor preview and Escape returns to the free cursor without recapturing');

 await page.eval('__smear.manual(true);__smear.grab(0,"Torso")');await page.eval('__smear.release(false);__smear.manual(false);__smear.controls.mode("fps");__smear.buddy.begin(true)');await until(()=>page.eval('!!__smear.buddy.state().placement'));assert(!(await page.eval('__smear.controls.state()')).locked);assert.equal(await page.eval('document.getElementById("play-menu").style.display'),'none');await tap('Escape');assert(!(await page.eval('__smear.controls.state()')).paused);pass('Restore from pause also enters cursor placement and returns cleanly to the free cursor without stealing mouse capture');
 const state=await page.eval('__smear.state()');assert.deepEqual(state.errors,[]);assert.equal(state.normalPaintReadbacks,0);receipt.logs=page.logs;assert(!page.logs.some(s=>/^error:|^EXCEPTION:/.test(s)));receipt.passed=true;console.log('COMPLETE '+receipt.checks.length+' buddy checks passed');
}catch(error){receipt.failureState=await page.eval('({buddy:__smear.buddy.state(),controls:__smear.controls.state()})').catch(()=>null);receipt.logs=page.logs;await page.shot(resolve(out,'failure.png')).catch(()=>{});receipt.error=error.stack;console.error(error);process.exitCode=1;}finally{page.kill();fs.writeFileSync(resolve(out,'receipt.json'),JSON.stringify(receipt,null,2));}
