import fs from 'node:fs';import assert from 'node:assert/strict';import {resolve} from 'node:path';import {pathToFileURL} from 'node:url';import {spawnSync} from 'node:child_process';import {createHash} from 'node:crypto';import {launch,until,sleep} from './cdp.mjs';
const out=resolve('tools/out/buddy-pass/recordings');fs.mkdirSync(out,{recursive:true});
const receipt={at:new Date().toISOString(),clips:[]};
function encode(args){const p=spawnSync('ffmpeg',['-nostdin','-hide_banner','-loglevel','error','-y',...args],{encoding:'utf8',windowsHide:true,timeout:120000});assert.ifError(p.error);assert.equal(p.status,0,p.stderr);}
for(const [name,path,version]of [['before','tools/out/buddy-pass/before/index.html','V34'],['after','index.html','V35']]){
 const page=await launch({port:9751,width:1600,height:1000,headless:true});const clip={name,version,profile:page.dir,buildSHA256:createHash('sha256').update(fs.readFileSync(path)).digest('hex')};receipt.clips.push(clip);
 async function tap(code){for(const type of ['keyDown','keyUp'])await page.call('Input.dispatchKeyEvent',{type,code,key:code.at(-1),windowsVirtualKeyCode:code.at(-1).charCodeAt(0)});}
 async function click(){await page.mouse('mousePressed',800,500);await sleep(40);await page.mouse('mouseReleased',800,500);}
 try{
  await page.goto(pathToFileURL(resolve(path)).href+'?defaults=1');await until(()=>page.eval('!!window.__smearComputeReady'),{timeout:90000});await page.eval('__smear.manual(true)');await page.mouse('mousePressed',800,140);await page.mouse('mouseReleased',800,140);
  // One identical initial standing pose for both builds. All subsequent damage,
  // selection, restoration and throwing use game controls and native physics.
  await page.eval(`(async()=>{__smear.reset();__smear.preset('default');__smear.tune({walking:false,recover:false});await __smear.step(0);const g=__smearGPU,d=g.device,b=g.buffer('explicit capture initialization',g.bodyBuffer.size,GPUBufferUsage.MAP_READ|GPUBufferUsage.COPY_DST),e=d.createCommandEncoder();e.copyBufferToBuffer(g.seedBuffer,0,b,0,b.size);d.queue.submit([e.finish()]);await b.mapAsync(GPUMapMode.READ);const a=new Float32Array(b.getMappedRange().slice(0));b.unmap();b.destroy();for(let i=0;i<15;i++){const s=g.sourceBodies[i],p=s.restP.clone().add(new g.THREE.Vector3(-3,.025,3));a.set(p.toArray(),i*104);a.set(s.restQ.toArray(),i*104+4);a.fill(0,i*104+8,i*104+16);a.set([0,0,0,9],i*104+32);a.set([0,0,0,100],i*104+36);a.set([-3,0,3,2],i*104+72);a.set([-3,0,3,100],i*104+76);}d.queue.writeBuffer(g.bodyBuffer,0,a);g.bodyCount=15;g.syncCounts();__smear.view([-3,2.4,7],[-3,1.3,3]);__smear.pointer(800,500);__smear.tool(0);await __smear.step(40);})()`);
  await tap('KeyF');
  await page.eval(`(()=>{window.__chunks=[];const tap=__smear.compute.audioTap();window.__stream=new MediaStream([...__smearGPU.canvas.captureStream(30).getVideoTracks(),...tap.stream.getAudioTracks()]);window.__recorder=new MediaRecorder(__stream,{mimeType:'video/webm;codecs=vp9,opus',videoBitsPerSecond:14000000,audioBitsPerSecond:192000});__recorder.ondataavailable=e=>{if(e.data.size)__chunks.push(e.data)};__recorder.start(1000);__smear.manual(false);})()`);
  await sleep(650);await page.mouse('mousePressed',800,500);await until(()=>page.eval('__smearGPU.input().held'),{timeout:2000,label:'native buddy selection'});await sleep(100);await page.mouse('mouseReleased',800,500);
  await page.eval('__smear.tool(1);__smear.view([-3,2.4,7],[-3,1.733,3]);__smear.pointer(800,500)');
  for(let i=0;i<4;i++){const head=(await page.eval('__smear.state()')).parts[2].p;await page.eval('__smear.view([-3,2.4,7],'+JSON.stringify(head)+');__smear.pointer(800,500)');await click();await sleep(170);}await sleep(700);clip.damaged=await page.eval('__smear.state()');assert(clip.damaged.parts.some(p=>p.severed));
  await page.eval('__smear.tool(0);__smear.view([-3,2.4,7],[-3,0,3]);__smear.pointer(800,500)');await tap('KeyR');await sleep(850);await page.shot(resolve(out,name+'-preview.png'));await click();await sleep(850);
  clip.afterRestore=await page.eval('__smear.state()');if(name==='after')assert(clip.afterRestore.parts.every(p=>!p.severed));
  await page.eval('__smear.view([-3,2.4,7],[-3,1.2,3]);__smear.pointer(800,500)');await page.mouse('mousePressed',800,500);await sleep(150);clip.throwPicked=await page.eval('__smearGPU.input().held');if(name==='after')assert(clip.throwPicked);
  for(let i=1;i<=8;i++){await page.mouse('mouseMoved',800+i*28,500-i*6);await sleep(18);}await page.mouse('mouseReleased',1024,452);await sleep(60);clip.thrown=await page.eval('__smear.state()');if(name==='after')assert(clip.thrown.parts.some(p=>Math.hypot(...p.v)>1));await sleep(1040);
  await page.eval('__smear.view([2,3.6,7],[-3,.8,3])');await sleep(2300);await page.shot(resolve(out,name+'-aftermath.png'));
  await page.eval('__smear.manual(true)');const data=await page.eval(`new Promise(resolve=>{__recorder.onstop=()=>{const f=new FileReader();f.onload=()=>resolve(f.result.split(',')[1]);f.readAsDataURL(new Blob(__chunks,{type:'video/webm'}));__stream.getTracks().forEach(t=>t.stop());};__recorder.stop();})`);fs.writeFileSync(resolve(out,name+'.webm'),Buffer.from(data,'base64'));
  clip.audio=await page.eval('__smear.compute.audio()');assert(clip.audio.enabled&&clip.audio.state==='running');assert.deepEqual((await page.eval('__smear.state()')).errors,[]);
  encode(['-i',resolve(out,name+'.webm'),'-vf',`fps=30,drawtext=font=Arial:text='${version} / ${name==='before'?'DISMEMBERED BUDDY':'RESTORE ONE BUDDY / KEEP THE ROOM'}':x=24:y=h-50:fontsize=25:fontcolor=white:box=1:boxcolor=black@0.7:boxborderw=8`,'-c:v','libx264','-preset','fast','-crf','18','-pix_fmt','yuv420p','-c:a','aac','-b:a','192k','-movflags','+faststart',resolve(out,name+'.mp4')]);console.log('Recorded '+version);
 }finally{page.kill();fs.writeFileSync(resolve(out,'capture.json'),JSON.stringify(receipt,null,2));}
}
encode(['-i',resolve(out,'before.mp4'),'-i',resolve(out,'after.mp4'),'-filter_complex','[0:v]scale=960:600,setpts=PTS-STARTPTS[a];[1:v]scale=960:600,setpts=PTS-STARTPTS[b];[a][b]hstack=inputs=2:shortest=1[v]','-map','[v]','-map','1:a','-shortest','-c:v','libx264','-preset','fast','-crf','18','-pix_fmt','yuv420p','-c:a','aac','-b:a','192k','-movflags','+faststart',resolve(out,'smear-v34-v35-buddy.mp4')]);
receipt.passed=true;fs.writeFileSync(resolve(out,'capture.json'),JSON.stringify(receipt,null,2));console.log('COMPLETE buddy comparison MP4');
