import assert from 'node:assert/strict';
import {mkdir,readFile,writeFile} from 'node:fs/promises';
import {resolve} from 'node:path';
import {pathToFileURL} from 'node:url';
import {createHash} from 'node:crypto';
import {launchComputeBrowser} from './compute-browser.mjs';
import {until} from './cdp.mjs';
import {installWetFixture} from './wet-fixture.mjs';
import {installImpactFixture} from './impact-fixture.mjs';
const label=process.argv.find(v=>/^(round-|final)/.test(v))||'round-01';
const out=resolve('tools/out/carry-pass',label+(process.argv.includes('firefox')?'-firefox':''));await mkdir(out,{recursive:true});
const page=await launchComputeBrowser({port:9685,width:1440,height:1080});
const receipt={startedAt:new Date().toISOString(),browserProfile:page.dir,buildSHA256:createHash('sha256').update(await readFile('index.html')).digest('hex'),checks:[]};
async function boot(path='index.html',query=''){
 await page.goto(pathToFileURL(resolve(path)).href+query);
 await until(async()=>{const s=await page.eval('({ready:!!window.__smearComputeReady,error:document.getElementById("failure")?.style.display==="block"?document.getElementById("failure").textContent:null})');if(s.error)throw Error(s.error);return s.ready;},{timeout:90000});await page.eval('__smear.manual(true)');
}
async function click(label,fraction){await page.eval('new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)))');const b=await page.eval(`__smear.ui().find(b=>b.label===${JSON.stringify(label)})`);assert(b,label);const x=fraction===undefined?b.x+20:b.x+9+(b.w-18)*fraction,y=b.y+16;await page.mouse('mouseMoved',x,y);await page.mouse('mousePressed',x,y);await page.mouse('mouseReleased',x,y);await page.eval('new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)))');}
async function pigment(){
 const pixels=await page.eval('__wetProbe.pixels()');
 const distance=await page.eval(`(()=>{const g=__smearGPU,b=__wetPixels,hist=new Map();let mass=0,mx=0;for(let id=0;id<16;id++){const r=g.records[id],s=g.surfaces[id];for(let y=0;y<r.height;y++)for(let x=0;x<r.width;x++){const a=b[(r.pixelOffset+x+y*r.width)*4+3];if(!a)continue;const wx=s.center.x+((x+.5)/r.width-.5)*s.w*s.u.x+((y+.5)/r.height-.5)*s.h*s.v.x;mass+=a;mx+=a*wx;hist.set(wx,(hist.get(wx)||0)+a);}}let sum=0,q95=0,q99=0;for(const [x,a]of [...hist].sort((a,b)=>a[0]-b[0])){sum+=a;if(sum<mass*.95)q95=x;if(sum<mass*.99)q99=x;}return {centroid:mx/mass,q95,q99};})()`);
 return {...pixels,...distance};
}
async function stroke(carry=2,options={},path='Array.from({length:121},(_,i)=>[-.6+i*.012,.1,2.5,0])'){
 await page.eval(`__smear.tune({carry:${carry},smudge:1.6,abrasion:0})`);await page.eval(`__wetProbe.setup(${JSON.stringify({ink:true,wet:.8,coverage:0,...options})})`);const before=await pigment();await page.eval(`__wetProbe.run(${path})`);return {before,after:await pigment()};
}
try{
 await boot('tools/out/carry-pass/before/index.html');await installWetFixture(page);receipt.baseline=await stroke();
 await boot();await page.eval('localStorage.setItem("smear.tune.v8",JSON.stringify({bleeding:2.2,smudge:2.6,abrasion:1.5,coverage:1.3}))');await boot('index.html','?qa=migrate');
 receipt.migrated=await page.eval('__smear.state().then(s=>s.tune)');assert.equal(receipt.migrated.bleeding,2.2);assert.equal(receipt.migrated.smudge,2.6);assert.equal(receipt.migrated.carry,2);assert.equal(receipt.migrated.splatSize,1);assert.equal(receipt.migrated.ceilingDrips,1);
 await page.eval('__smear.panel("tune")');await click('Effects');await click('Gentler effects');const gentle=await page.eval('__smear.state().then(s=>s.tune)');assert.equal(gentle.splatSize,.8);assert.equal(gentle.ceilingDrips,.35);assert.equal(gentle.smudge,2.6);assert.equal(gentle.bleeding,2.2);await page.shot(resolve(out,'tune-effects.png'));
 await click('V28 effects');const restored=await page.eval('__smear.state().then(s=>s.tune)');assert.equal(restored.splatSize,1);assert.equal(restored.ceilingDrips,1);assert.equal(restored.bleeding,2.2);
 await click('Impact size',.4);await click('Ceiling drips',.35);await click('Smudge');await click('Carry distance',2/3);await page.shot(resolve(out,'tune-carry.png'));await boot('index.html','?qa=persist');receipt.saved=await page.eval('__smear.state().then(s=>s.tune)');assert(Math.abs(receipt.saved.splatSize-.84)<.03);assert(Math.abs(receipt.saved.ceilingDrips-.35)<.03);assert(Math.abs(receipt.saved.carry-3)<.03);assert.equal(receipt.saved.bleeding,2.2);assert.equal(receipt.saved.smudge,2.6);
 receipt.checks.push('Old tuning migrates; actual Effects and Carry sliders persist, and both effects presets preserve custom bleeding and smudge settings');
 await page.eval('__smear.preset("default")');await installWetFixture(page);receipt.carry={};
 for(const carry of [1,2,4]){const r=await stroke(carry);receipt.carry[carry]=r;assert(Math.abs(r.after.sum/r.before.sum-1)<.02);assert.equal(r.after.blue,r.after.painted);await page.eval('__smearGPU.bodyCount=0;__smearGPU.syncCounts();__smear.view([.1,2.6,2.6],[.1,0,2.5]);__smear.render()');await page.shot(resolve(out,'carry-'+carry+'.png'));}
 assert(receipt.carry[2].after.q95>receipt.baseline.after.q95+.12);assert(receipt.carry[4].after.q95>receipt.carry[1].after.q95+.15);assert(receipt.carry[2].after.centroid>receipt.baseline.after.centroid+.05);
 receipt.checks.push('Longer carry advances the existing pigment front and centroid, with no fresh color and under 2% quantization error');
 const seam=await stroke(4,{x:-.12},'Array.from({length:100},(_,i)=>[-.12+i*.012,.1,2.5,i*.007])');assert(seam.after.tileSum[10]>seam.before.tileSum[10]+2000);assert(Math.abs(seam.after.sum/seam.before.sum-1)<.02);receipt.seam=seam;
 for(const [name,options,path]of [['dry',{wet:0},undefined],['hover',{},'Array.from({length:121},(_,i)=>[-.6+i*.012,.6,2.5,0])']]){const r=await stroke(4,options,path);assert.equal(r.after.hash,r.before.hash);receipt[name]=r;}
 receipt.checks.push('Maximum carry crosses a floor seam under rotation while conserving pigment; dry and hovering contacts leave paint unchanged');
 await installImpactFixture(page);receipt.impacts={};for(const size of [.6,.8,1]){await page.eval('__impactTest.setup({speed:12,pose:"head"})');await page.eval(`__smear.tune({splatSize:${size}})`);await page.eval('__impactTest.advance(20)');receipt.impacts[size]=await page.eval('__impactTest.read()');await page.shot(resolve(out,'impact-'+size+'.png'));}
 assert(receipt.impacts[.6].painted<receipt.impacts[1].painted*.70);assert(receipt.impacts[.8].painted<receipt.impacts[1].painted*.90);for(const size of [.6,.8]){assert.equal(receipt.impacts[size].impacts,receipt.impacts[1].impacts);assert(Math.abs(receipt.impacts[size].volume/receipt.impacts[1].volume-1)<.001);assert.deepEqual(receipt.impacts[size].parts.map(p=>p.wound),receipt.impacts[1].parts.map(p=>p.wound));}
 receipt.checks.push('Impact size reduces the print footprint of the same hard throw without changing injury or allocated blood');
 // Finite injected pool, then the complete shipping film and airborne pipeline.
 await page.eval(`(()=>{const g=__smearGPU,d=g.device;async function read(buffer,offset,size){const b=g.buffer('explicit ceiling tuning inspection',size,GPUBufferUsage.MAP_READ|GPUBufferUsage.COPY_DST),e=d.createCommandEncoder();e.copyBufferToBuffer(buffer,offset,b,0,size);d.queue.submit([e.finish()]);await b.mapAsync(GPUMapMode.READ);const a=b.getMappedRange().slice(0);b.unmap();b.destroy();return a;}
 window.__ceilingTest={async setup(rate,wall=false){__smear.reset();__smear.preset('default');await __smear.step(0);__smear.clean();g.clearDrops();g.bodyCount=0;g.syncCounts();g.action=0;__smear.tune({ceilingDrips:rate,drying:100});const e=d.createCommandEncoder();e.clearBuffer(g.workBuffer);e.clearBuffer(g.wetBuffer);d.queue.submit([e.finish()]);this.id=wall?16:g.surfaces.findIndex(s=>s.n.y<-.9&&s.center.y>4.9);const r=g.records[this.id],s=g.surfaces[this.id],a=new Uint32Array(r.filmWidth*r.filmHeight);for(let y=0;y<r.filmHeight;y++)for(let x=0;x<r.filmWidth;x++){const u=((x+.5)/r.filmWidth-.5)*s.w,v=((y+.5)/r.filmHeight-.5)*s.h,r2=(u*u+v*v)/(.45*.45);if(r2<1)a[x+y*r.filmWidth]=Math.round((1-r2)*1.4*65536);}d.queue.writeBuffer(g.wetBuffer,(g.surfaces.length*3136+r.filmOffset)*4,a);},
 async advance(ticks){for(let i=0;i<ticks;i+=2)g.submit(2);await d.queue.onSubmittedWorkDone();},
 async read(){const a=new Uint32Array(await read(g.wetBuffer,g.surfaces.length*3136*4,g.filmCells*3*4)),drops=new Float32Array(await read(g.particleBuffer,0,900*16*4)),w=new Uint32Array(await read(g.workBuffer,0,1024*4));let mobile=0,dry=0,retained=0,airborne=0;for(let id=0;id<g.surfaces.length;id++){const r=g.records[id],s=g.surfaces[id],area=s.w*s.h/(r.filmWidth*r.filmHeight);for(let k=0;k<r.filmWidth*r.filmHeight;k++){const m=a[r.filmOffset+k]/65536*area,z=a[g.filmCells*2+r.filmOffset+k]/65536*area;mobile+=m;dry+=z;if(id===this.id)retained+=m+z;}}for(let i=0;i<900;i++)if(w[64+i])airborne+=drops[i*16+12];return {mobile,dry,retained,airborne,total:mobile+dry+airborne,runoff:w[26],landed:w[28]};}};})()`);
 receipt.ceiling={};for(const rate of [0,.35,1]){await page.eval(`__ceilingTest.setup(${rate})`);const before=await page.eval('__ceilingTest.read()');await page.eval('__ceilingTest.advance(120)');const one=await page.eval('__ceilingTest.read()');await page.eval('__ceilingTest.advance(600)');const six=await page.eval('__ceilingTest.read()');receipt.ceiling[rate]={before,one,six};assert(Math.abs(six.total/before.total-1)<.03);}
 assert.equal(receipt.ceiling[0].six.runoff,0);assert(receipt.ceiling[1].one.runoff>50);assert(receipt.ceiling[.35].one.runoff<receipt.ceiling[1].one.runoff*.7);assert(receipt.ceiling[.35].six.retained>receipt.ceiling[1].six.retained*1.2);receipt.checks.push('Gentler overhead runoff emits fewer full-sized drops and retains more liquid; zero disables it, with finite total supply');
 receipt.walls={};for(const rate of [0,1]){await page.eval(`__ceilingTest.setup(${rate},true)`);await page.eval('__ceilingTest.advance(360)');receipt.walls[rate]=await page.eval('__ceilingTest.read()');}assert(Math.abs(receipt.walls[0].retained/receipt.walls[1].retained-1)<.001);assert.equal(receipt.walls[0].runoff,receipt.walls[1].runoff);receipt.checks.push('Ceiling tuning leaves wall drainage unchanged');
 receipt.errors=page.logs.filter(s=>/^EXCEPTION:|^error:/i.test(s));assert.deepEqual(receipt.errors,[]);receipt.result='COMPLETE carry and effects tuning checks';console.log(JSON.stringify({result:receipt.result,checks:receipt.checks,carry:Object.fromEntries(Object.entries(receipt.carry).map(([k,r])=>[k,{q95:r.after.q95,centroid:r.after.centroid,massRatio:r.after.sum/r.before.sum}])),baseline:{q95:receipt.baseline.after.q95,centroid:receipt.baseline.after.centroid},ceiling:receipt.ceiling},null,2));
}catch(e){receipt.result='FAIL';receipt.error=e.stack;console.error(e.stack);process.exitCode=1;}finally{receipt.logs=page.logs;await writeFile(resolve(out,'verification.json'),JSON.stringify(receipt,null,2)+'\n');page.kill();}
