// Native-time matched rendering comparison, plus the new bat in real gameplay.
import fs from 'node:fs';import {resolve} from 'node:path';import {pathToFileURL} from 'node:url';import {spawnSync} from 'node:child_process';import {createHash} from 'node:crypto';import assert from 'node:assert/strict';
import {launch,until,sleep} from './cdp.mjs';import {installHandlingFixture} from './handling-fixture.mjs';import {installBrushFlowFixture} from './brush-flow-fixture.mjs';
const root=resolve('tools/out/controller-pass/recordings');fs.mkdirSync(root,{recursive:true});const receipt={startedAt:new Date().toISOString(),viewport:[1440,1080],profiles:[],clips:[],comparison:'smear-v31-v32-ltc.mp4'};
function encode(args){const r=spawnSync('ffmpeg',['-nostdin','-hide_banner','-loglevel','error','-y',...args],{windowsHide:true,encoding:'utf8',timeout:120000});assert.ifError(r.error);assert.equal(r.status,0,r.stderr);}
function save(){fs.writeFileSync(resolve(root,'capture.json'),JSON.stringify(receipt,null,2));}
for(const label of ['before','after']){
 const out=resolve(root,label);fs.mkdirSync(out,{recursive:true});const source=label==='before'?'tools/out/controller-pass/before/index.html':'index.html';fs.copyFileSync(source,resolve(out,'build.html'));const page=await launch({port:9694,width:1440,height:1080});receipt.profiles.push({profile:page.dir,pid:page.proc.pid,label});save();
 try{
  await page.goto(pathToFileURL(resolve(out,'build.html')).href);await until(()=>page.eval('!!window.__smearComputeReady'),{timeout:90000});await page.eval('__smear.manual(true)');await page.mouse('mousePressed',720,130);await page.mouse('mouseReleased',720,130);await installHandlingFixture(page);await installBrushFlowFixture(page);
  for(const [name,duration,caption]of [['pool',8,'WET FLOOR / SAME LIQUID AND TWIST INPUT'],['wall',15,'WALL BRUSH / RELEASE AND DRAINAGE'],...(label==='after'?[['bat',8,'SPIKED BAT / PHYSICAL HITS AND GAME AUDIO']]:[])]){
   let fixture=null;
   if(name==='pool'){await page.eval('__handling.poolSetup()');await page.eval('__smear.view([2,1.3,5.7],[0,0,2.5])');}
   else if(name==='wall'){await page.eval("__smear.preset('default');__contactPlay.setup('drag')");await page.eval("__smear.grab(0,'Torso',[0,0,.125])");await page.eval('__contactPlay.advance(960)');await page.eval('__smear.release(false);__smear.view([-3.9,1.05,-5.2],[-3.5,2,-8])');fixture=await page.eval('__drainRead()');assert(fixture.mass>.02,'Wall recording must start with a real wet brush deposit');}
   else{await page.eval('__impactTest.setup({speed:0})');const h=(await page.eval('__smear.state()')).parts[2].p;await page.eval(`__smear.view([${h[0]},${h[1]},${h[2]+1.4}],${JSON.stringify(h)});__smear.tool(3);__smear.pointer(720,540)`);}
   await page.eval(`(()=>{window.__chunks=[];window.__video=__smearGPU.canvas.captureStream(30);window.__tap=__smear.compute.audioTap();window.__stream=new MediaStream([...__video.getVideoTracks(),...__tap.stream.getAudioTracks()]);window.__recorder=new MediaRecorder(__stream,{mimeType:'video/webm;codecs=vp9,opus',videoBitsPerSecond:14000000,audioBitsPerSecond:192000});__recorder.ondataavailable=e=>{if(e.data.size)__chunks.push(e.data)};__recorder.start(1000);__smear.render();__smear.manual(false);})()`);
   if(name==='pool'){await page.eval('__handling.twist(true)');await sleep(4000);await page.eval('__handling.twist(false);__smear.release(false)');await sleep(4000);}
   else if(name==='bat'){await page.mouse('mousePressed',720,540);await page.mouse('mouseReleased',720,540);await sleep(2000);await page.eval('__smear.view([-4.2,2.3,-3.2],[-3.5,1.7,-8])');await sleep(2000);await page.mouse('mousePressed',720,540);await page.mouse('mouseReleased',720,540);await sleep(4000);}
   else await sleep(duration*1000);
   await page.eval('__smear.manual(true)');const data=await page.eval(`new Promise(resolve=>{__recorder.onstop=()=>{const r=new FileReader();r.onload=()=>resolve(r.result.split(',')[1]);r.readAsDataURL(new Blob(__chunks,{type:'video/webm'}));__stream.getTracks().forEach(t=>t.stop());};__recorder.stop();})`);fs.writeFileSync(resolve(out,name+'.webm'),Buffer.from(data,'base64'));
   const state=await page.eval('__smear.state()');assert.deepEqual(state.errors,[]);receipt.clips.push({label,name,duration,fixture,sha256:createHash('sha256').update(fs.readFileSync(source)).digest('hex'),audio:await page.eval('__smear.compute.audio()'),steps:state.steps});
   encode(['-i',resolve(out,name+'.webm'),'-vf',`fps=30,tpad=stop_mode=clone:stop_duration=1,drawtext=font=Arial:text='${caption}':x=24:y=h-50:fontsize=23:fontcolor=white:box=1:boxcolor=black@0.65:boxborderw=8`,'-af','apad','-t',String(duration),'-c:v','libx264','-preset','fast','-crf','18','-pix_fmt','yuv420p','-c:a','aac','-b:a','192k','-movflags','+faststart',resolve(out,name+'.mp4')]);console.log('Recorded '+label+'/'+name);save();
  }
  fs.writeFileSync(resolve(out,'clips.txt'),"file 'pool.mp4'\nfile 'wall.mp4'\n");encode(['-f','concat','-safe','0','-i',resolve(out,'clips.txt'),'-c','copy','-movflags','+faststart',resolve(out,'lighting-'+label+'.mp4')]);assert.deepEqual(page.logs.filter(s=>/^EXCEPTION:|^error:/i.test(s)),[]);
 }finally{page.kill();save();}
}
encode(['-i',resolve(root,'before/lighting-before.mp4'),'-i',resolve(root,'after/lighting-after.mp4'),'-filter_complex',"[0:v]scale=960:720,drawbox=x=0:y=0:w=iw:h=52:color=black@0.75:t=fill,drawtext=font=Arial:text='BEFORE / V31':x=24:y=15:fontsize=24:fontcolor=white[a];[1:v]scale=960:720,drawbox=x=0:y=0:w=iw:h=52:color=black@0.75:t=fill,drawtext=font=Arial:text='ARC LTC LIGHTS / V32':x=24:y=15:fontsize=24:fontcolor=white[b];[a][b]hstack=inputs=2[v];[0:a]pan=mono|c0=0.5*c0+0.5*c1[left];[1:a]pan=mono|c0=0.5*c0+0.5*c1[right];[left][right]amerge=inputs=2[audio]",'-map','[v]','-map','[audio]','-c:v','libx264','-preset','fast','-crf','18','-pix_fmt','yuv420p','-c:a','aac','-b:a','192k','-movflags','+faststart',resolve(root,receipt.comparison)]);
for(const [name,time]of [['pool',2],['wall',10]])encode(['-ss',String(time),'-i',resolve(root,receipt.comparison),'-frames:v','1',resolve(root,name+'-review.png')]);encode(['-ss','0.22','-i',resolve(root,'after/bat.mp4'),'-frames:v','1',resolve(root,'bat-review.png')]);receipt.result='COMPLETE V31/V32 native lighting comparison and spiked bat showcase';save();console.log(receipt.result);
