import fs from 'node:fs';import assert from 'node:assert/strict';import {resolve} from 'node:path';import {pathToFileURL} from 'node:url';import {createHash} from 'node:crypto';
import {launchComputeBrowser} from './compute-browser.mjs';import {until,sleep} from './cdp.mjs';import {installImpactFixture} from './impact-fixture.mjs';
const browser=process.argv.includes('firefox')?'firefox':'chrome',label=process.argv.find(v=>/^(round-|final)/.test(v))||'round-01',out=resolve('tools/out/controller-pass',label+'-'+browser);fs.mkdirSync(out,{recursive:true});
const page=await launchComputeBrowser({port:9695,width:1440,height:1080}),r={startedAt:new Date().toISOString(),browserProfile:page.dir,buildSHA256:createHash('sha256').update(fs.readFileSync('index.html')).digest('hex'),checks:[]};
async function key(code,down=true){if(browser==='chrome')await page.call('Input.dispatchKeyEvent',{type:down?'keyDown':'keyUp',code,key:{Escape:'Escape',Tab:'Tab',Space:' '}[code]||code.replace(/^Key|^Digit/,''),windowsVirtualKeyCode:{Escape:27,Tab:9,Space:32}[code]||code.at(-1).charCodeAt(0)});else await page.call('input.performActions',{context:page.context,actions:[{type:'key',id:'keyboard',actions:[{type:down?'keyDown':'keyUp',value:{Escape:'\uE00C',Tab:'\uE004',Space:' '}[code]||code.replace(/^Key|^Digit/,'').toLowerCase()}]}]});}
async function tap(code){await key(code);await key(code,false);}
async function state(){return page.eval('__smear.controls.state()');}
async function play(){await sleep(180);const b=await page.eval('(()=>{const r=document.getElementById("play-resume").getBoundingClientRect();return {x:r.x+r.width/2,y:r.y+r.height/2};})()');await page.mouse('mousePressed',b.x,b.y);await page.mouse('mouseReleased',b.x,b.y);await until(async()=>{const s=await state();return s.locked&&!s.paused;},{timeout:5000,label:'FPS mouse capture'});}
async function move(dx,dy){if(browser==='chrome')await page.call('Input.dispatchMouseEvent',{type:'mouseMoved',x:720+dx,y:540+dy,buttons:0});else await page.call('input.performActions',{context:page.context,actions:[{type:'pointer',id:'mouse',parameters:{pointerType:'mouse'},actions:[{type:'pointerMove',origin:'pointer',x:dx,y:dy,duration:0}]}]});}
try{
 await page.goto(pathToFileURL(resolve('index.html')).href);await until(async()=>{const v=await page.eval('({ready:!!window.__smearComputeReady,error:document.getElementById("failure")?.style.display==="block"?document.getElementById("failure").textContent:null})');if(v.error)throw Error(v.error);return v.ready;},{timeout:90000});r.initial=await state();assert(r.initial.paused&&!r.initial.locked&&r.initial.mode==='fps');const before=await page.eval('__smearGPU.steps');await sleep(300);assert.equal(await page.eval('__smearGPU.steps'),before);await page.shot(resolve(out,'enter.png'));r.checks.push('Fresh load offers click-to-play and freezes simulation before mouse capture');
 await play();await page.eval('window.__menuMutations=0;window.__menuObserver=new MutationObserver(m=>__menuMutations+=m.length);__menuObserver.observe(document.getElementById("play-menu"),{attributes:true,childList:true,subtree:true,characterData:true})');const look=await state();await move(90,35);const moved=await state();assert(Math.abs(moved.yaw-look.yaw)>.01);await sleep(100);assert((await state()).locked);assert.equal(await page.eval('__menuMutations'),0);await page.eval('__menuObserver.disconnect()');r.checks.push('A real click captures the mouse without a gameplay action; looking persists without holding right-click');
 await tap('Digit2');await page.mouse('mousePressed',720,540,'right');await sleep(300);assert((await state()).aimDown);assert(await page.eval('__smearGPU.camera.fov<65'));await page.mouse('mouseReleased',720,540,'right');assert(!(await state()).aimDown);assert((await state()).locked);r.checks.push('Right-click aims the pistol and releasing it keeps FPS mouse lock');
 await key('KeyC');const c0=await state();await move(150,-60);const c1=await state();assert(c1.freeAim);assert.equal(c1.yaw,c0.yaw);assert.equal(c1.pitch,c0.pitch);assert(Math.hypot(c1.aim.x-720,c1.aim.y-540)>20);assert(c1.eye>1.5);await page.shot(resolve(out,'free-aim.png'));await key('KeyC',false);const c2=await state();assert(!c2.freeAim&&c2.locked);assert.deepEqual(c2.aim,{x:720,y:540});r.checks.push('Holding C moves the aim point without rotating or crouching; releasing C returns to FPS aim without unlocking');
 await key('KeyW');await sleep(180);await tap('Escape');await until(async()=>!(await state()).locked,{timeout:3000});const stopped=await state();assert(stopped.paused&&!stopped.left&&stopped.keys.length===0);assert.deepEqual(stopped.velocity,[0,0,0]);const p=await page.eval('__smearGPU.camera.position.toArray()'),ticks=await page.eval('__smearGPU.steps');await sleep(220);assert.deepEqual(await page.eval('__smearGPU.camera.position.toArray()'),p);assert.equal(await page.eval('__smearGPU.steps'),ticks);const shots=stopped.shots;await play();assert.equal((await state()).shots,shots);r.checks.push('Escape freezes movement and simulation, clears held inputs, and the resume click cannot fire the pistol');
 await tap('Tab');await until(async()=>!(await state()).locked,{timeout:3000});assert(!(await state()).paused);const controls=await page.eval('__smear.ui().find(b=>b.label==="Controls")');await page.mouse('mousePressed',controls.x+20,controls.y+15);await page.mouse('mouseReleased',controls.x+20,controls.y+15);assert((await state()).paused);await until(()=>page.eval('__smear.ui().some(b=>b.label==="Close")'));const close=await page.eval('__smear.ui().find(b=>b.label==="Close")');await page.mouse('mousePressed',close.x+20,close.y+15);await page.mouse('mouseReleased',close.x+20,close.y+15);assert(!(await state()).paused);await tap('Tab');await until(async()=>(await state()).locked);await page.eval('window.dispatchEvent(new Event("blur"))');await until(async()=>!(await state()).locked,{timeout:3000});assert((await state()).paused);r.checks.push('Tab frees the mouse, Controls pauses, closing returns to cursor, Tab recaptures; focus loss pauses');
 await play();await tap('Digit4');await sleep(80);assert(await page.eval('__smearGPU.bat.visible&&!__smearGPU.gun.visible&&!__smearGPU.spillCan.visible'));await page.shot(resolve(out,'bat-idle.png'));const n=(await state()).batSwings;
 await page.mouse('mousePressed',720,540);await page.mouse('mouseReleased',720,540);await sleep(100);await page.shot(resolve(out,'bat-swing.png'));for(let i=0;i<4;i++){await page.mouse('mousePressed',720,540);await page.mouse('mouseReleased',720,540);}assert.equal((await state()).batSwings,n+1);await sleep(620);
 const attacks=await page.eval('__smearGPU.readWork().then(()=>__smearGPU.steps)');await page.mouse('mousePressed',720,540);await page.mouse('mouseReleased',720,540);await tap('Digit1');await sleep(220);assert((await state()).batAge>=10);r.checks.push('Weapon 4 shows the spiked bat and animates a swing; click spam cannot bypass recovery and weapon switching cancels windup');
 await page.eval('__smear.manual(true);__smear.controls.mode("cursor")');await installImpactFixture(page);
 await page.eval(`(()=>{const g=__smearGPU,d=g.device;window.__meleeRead=async()=>{const b=g.buffer('explicit melee test',256,GPUBufferUsage.COPY_DST|GPUBufferUsage.MAP_READ),e=d.createCommandEncoder();e.copyBufferToBuffer(g.workBuffer,0,b,0,b.size);d.queue.submit([e.finish()]);await b.mapAsync(GPUMapMode.READ);const w=new Uint32Array(b.getMappedRange().slice(0));b.unmap();b.destroy();return Array.from(w.slice(54,58));};})()`);
 r.melee=[];for(const scenario of ['near','far','wall','empty','full']){
  await page.eval(`__impactTest.setup({speed:0,reserve:${scenario==='empty'?0:9},full:${scenario==='full'}})`);const initial=await page.eval('__smear.state()');const head=initial.parts[2].p;const origin=scenario==='wall'?[-3.5,2,-9]:[head[0],head[1],head[2]+(scenario==='far'?5.2:1.4)];
  await page.eval(`__smear.view(${JSON.stringify(origin)},${JSON.stringify(head)});__smear.pointer(720,540);__smearGPU.melee();__smearGPU.submit(0);__smearGPU.device.queue.onSubmittedWorkDone()`);const after=await page.eval('__smear.state()'),counters=await page.eval('__meleeRead()');r.melee.push({scenario,counters,before:initial.parts.map(p=>({v:p.v,reserve:p.reserve,damage:p.damage,wet:p.wet})),after:after.parts.map(p=>({v:p.v,reserve:p.reserve,damage:p.damage,wet:p.wet})),particles:after.particles});
  assert.equal(counters[0],1);assert.equal(counters[1],['near','empty','full'].includes(scenario)?1:0);if(scenario==='wall')assert.equal(counters[3],1);
  if(['near','empty','full'].includes(scenario)){assert(after.parts.some(p=>p.damage>0));assert(after.parts.slice(0,15).every(p=>Math.hypot(...p.v)>4));}else assert(after.parts.every(p=>p.damage===0));
  if(scenario==='near')assert(after.particles>0);if(scenario==='empty')assert.equal(after.particles,0);if(scenario==='full')assert.equal(after.particles,900);
 }
 r.checks.push('GPU melee arc hits in reach, knocks the whole rig, wounds the contact part and emits carried blood; distance and walls block it, empty supplies stay dry, and a full 900-drop pool stays bounded');
 // Real locked input, including carrying a picked body across the free-aim transition.
 await page.eval('__smear.manual(true);__smear.reset();__smear.tune({walking:false,recover:false});__smear.step(45)');
 const torso=(await page.eval('__smear.state()')).parts[0].p;await page.eval(`__smear.view([${torso[0]},${torso[1]+.9},${torso[2]+2}],${JSON.stringify(torso)});__smear.controls.mode('fps')`);await play();
 await page.mouse('mousePressed',720,540);await page.eval('__smear.render()');await until(()=>page.eval('__smearGPU.input().held'),{timeout:5000});await key('KeyC');await move(70,20);const aimBefore=await state(),targetBefore=await page.eval('__smearGPU.input().target');await key('KeyC',false);const aimAfter=await state(),targetAfter=await page.eval('__smearGPU.input().target');assert(Math.hypot(aimAfter.aim.x-aimBefore.aim.x,aimAfter.aim.y-aimBefore.aim.y)<1e-6);assert(Math.hypot(...targetAfter.map((v,i)=>v-targetBefore[i]))<1e-6);await page.mouse('mouseReleased',720,540);assert.equal(await page.eval('__smearGPU.input().held'),false);r.checks.push('A real GPU-picked body keeps its aim ray and target when C is released, then releases normally on mouseup');
 await tap('Escape');await until(async()=>!(await state()).locked);await page.eval('__smear.controls.mode("cursor");window.dispatchEvent(new Event("blur"))');assert((await state()).paused);assert.equal(await page.eval('getComputedStyle(document.getElementById("play-menu")).display'),'flex');
 const resume=await page.eval('(()=>{const b=document.getElementById("play-resume").getBoundingClientRect();return{x:b.x+b.width/2,y:b.y+b.height/2};})()');await page.mouse('mousePressed',resume.x,resume.y);await page.mouse('mouseReleased',resume.x,resume.y);assert(!(await state()).paused);assert(!(await state()).locked);r.checks.push('Free-cursor mode also pauses safely on focus loss and resumes without forcing mouse lock');
 await page.eval('__smear.controls.mode("fps");document.dispatchEvent(new Event("pointerlockerror"))');assert((await state()).paused);assert((await state()).error.includes('blocked'));await play();assert.equal((await state()).error,'');r.checks.push('Denied mouse capture shows a retry and cursor fallback, and a fresh user gesture recovers');
 await tap('Escape');await until(async()=>!(await state()).locked);await page.eval('__impactTest.setup({speed:0})');const nearHead=(await page.eval('__smear.state()')).parts[2].p;await page.eval(`__smear.view([${nearHead[0]},${nearHead[1]},${nearHead[2]+1.4}],${JSON.stringify(nearHead)});__smear.controls.mode('fps')`);await play();await tap('Digit4');
 await page.eval(`(()=>{const g=__smearGPU,impact=g.impact;window.__batEvents=[];g.impact=e=>{__batEvents.push(e);impact(e);};const tap=__smear.compute.audioTap(),source=tap.context.createMediaStreamSource(tap.stream),meter=tap.context.createAnalyser();meter.fftSize=2048;source.connect(meter);window.__batPeaks=[];window.__batMeter=setInterval(()=>{const a=new Float32Array(2048);meter.getFloatTimeDomainData(a);__batPeaks.push(Math.max(...a.map(Math.abs)));},8);__smear.manual(false);})()`);
 await page.mouse('mousePressed',720,540);await page.mouse('mouseReleased',720,540);await sleep(450);await page.eval('__smear.manual(true);clearInterval(__batMeter)');r.nativeBat=await page.eval('({events:__batEvents,peak:Math.max(...__batPeaks),audio:__smear.compute.audio()})');assert(r.nativeBat.events.some(e=>e.melee&&e.body<255));assert(r.nativeBat.peak>.001);r.checks.push('A real mouse swing connects during native simulation and produces a measured whoosh and GPU-confirmed impact thud');
 r.errors=page.logs.filter(s=>/^EXCEPTION:|^error:/i.test(s));assert.deepEqual(r.errors,[]);r.result='COMPLETE FPS controller and spiked bat checks';console.log(JSON.stringify({result:r.result,checks:r.checks},null,2));
}catch(e){r.result='FAIL';r.error=e.stack;console.error(e.stack);process.exitCode=1;}finally{r.logs=page.logs;fs.writeFileSync(resolve(out,'verification.json'),JSON.stringify(r,null,2));page.kill();}
