import fs from 'node:fs';import assert from 'node:assert/strict';import {resolve} from 'node:path';import {pathToFileURL} from 'node:url';import {spawnSync} from 'node:child_process';import {createHash} from 'node:crypto';
import {launch,until,sleep} from './cdp.mjs';import {installHandlingFixture} from './handling-fixture.mjs';import {installDestructionFixture} from './destruction-fixture.mjs';
const root=resolve('tools/out/destruction-pass/recordings');fs.mkdirSync(root,{recursive:true});const receipt={profiles:[],clips:[],startedAt:new Date().toISOString()};
function encode(args){const p=spawnSync('ffmpeg',['-nostdin','-hide_banner','-loglevel','error','-y',...args],{encoding:'utf8',windowsHide:true,timeout:120000});assert.ifError(p.error);assert.equal(p.status,0,p.stderr);}
function save(){fs.writeFileSync(resolve(root,'capture.json'),JSON.stringify(receipt,null,2));}
for(const label of ['before','after']){
 const source=label==='before'?'tools/out/destruction-pass/before/index.html':'index.html',out=resolve(root,label);fs.mkdirSync(out,{recursive:true});fs.copyFileSync(source,resolve(out,'build.html'));const page=await launch({port:9729,width:1440,height:1080});receipt.profiles.push({profile:page.dir,pid:page.proc.pid,label});save();
 try{
  await page.goto(pathToFileURL(resolve(out,'build.html')).href+'?defaults=1');await until(()=>page.eval('!!window.__smearComputeReady'),{timeout:90000});await page.eval('__smear.manual(true)');await page.mouse('mousePressed',720,130);await page.mouse('mouseReleased',720,130);await installHandlingFixture(page);await installDestructionFixture(page);
  for(const [name,duration,caption]of [['ceiling',12,'CEILING / SAME FINITE DEPOSIT / DEFAULT DRIP SETTING'],['dummy',7,'THREE HEAD HITS / RELEASE / FINITE BLEEDING'],...(label==='after'?[['grenade',8,'GRENADE / THROW - BOUNCE - FUSE - BLAST'],['pool',7,'BLAST PRESSURE / EXISTING POOL PUSHED INTO SPRAY']]:[])]){
   if(name==='ceiling')await page.eval('__destructionFixture.ceiling(1)');
   if(name==='dummy'){await page.eval('__impactTest.setup({speed:0})');const h=(await page.eval('__smear.state()')).parts[2].p;await page.eval(`(async()=>{__smear.view([${h[0]+1.2},${h[1]},${h[2]}],${JSON.stringify(h)});__smear.pointer(720,540);for(let i=0;i<3;i++){__smearGPU.shoot();__smearGPU.submit(0);await __smearGPU.device.queue.onSubmittedWorkDone();}__smear.view([-1.7,2.8,-4.5],[-3.5,1.9,-7]);__smear.tool(0);})()`);}
   if(name==='grenade'){await page.eval("__impactTest.setup({speed:0,pose:'body'})");await page.eval('__smear.view([-3.5,2.8,-3.6],[-3.5,-2,-7.1]);__smear.pointer(720,540);__smear.tool(4)');}
   if(name==='pool'){await page.eval('__handling.poolSetup()');await page.eval('__smear.release(false);__smearGPU.bodyCount=0;__smearGPU.syncCounts();__smear.view([2,3.7,5.5],[0,0,2.5])');}
   await page.eval(`(()=>{window.__chunks=[];window.__video=__smearGPU.canvas.captureStream(30);window.__tap=__smear.compute.audioTap();window.__stream=new MediaStream([...__video.getVideoTracks(),...__tap.stream.getAudioTracks()]);window.__recorder=new MediaRecorder(__stream,{mimeType:'video/webm;codecs=vp9,opus',videoBitsPerSecond:14000000,audioBitsPerSecond:192000});__recorder.ondataavailable=e=>{if(e.data.size)__chunks.push(e.data)};__recorder.start(1000);__smear.render();__smear.manual(false);})()`);
   if(name==='grenade'){await sleep(500);await page.mouse('mousePressed',720,540);await page.mouse('mouseReleased',720,540);await sleep(500);await page.eval('__smear.view([-1.4,2.4,-3.3],[-3.5,.9,-7.1])');await sleep(7000);}
   else if(name==='pool'){await sleep(650);await page.eval('__smear.blast([0,.35,2.5])');await sleep(6350);}
   else await sleep(duration*1000);
   await page.eval('__smear.manual(true)');const data=await page.eval(`new Promise(resolve=>{__recorder.onstop=()=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result.split(',')[1]);reader.readAsDataURL(new Blob(__chunks,{type:'video/webm'}));__stream.getTracks().forEach(t=>t.stop());};__recorder.stop();})`);fs.writeFileSync(resolve(out,name+'.webm'),Buffer.from(data,'base64'));
   const state=await page.eval('__smear.state()');assert.deepEqual(state.errors,[]);receipt.clips.push({label,name,duration,buildSHA256:createHash('sha256').update(fs.readFileSync(source)).digest('hex'),parts:state.parts.map(p=>({name:p.name,severed:p.severed,reserve:p.reserve})),audio:await page.eval('__smear.compute.audio()')});await page.shot(resolve(out,name+'-end.png'));
   encode(['-i',resolve(out,name+'.webm'),'-vf',`fps=30,tpad=stop_mode=clone:stop_duration=1,drawtext=font=Arial:text='${caption}':x=24:y=h-50:fontsize=23:fontcolor=white:box=1:boxcolor=black@0.65:boxborderw=8`,'-af','apad','-t',String(duration),'-c:v','libx264','-preset','fast','-crf','18','-pix_fmt','yuv420p','-c:a','aac','-b:a','192k','-movflags','+faststart',resolve(out,name+'.mp4')]);console.log('Recorded '+label+'/'+name);save();
  }
  assert.deepEqual(page.logs.filter(s=>/^error:|^EXCEPTION:/i.test(s)),[]);
 }finally{await page.kill();save();}
}
for(const name of ['ceiling','dummy']){
 encode(['-i',resolve(root,'before',name+'.mp4'),'-i',resolve(root,'after',name+'.mp4'),'-filter_complex',"[0:v]scale=960:720,drawbox=x=0:y=0:w=iw:h=52:color=black@0.75:t=fill,drawtext=font=Arial:text='BEFORE / V32':x=24:y=15:fontsize=24:fontcolor=white[a];[1:v]scale=960:720,drawbox=x=0:y=0:w=iw:h=52:color=black@0.75:t=fill,drawtext=font=Arial:text='AFTER / V33':x=24:y=15:fontsize=24:fontcolor=white[b];[a][b]hstack=inputs=2[v];[0:a]pan=mono|c0=0.5*c0+0.5*c1[left];[1:a]pan=mono|c0=0.5*c0+0.5*c1[right];[left][right]amerge=inputs=2[audio]",'-map','[v]','-map','[audio]','-c:v','libx264','-preset','fast','-crf','18','-pix_fmt','yuv420p','-c:a','aac','-b:a','192k','-movflags','+faststart',resolve(root,'smear-v32-v33-'+name+'.mp4')]);
 encode(['-ss',name==='ceiling'?'2.5':'0.6','-i',resolve(root,'smear-v32-v33-'+name+'.mp4'),'-frames:v','1',resolve(root,name+'-comparison.png')]);
}
fs.writeFileSync(resolve(root,'after','clips.txt'),"file 'grenade.mp4'\nfile 'pool.mp4'\nfile 'dummy.mp4'\nfile 'ceiling.mp4'\n");encode(['-f','concat','-safe','0','-i',resolve(root,'after','clips.txt'),'-c','copy','-movflags','+faststart',resolve(root,'smear-v33-destruction.mp4')]);encode(['-ss','2.2','-i',resolve(root,'after/grenade.mp4'),'-frames:v','1',resolve(root,'grenade-review.png')]);receipt.passed=true;save();console.log('COMPLETE V33 destruction videos and V32/V33 comparisons');
