import fs from 'node:fs';import assert from 'node:assert/strict';import {resolve} from 'node:path';import {pathToFileURL} from 'node:url';import {createHash} from 'node:crypto';
import {launchComputeBrowser} from './compute-browser.mjs';import {until} from './cdp.mjs';import {installHandlingFixture} from './handling-fixture.mjs';
const browser=process.argv.includes('firefox')?'firefox':'chrome',label=process.argv.find(a=>/^(round-|final)/.test(a))||'round-01',out=resolve('tools/out/destruction-pass',label+'-'+browser);fs.mkdirSync(out,{recursive:true});
const page=await launchComputeBrowser({port:9727,width:1600,height:1000}),r={browser,browserProfile:page.dir,startedAt:new Date().toISOString(),buildSHA256:createHash('sha256').update(fs.readFileSync('index.html')).digest('hex'),checks:[]};
const url=pathToFileURL(resolve('index.html')).href;
async function boot(query='?defaults=1'){await page.goto(url+query);await until(async()=>{const s=await page.eval('({ready:!!window.__smearComputeReady,error:document.getElementById("failure")?.style.display==="block"?document.getElementById("failure").textContent:null})');if(s.error)throw Error(s.error);return s.ready;},{timeout:90000});}
const check=(name,result)=>{r.checks.push(name);console.log('PASS '+name);if(result)r[name]=result;};
try{
 await boot();r.defaults=await page.eval('({...__smearGPU.input().tune})');await page.eval(`localStorage.setItem('smear.tune.v8',JSON.stringify({bleeding:2.5,smudge:4,fragility:2}));localStorage.setItem('smear.controls.mode','cursor');`);await boot();assert.deepEqual(await page.eval('({...__smearGPU.input().tune})'),r.defaults);assert.equal(await page.eval('__smear.controls.state().mode'),'fps');await page.eval('__smear.tune({bleeding:2})');assert.equal(await page.eval('JSON.parse(localStorage.getItem("smear.tune.v8")).bleeding'),2.5);await boot('');assert.equal(await page.eval('__smearGPU.input().tune.bleeding'),2.5);assert.equal(await page.eval('__smear.controls.state().mode'),'cursor');check('Reference URL ignores saved tuning and controls without overwriting the saved session');await boot();await page.eval('__smear.manual(true)');await installHandlingFixture(page);
 await page.eval(`(()=>{const g=__smearGPU,d=g.device;window.__destruct={
 async read(buffer,offset,size){const b=g.buffer('explicit destruction verification',size,GPUBufferUsage.COPY_DST|GPUBufferUsage.MAP_READ),e=d.createCommandEncoder();e.copyBufferToBuffer(buffer,offset,b,0,size);d.queue.submit([e.finish()]);await b.mapAsync(GPUMapMode.READ);const a=b.getMappedRange().slice(0);b.unmap();b.destroy();return a;},
 async counters(){return Array.from(new Uint32Array(await this.read(g.workBuffer,0,256)));},
 async snapshot(){const a=new Uint32Array(await this.read(g.workBuffer,g.destructionBase*4,(g.destructionMeta+32-g.destructionBase)*4));return {cuts:Array.from(a.slice(0,1440)).filter((v,i)=>i%8===0&&v).length,fragments:Array.from({length:128},(_,i)=>a[1440+i*24+23]).filter(v=>v===2).length,grenades:Array.from({length:8},(_,i)=>a[1440+i*24+23]).filter(v=>v===1).length};},
 async pose(){return new Float32Array(await this.read(g.bodyBuffer,0,g.bodyBuffer.size));}
 };})()`);
 await page.eval('__impactTest.setup({speed:0})');r.headBefore=await page.eval('__smear.state()');const head=r.headBefore.parts[2].p;
 await page.eval(`(async()=>{__smear.view([${head[0]+1.2},${head[1]},${head[2]}],${JSON.stringify(head)});__smear.pointer(800,500);for(let i=0;i<3;i++){__smearGPU.shoot();__smearGPU.submit(0);await __smearGPU.device.queue.onSubmittedWorkDone();}})()`);r.cut=await page.eval('__smear.state()');assert(r.cut.parts[2].severed);assert.equal(r.cut.parts.filter(p=>p.severed).length,1);assert.equal(r.cut.parts[0].socketMask,4);assert(r.cut.parts[2].reserve<9);await page.eval('__impactTest.advance(100)');r.detached=await page.eval('__smear.state()');assert(Math.hypot(...r.detached.parts[2].p.map((v,k)=>v-r.detached.parts[0].p[k]))>.5);assert(r.detached.maxJoint<.16);await page.shot(resolve(out,'severed-head.png'));check('Repeated pistol hits sever the struck joint; remaining joints hold and both sockets bleed from finite reserves');
 // A grabbed detached part must not transfer fling assistance to the former rig.
 await page.eval(`(async()=>{const g=__smearGPU;__smear.stopBleeding();await __smear.step(0);const a=await __destruct.pose();for(let i=0;i<15;i++){a.set([i*.38-2,3,3],i*104);a.fill(0,i*104+8,i*104+16);}g.device.queue.writeBuffer(g.bodyBuffer,0,a);await __smear.grab(0,'Head');window.__headTarget=[...a.slice(208,211)];for(let i=0;i<8;i++){__headTarget[0]+=.12;__smear.target(__headTarget);await __impactTest.advance(2);}})()`);const pre=await page.eval('__smear.state()');await page.eval('__smear.release(true)');const post=await page.eval('__smear.state()');assert(pre.parts.every((p,i)=>i===2||p.v.every((v,k)=>Math.abs(v-post.parts[i].v[k])<1e-5)));check('Releasing a severed head does not boost the old torso or limbs');
 await page.eval(`(async()=>{__smear.heal();await __smear.step(0);})()`);assert((await page.eval('__smear.state()')).parts[2].severed);assert.equal((await page.eval('__smear.state()')).parts[2].bleeding,0);check('Heal closes wounds without silently reconnecting severed joints; Reset restores the full rig');
 await page.eval('__impactTest.setup({speed:0})');await page.eval(`(async()=>{const s=await __smear.state();__smear.blast(s.parts[0].p.map((x,k)=>x+(k===2?.3:0)));__smearGPU.submit(0);await __smearGPU.device.queue.onSubmittedWorkDone();})()`);r.blast=await page.eval('__smear.state()');r.blastCounts=await page.eval('__destruct.snapshot()');assert(r.blastCounts.cuts>3);assert.equal(r.blastCounts.fragments,42);assert(r.blast.particles>30&&r.blast.particles<=900);assert(r.blast.parts.reduce((n,p)=>n+p.reserve,0)<135);await page.eval('__impactTest.advance(80)');await page.shot(resolve(out,'blast-dismemberment.png'));check('An actual blast breaks multiple joints, launches fragments and pays its airborne blood from the bodies');
 r.pools=[];for(const scenario of ['wet','dry','full','occluded']){
  await page.eval(`__handling.poolSetup({wet:${scenario!=='dry'}})`);await page.eval('__smear.release(false);__smearGPU.bodyCount=0;__smearGPU.syncCounts();');
  if(scenario==='full')await page.eval(`(()=>{const g=__smearGPU,a=new Float32Array(900*16);for(let i=0;i<900;i++){a.set([6,3,6,.007],i*16);a[i*16+11]=999;}g.device.queue.writeBuffer(g.particleBuffer,0,a);g.device.queue.writeBuffer(g.workBuffer,256,new Uint32Array(900).fill(1));g.device.queue.writeBuffer(g.workBuffer,36,new Uint32Array([900]));})()`);
  const before=await page.eval('__handling.poolRead()');await page.eval(`__smear.blast(${scenario==='occluded'?'[0,-.35,2.5]':'[0,.35,2.5]'});__smearGPU.submit(0);__impactTest.advance(24)`);const after=await page.eval('__handling.poolRead()');delete before.field;delete after.field;r.pools.push({scenario,before,after});assert(Math.abs(after.total-before.total)<.008);if(scenario==='wet'||scenario==='full')assert(after.outer>before.outer*1.3);if(scenario==='wet')assert(after.airborne>0);if(scenario==='dry'||scenario==='occluded')assert(after.airborne===0);if(scenario==='full')assert.equal(after.airborne,0);if(scenario==='wet')await page.shot(resolve(out,'blast-pool.png'));
  if(scenario==='wet'){const beforePause=await page.eval('__smear.compute.paintHash(10)');await page.eval('(async()=>{for(let i=0;i<8;i++)__smearGPU.submit(0);await __smearGPU.device.queue.onSubmittedWorkDone();})()');assert.deepEqual(await page.eval('__smear.compute.paintHash(10)'),beforePause);}
 }check('Blast pressure redistributes finite wet pools; dry surfaces, occluded pools and a saturated drop pool do not invent liquid; paused renders do not move paint');
 await page.eval(`(async()=>{await __impactTest.setup({speed:0,reserve:0});__smearGPU.bodyCount=0;__smearGPU.syncCounts();__smear.view([-3.5,2,-6],[-3.5,2,-8]);__smear.pointer(800,500);__smearGPU.shoot();__smearGPU.submit(0);await __impactTest.advance(120);})()`);r.bullet=await page.eval(`(async()=>{const g=__smearGPU,rec=g.records[16],p=new Uint32Array(await __destruct.read(g.paintBuffer,rec.pixelOffset*4,rec.width*rec.height*4)),f=new Uint32Array(await __destruct.read(g.wetBuffer,(g.surfaces.length*3136+rec.filmOffset)*4,rec.filmWidth*rec.filmHeight*4));return {painted:p.filter(v=>v>>>24).length,black:p.filter(v=>(v>>>24)>30&&(v&255)<90).length,liquid:f.reduce((n,v)=>n+v,0),counters:await __destruct.counters()};})()`);assert(r.bullet.black>20);assert.equal(r.bullet.liquid,0);assert(r.bullet.counters[60]>0);await page.shot(resolve(out,'bullet-and-scuffs.png'));check('Pistol misses leave dark bullet pits and colliding fragments leave dry scuffs');
 await page.eval('(async()=>{await __impactTest.setup({speed:0,reserve:0});__smearGPU.bodyCount=0;__smearGPU.syncCounts();__smear.view([0,2,5],[0,1,0]);__smear.pointer(800,500);__smear.tool(4);__smearGPU.updateToolPresentation(0,{tool:4,panel:null,time:0,left:false});__smear.grenade();__smearGPU.submit(0);await __smearGPU.device.queue.onSubmittedWorkDone();})()');assert.equal((await page.eval('__destruct.snapshot()')).grenades,1);await page.shot(resolve(out,'grenade-in-flight.png'));await page.eval('__impactTest.advance(200)');assert.equal((await page.eval('__destruct.snapshot()')).grenades,0);assert.equal((await page.eval('__destruct.counters()'))[58],1);check('Weapon 5 throws a visible grenade that bounces, burns down its fuse and detonates once');
 r.final=await page.eval('__smear.state()');assert.deepEqual(r.final.errors,[]);assert.equal(r.final.normalPaintReadbacks,0);r.logs=page.logs;assert(!page.logs.some(v=>/^error:/.test(v)));r.passed=true;console.log('COMPLETE '+r.checks.length+' checks passed');
}catch(e){r.error=e.stack;console.error(e);process.exitCode=1;}finally{fs.writeFileSync(resolve(out,'receipt.json'),JSON.stringify(r,null,2));await page.kill();}
