import assert from 'node:assert/strict';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {resolve} from 'node:path';
import {pathToFileURL} from 'node:url';
import {inflateSync} from 'node:zlib';
import {launch,until} from './cdp.mjs';
import {launchFirefox} from './bidi.mjs';
const firefox=process.argv[2]==='firefox',out=resolve('tools/out','details-'+(firefox?'firefox':'chrome'));await mkdir(out,{recursive:true});
const fixture=`const detailsQA={setup:async which=>{manual=true;preset('default');applyTuning({walking:false,recover:false});resetWorld();if(which==='chaos')chaosScene();if(which==='twelve')while(dolls.length<12)addDummy();if(which==='drag'){startDemo();for(let i=0;i<480;i++){physicsStep();if(i%8===7){renderNow();await __smear.paintReady(false);}}}renderNow();await __smear.paintReady(false);},pixels:async()=>{renderNow();const gl=renderer.getContext(),a=new Uint8Array(canvas.width*canvas.height*4);gl.readPixels(0,0,canvas.width,canvas.height,gl.RGBA,gl.UNSIGNED_BYTE,a);const bytes=new Uint8Array(await new Response(new Blob([a]).stream().pipeThrough(new CompressionStream('deflate'))).arrayBuffer());let str='';for(let i=0;i<bytes.length;i+=8192)str+=String.fromCharCode(...bytes.subarray(i,i+8192));let transforms=true,flags=true;for(const {mesh,parts}of detailGroups.values())for(let i=0;i<parts.length;i++){const p=parts[i];for(let j=0;j<16;j++)if(mesh.instanceMatrix.array[i*16+j]!==Math.fround(p.matrixWorld.elements[j]))transforms=false;if(mesh.material!==p.material||mesh.castShadow!==p.castShadow||mesh.receiveShadow!==p.receiveShadow)flags=false;}return{data:btoa(str),calls:renderer.info.render.calls,triangles:renderer.info.render.triangles,transforms,flags,groups:detailGroups.size,instances:[...detailGroups.values()].reduce((n,g)=>n+g.parts.length,0)};}};`;
const file=resolve(out,'runtime.html');await writeFile(file,(await readFile('index.html','utf8')).replace('</head>','<script>window.requestAnimationFrame=()=>0;</script></head>').replace('window.__smear={state,',fixture+'\nwindow.__smear={detailsQA,state,'));
const page=firefox?await launchFirefox({width:1920,height:1080}):await launch({port:9598,width:1920,height:1080}),receipt={checks:[]};
try{
 for(const which of ['room','drag','chaos','twelve']){const runs=[];for(const meshes of [true,false]){await page.goto(pathToFileURL(file).href+(meshes?'?detailMeshes=1':''));await until(()=>page.eval('!!window.__smear'),{label:'details audit boot'});await page.eval(`__smear.detailsQA.setup('${which}')`);const r=await page.eval('__smear.detailsQA.pixels()');r.data=inflateSync(Buffer.from(r.data,'base64'));runs.push(r);await page.shot(resolve(out,which+(meshes?'-meshes':'-instances')+'.png'));}
  const [b,a]=runs;assert.equal(a.data.length,b.data.length);let sum=0,pixelsOver5=0,max=0;for(let i=0;i<a.data.length;i+=4){let d=0;for(let c=0;c<3;c++){const delta=Math.abs(a.data[i+c]-b.data[i+c]);sum+=delta;d=Math.max(d,delta);}max=Math.max(max,d);if(d>5)pixelsOver5++;}const mean=sum/(a.data.length/4*3),ratio=pixelsOver5/(a.data.length/4);assert(a.transforms&&a.flags);assert(a.groups<=3&&a.instances<=336);assert(a.calls<b.calls);assert(mean<.35&&ratio<.005,JSON.stringify({which,mean,ratio,max}));receipt.checks.push({which,mean,ratio,max,drawsBefore:b.calls,drawsAfter:a.calls,instances:a.instances});console.log('PASS detail transforms, materials, shadows and rendered pixels: '+JSON.stringify(receipt.checks.at(-1)));
 }
 receipt.errors=page.logs.filter(s=>/^EXCEPTION:|^error:/i.test(s));assert.deepEqual(receipt.errors,[]);receipt.result='COMPLETE instanced detail checks passed';console.log(receipt.result);
}catch(error){receipt.result='FAIL';receipt.error=error.stack;throw error;}
finally{await writeFile(resolve(out,'verification.json'),JSON.stringify(receipt,null,2)+'\n');page.kill();}
