import fs from 'node:fs';import assert from 'node:assert/strict';import {resolve} from 'node:path';import {pathToFileURL} from 'node:url';import {createHash} from 'node:crypto';import {launchComputeBrowser} from './compute-browser.mjs';import {until} from './cdp.mjs';import {installHandlingFixture} from './handling-fixture.mjs';
const browser=process.argv.includes('firefox')?'firefox':'chrome',label=process.argv.find(a=>/^(round-|final)/.test(a))||'round-01',out=resolve('tools/out/destruction-pass',label+'-fragments-'+browser);fs.mkdirSync(out,{recursive:true});const page=await launchComputeBrowser({port:9730,width:1440,height:1080}),r={browser,browserProfile:page.dir,buildSHA256:createHash('sha256').update(fs.readFileSync('index.html')).digest('hex'),checks:[],cases:[]};
try{
 await page.goto(pathToFileURL(resolve('index.html')).href+'?defaults=1');await until(()=>page.eval('!!window.__smearComputeReady'),{timeout:90000});await installHandlingFixture(page);
 await page.eval(String.raw`(async()=>{const g=__smearGPU,d=g.device,module=d.createShaderModule({code:__smearComputeShaders.common+'\n'+__smearComputeShaders.compute+'\n@compute @workgroup_size(1) fn fragmentProbe(){spawnOrdnance(2u,vec3f(0,.041,2.5),vec3f(5,-3,0),.034,77u);}' });window.__fragmentProbe=await d.createComputePipelineAsync({layout:d.createPipelineLayout({bindGroupLayouts:[g.computeLayout]}),compute:{module,entryPoint:'fragmentProbe'}});})()`);
 for(const wet of [false,true]){
  await page.eval(`__handling.poolSetup({wet:${wet}})`);await page.eval('__smear.release(false);__smearGPU.bodyCount=0;__smearGPU.syncCounts()');const before=await page.eval('__handling.poolRead()');
  const stamps=await page.eval(`(async()=>{const g=__smearGPU,d=g.device;g.uniforms(1);const e=d.createCommandEncoder(),p=e.beginComputePass();p.setBindGroup(0,g.computeGroup,[0]);p.setPipeline(__fragmentProbe);p.dispatchWorkgroups(1);p.setPipeline(g.computePipelines.ordnance);p.dispatchWorkgroups(2);p.setPipeline(g.computePipelines.prepareFilm);p.dispatchWorkgroups(Math.ceil(g.filmCells/256));p.setPipeline(g.computePipelines.bin);p.dispatchWorkgroups(128);p.end();e.copyBufferToBuffer(g.workBuffer,0,g.paintDispatch,0,12);const paint=e.beginComputePass();paint.setBindGroup(0,g.computeGroup,[0]);for(const name of ['snapshotPaint','paint']){paint.setPipeline(g.computePipelines[name]);paint.dispatchWorkgroupsIndirect(g.paintDispatch,0);}paint.setPipeline(g.computePipelines.snapshotFilm);paint.dispatchWorkgroups(Math.ceil(g.filmCells/256));for(const name of ['accelerateFilm','spreadFilm','runoffFilm']){paint.setPipeline(g.computePipelines[name]);paint.dispatchWorkgroups(g.filmGroups);}paint.end();const b=g.buffer('explicit fragment stamp inspection',g.stampBuffer.size+256,GPUBufferUsage.COPY_DST|GPUBufferUsage.MAP_READ);e.copyBufferToBuffer(g.workBuffer,0,b,0,256);e.copyBufferToBuffer(g.stampBuffer,0,b,256,g.stampBuffer.size);d.queue.submit([e.finish()]);await b.mapAsync(GPUMapMode.READ);const a=b.getMappedRange().slice(0),w=new Uint32Array(a),f=new Float32Array(a);b.unmap();b.destroy();return {contacts:w[60],kinds:Array.from({length:w[3]},(_,i)=>f[64+i*16+13])};})()`);
  const after=await page.eval('__handling.poolRead()');assert(stamps.contacts>0);assert(stamps.kinds.includes(11));assert.equal(stamps.kinds.includes(3),wet);assert(Math.abs(after.total-before.total)<.0003);const delta=before.field.reduce((n,v,i)=>n+Math.abs(v-after.field[i]),0);if(wet)assert(delta>.01);else assert.equal(delta,0);delete before.field;delete after.field;r.cases.push({wet,stamps,delta,before,after});
 }r.checks.push('A fragment impact always leaves a black scuff; its wet push is conditional on actual liquid and conserves the pool');r.errors=await page.eval('__smearGPU.errors');assert.deepEqual(r.errors,[]);r.passed=true;console.log('COMPLETE fragment wetness and conservation checks');
}catch(e){r.error=e.stack;console.error(e);process.exitCode=1;}finally{fs.writeFileSync(resolve(out,'receipt.json'),JSON.stringify(r,null,2));await page.kill();}
