import assert from 'node:assert/strict';import fs from 'node:fs';import {resolve} from 'node:path';import {pathToFileURL} from 'node:url';import {createHash} from 'node:crypto';import {spawnSync} from 'node:child_process';
import {launch,until,sleep} from './cdp.mjs';import {installUtilityFixture} from './utility-fixture.mjs';
const capture=process.argv.includes('record'),out=resolve('tools/out/gauntlet-v46',capture?'capture':'checks'),review=resolve('review/v46');fs.mkdirSync(out,{recursive:true});fs.mkdirSync(review,{recursive:true});
const r={at:new Date().toISOString(),sha256:createHash('sha256').update(fs.readFileSync('index.html')).digest('hex'),checks:[],clips:[],poses:[]};let p;const check=s=>{r.checks.push(s);console.log('PASS '+s);};
const key=async code=>{for(const type of ['keyDown','keyUp'])await p.call('Input.dispatchKeyEvent',{type,code,key:code.replace('Key','').toLowerCase()});};
const pose=async(tool,yaw=0,pitch=0)=>p.eval(`(()=>{const g=__smearGPU;__smear.tool(${tool});for(const root of g.toolRoots)if(root)root.visible=false;g.handlingReview={yaw:${yaw},pitch:${pitch},offset:[-.15,.12,-.13]};g.updateToolPresentation(0,{tool:${tool},time:3,left:false});if(${tool}===1){g.gun.visible=true;g.gun.position.set(.20,-.16,-.55);g.gun.rotation.set(0,0,0);g.animateHandling({tool:1,time:3,reloadAge:10,reloadDuration:1.5,grenadeAge:10,inspectAge:10});}__smear.render();})()`);
const startVideo=async()=>p.eval(`(()=>{const g=__smearGPU;window.__proofCanvas=g.canvas;window.__proofTimer=null;window.__proofTap=__smear.compute.audioTap();window.__proofStream=new MediaStream([...__proofCanvas.captureStream(30).getVideoTracks(),...__proofTap.stream.getAudioTracks()]);window.__proofChunks=[];window.__proofRecorder=new MediaRecorder(__proofStream,{mimeType:'video/webm;codecs=vp9,opus',videoBitsPerSecond:6500000});__proofRecorder.ondataavailable=e=>{if(e.data.size)__proofChunks.push(e.data);};__proofRecorder.start(500);})()`);
const stopVideo=async name=>{const b64=await p.eval(`new Promise(resolve=>{__proofRecorder.onstop=()=>{const f=new FileReader();f.onload=()=>resolve(f.result.split(',')[1]);f.readAsDataURL(new Blob(__proofChunks));clearInterval(__proofTimer);__proofStream.getTracks().forEach(t=>t.stop());};__proofRecorder.stop();})`);const webm=resolve(out,name+'.webm'),mp4=resolve(review,name+'.mp4');fs.writeFileSync(webm,Buffer.from(b64,'base64'));const ff=spawnSync('ffmpeg',['-hide_banner','-loglevel','error','-y','-i',webm,'-c:v','libx264','-preset','fast','-crf','20','-pix_fmt','yuv420p','-c:a','aac','-b:a','160k','-movflags','+faststart',mp4],{windowsHide:true,encoding:'utf8'});assert.equal(ff.status,0,ff.stderr);r.clips.push({name,file:name+'.mp4',bytes:fs.statSync(mp4).size,audio:await p.eval('__smear.compute.audio()')});console.log('Recorded '+name);};
try{
 p=await launch({port:9681,width:1440,height:900});r.profile=p.dir;await p.goto(pathToFileURL(resolve('index.html')).href+'?defaults=1');await until(async()=>{if(p.logs.some(s=>/^EXCEPTION:|^error:/i.test(s)))throw Error(p.logs.join('\n'));return p.eval('!!window.__smearComputeReady');},{timeout:90000});await p.eval('__smear.controls.mode("cursor");__smear.manual(true)');await p.mouse('mousePressed',720,450);await p.mouse('mouseReleased',720,450);await p.eval('__smear.release(false)');
 if(!capture){
  await installUtilityFixture(p);await p.eval('__utilityTest.reset()');r.props=await p.eval('__smear.props()');const ids=r.props.map((v,i)=>v.kind==='barrel'?i:-1).filter(i=>i>=0);assert(ids.length>=2);const [a,b]=ids;
  await p.eval(`__utilityTest.pose(${a},[-2.55,.58,5]);`);await p.eval(`__utilityTest.pose(${b},[-1.75,.58,5]);`);await p.eval('__smear.step(240)');let state=await p.eval('__smear.props()');r.side={a:state[a],b:state[b]};assert(Math.hypot(state[a].p[0]-state[b].p[0],state[a].p[2]-state[b].p[2])>.80);check('Overlapping upright barrels separate and remain solid');
  await p.eval('__utilityTest.reset()');await p.eval(`__utilityTest.pose(${a},[-3,.58,5]);`);await p.eval(`__utilityTest.pose(${b},[-3,1.70,5]);`);await p.eval('__smear.step(360)');state=await p.eval('__smear.props()');r.stack={a:state[a],b:state[b]};assert(state[b].p[1]>1.64);assert(Math.hypot(...state[b].v)<.3);check('Barrel-on-barrel stack supports weight for three simulated seconds');
  await p.eval('__utilityTest.reset()');await p.eval(`__utilityTest.pose(${a},[-3,.58,5]);`);await p.eval(`__utilityTest.pose(${b},[-2,.58,5]);`);await p.eval('__smear.view([-2.5,1.6,7],[-2.5,1.1,3]);__smear.pointer(720,450);__smear.tool(10)');await p.mouse('mousePressed',720,450);await p.eval('__smear.step(240)');state=await p.eval('__smear.props()');r.magnet={a:state[a],b:state[b]};assert(state[a].p.every(Number.isFinite)&&state[b].p.every(Number.isFinite));assert(Math.hypot(...state[a].p.map((v,i)=>v-state[b].p[i]))>.7);await p.mouse('mouseReleased',720,450);check('Two magnetized barrels remain separated during a two-second pull');
  await p.eval('__smear.reset();__smear.step(0);__smear.tool(1);__smear.manual(false)');await key('KeyR');await sleep(300);assert(await p.eval('__smearGPU.handlingState.reloading'));await sleep(1500);assert(!(await p.eval('__smearGPU.handlingState.reloading')));await key('KeyI');await sleep(100);assert(await p.eval('__smearGPU.handlingState.inspecting'));check('Native R completes reload and native I starts inspection');
  const text=await p.eval('({glyphs:__smearGPU.glyphUI.glyphCount,canvas:document.body.classList.contains("gpu-letters"),r:document.getElementById("equipped-tool").getBoundingClientRect().toJSON(),meshes:__smearGPU.renderObjects.filter(x=>x.map===-2).length})');r.text=text;assert(text.canvas&&text.glyphs>0&&text.meshes>10);assert(text.r.x>720&&text.r.x<790);assert(Math.abs(text.r.y-450)<70);check('GPU glyphs cover world/tool labels and place the weapon indicator beside the reticle');
  await p.eval('__smear.panel("tune")');await sleep(250);const panelGlyphs=await p.eval('__smearGPU.glyphUI.glyphCount');assert(panelGlyphs>150);await sleep(500);assert((await p.eval('__smearGPU.glyphUI.glyphCount'))>=panelGlyphs*.9);await p.shot(resolve(out,'settings.png'));r.panelGlyphs=panelGlyphs;check('Settings glyphs stay visible while the cached canvas panel is idle');await p.eval('__smear.panel(null)');
 }else{
  await p.eval('__smear.stopBleeding();__smear.clean();__smear.view([0,2.5,6.8],[0,2.5,-7]);__smear.pointer(720,450)');
  for(let tool=1;tool<14;tool++)for(const [name,yaw,pitch]of [['front',0,0],['inside',-.55,.10],['outside',.55,-.08]]){await pose(tool,yaw,pitch);await sleep(50);const file=`tool-${tool}-${name}.png`;await p.shot(resolve(review,file));r.poses.push({tool,angle:name,file});}
  check('All thirteen held tools captured from three close inspection angles');
  await p.eval('__smear.fly();__smear.view([0,2.5,6.8],[0,2.5,-7])');
  for(const [tool,name]of [[1,'pistol'],[5,'rocket'],[12,'shotgun'],[13,'sawblade']]){
   await p.eval(`__smear.tool(${tool});__smearGPU.handlingReview=null;__smear.manual(false)`);await startVideo();await sleep(500);await key('KeyR');await sleep(2100);await key('KeyI');await sleep(3100);await p.mouse('mousePressed',720,450);await sleep(900);await p.mouse('mouseReleased',720,450);await sleep(800);await stopVideo(name);
  }
  await startVideo();for(const tool of [2,3,4,6,7,8,9,10,11]){await p.eval(`__smear.tool(${tool})`);await key('KeyI');await sleep(1350);if(tool===3||tool===4){await p.mouse('mousePressed',720,450);await sleep(350);await p.mouse('mouseReleased',720,450);}await sleep(300);}await stopVideo('tools-and-hands');
 }
 r.errors=p.logs.filter(s=>/^EXCEPTION:|^error:/i.test(s));assert.deepEqual(r.errors,[]);r.result='COMPLETE V46 '+(capture?'weapon proof capture':'gauntlet checks');console.log(r.result);
}catch(e){r.error=e.stack;console.error(e);process.exitCode=1;}finally{p?.kill();fs.writeFileSync(resolve(out,'receipt.json'),JSON.stringify(r,null,2));}
