// Matched native-time inputs with real game audio. Capture is separate from FPS gates.
import fs from 'node:fs';import {resolve} from 'node:path';import {pathToFileURL} from 'node:url';import {spawnSync} from 'node:child_process';import {createHash} from 'node:crypto';import assert from 'node:assert/strict';
import {launch,until,sleep} from './cdp.mjs';import {installHandlingFixture} from './handling-fixture.mjs';
const root=resolve('tools/out/throw-pass/recordings');fs.mkdirSync(root,{recursive:true});
const receipt={started:new Date().toISOString(),viewport:[1280,960],browsers:[],builds:[],clips:[],comparison:'smear-v29-v30-handling-and-thuds.mp4'};
function encode(args){const r=spawnSync('ffmpeg',['-hide_banner','-loglevel','error','-y',...args],{windowsHide:true,encoding:'utf8'});assert.ifError(r.error);assert.equal(r.status,0,r.stderr);}
function save(){fs.writeFileSync(resolve(root,'capture.json'),JSON.stringify(receipt,null,2)+'\n');}
for(const label of ['before','after']){
 const out=resolve(root,label);fs.mkdirSync(out,{recursive:true});const source=label==='before'?'tools/out/throw-pass/before/index.html':'index.html';fs.copyFileSync(source,resolve(out,'build.html'));
 const page=await launch({port:9694,width:1280,height:960});receipt.browsers.push({label,profile:page.dir,pid:page.proc.pid});save();
 try{
  await page.init(`(()=>{const connect=AudioNode.prototype.connect;AudioNode.prototype.connect=function(dest,...a){if(dest instanceof AudioDestinationNode)window.__qaMaster=this;return connect.call(this,dest,...a);};})()`);
  await page.goto(pathToFileURL(resolve(out,'build.html')).href);await until(()=>page.eval('!!window.__smearComputeReady'),{timeout:90000});await page.eval('__smear.manual(true)');await page.mouse('mousePressed',640,130);await page.mouse('mouseReleased',640,130);await until(()=>page.eval('__smear.compute.audio().state==="running"'),{timeout:5000});await installHandlingFixture(page);
  const version=await page.eval('__smear.state().then(s=>s.version)');receipt.builds.push({label,version,sha256:createHash('sha256').update(fs.readFileSync(source)).digest('hex')});
  for(const [name,seconds,caption]of [['pool',8,'E TWIST - PUSHING AN EXISTING POOL'],['throw',5,'FLICK WITH 67 MS RELEASE DELAY'],['wall',4,'CLEAN HEAD IMPACT + GAME AUDIO'],['floor',4,'CLEAN FLOOR IMPACT + GAME AUDIO']]){
   if(name==='pool')await page.eval('__handling.poolSetup()');else if(name==='throw'){await page.eval('__handling.throwSetup()');await page.eval('__smear.view([-.1,3.6,3],[-1.5,1.7,-4])');}else await page.eval(`__impactTest.setup({pose:'${name==='wall'?'head':'floor'}',speed:12})`);
   await page.eval(`(()=>{window.__chunks=[];window.__video=__smearGPU.canvas.captureStream(30);window.__tap=__qaMaster.context.createMediaStreamDestination();__qaMaster.connect(__tap);window.__stream=new MediaStream([...__video.getVideoTracks(),...__tap.stream.getAudioTracks()]);window.__recorder=new MediaRecorder(__stream,{mimeType:'video/webm;codecs=vp9,opus',videoBitsPerSecond:14000000,audioBitsPerSecond:192000});__recorder.ondataavailable=e=>{if(e.data.size)__chunks.push(e.data)};__recorder.start(1000);})()`);
   await page.eval('(async()=>{__smear.render();await __smearGPU.device.queue.onSubmittedWorkDone();__video.getVideoTracks()[0].requestFrame();})()');await sleep(500);
   if(name==='pool')await page.eval('__handling.twist(true);__smear.manual(false)');else if(name==='throw')await page.eval(`(()=>{const start=__smearGPU.steps,p=[...__handling.target];window.__throwTimer=setInterval(()=>{const elapsed=__smearGPU.steps-start;__smear.target([p[0]+Math.min(9,Math.floor(elapsed/2))*.15,p[1],p[2]]);if(elapsed>=26){clearInterval(__throwTimer);__smear.release();}},4);__smear.manual(false);})()`);else await page.eval('__smear.manual(false)');
   if(name==='pool'){await sleep(4000);await page.eval('__handling.twist(false);__smear.release(false)');await sleep((seconds-.5)*1000-4000);}else await sleep((seconds-.5)*1000);
   await page.eval('__smear.manual(true)');const data=await page.eval(`new Promise(resolve=>{__recorder.onstop=()=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result.split(',')[1]);reader.readAsDataURL(new Blob(__chunks,{type:'video/webm'}));__qaMaster.disconnect(__tap);__stream.getTracks().forEach(t=>t.stop());};__recorder.stop();})`);fs.writeFileSync(resolve(out,name+'.webm'),Buffer.from(data,'base64'));
   const state=await page.eval('__smear.state()');assert.deepEqual(state.errors,[]);assert.equal(state.stampOverflow,0);assert.equal(state.tileOverflow,0);receipt.clips.push({label,name,seconds,steps:state.steps,audio:await page.eval('__smear.compute.audio()')});
   encode(['-i',resolve(out,name+'.webm'),'-vf',`fps=30,tpad=stop_mode=clone:stop_duration=1,drawtext=font=Arial:text='${caption}':x=24:y=h-45:fontsize=22:fontcolor=white:box=1:boxcolor=black@0.65:boxborderw=8`,'-af','apad','-t',String(seconds),'-c:v','libx264','-preset','fast','-crf','18','-pix_fmt','yuv420p','-c:a','aac','-b:a','192k','-movflags','+faststart',resolve(out,name+'.mp4')]);console.log('Recorded '+label+'/'+name);save();
  }
  fs.writeFileSync(resolve(out,'clips.txt'),['pool','throw','wall','floor'].map(n=>`file '${n}.mp4'`).join('\n')+'\n');encode(['-f','concat','-safe','0','-i',resolve(out,'clips.txt'),'-c','copy','-movflags','+faststart',resolve(out,'handling-'+label+'.mp4')]);assert.deepEqual(page.logs.filter(s=>/^EXCEPTION:|^error:/i.test(s)),[]);
 }finally{page.kill();save();}
}
encode(['-i',resolve(root,'before/handling-before.mp4'),'-i',resolve(root,'after/handling-after.mp4'),'-filter_complex',`[0:v]scale=960:720,drawbox=x=0:y=0:w=iw:h=55:color=black@0.75:t=fill,drawtext=font=Arial:text='BEFORE / V29':x=24:y=16:fontsize=24:fontcolor=white[a];[1:v]scale=960:720,drawbox=x=0:y=0:w=iw:h=55:color=black@0.75:t=fill,drawtext=font=Arial:text='THROW GRACE + THUDS + SQUEEGEE / V30':x=24:y=16:fontsize=23:fontcolor=white[b];[a][b]hstack=inputs=2[v];[0:a]pan=mono|c0=0.5*c0+0.5*c1[left];[1:a]pan=mono|c0=0.5*c0+0.5*c1[right];[left][right]amerge=inputs=2[audio]`,'-map','[v]','-map','[audio]','-c:v','libx264','-preset','fast','-crf','18','-pix_fmt','yuv420p','-c:a','aac','-b:a','192k','-movflags','+faststart',resolve(root,receipt.comparison)]);
for(const [name,time]of [['pool',4.3],['throw',9.2],['wall',13.8],['floor',17.8]])encode(['-ss',String(time),'-i',resolve(root,receipt.comparison),'-frames:v','1',resolve(root,name+'-review.png')]);
receipt.result='COMPLETE matched V29/V30 native gameplay MP4s with stereo game audio (before left, after right)';save();console.log(receipt.result);
