import assert from 'node:assert/strict';import fs from 'node:fs';import {resolve} from 'node:path';import {pathToFileURL} from 'node:url';import {createHash} from 'node:crypto';
import {launchComputeBrowser} from './compute-browser.mjs';import {until,sleep} from './cdp.mjs';import {installHandlingFixture} from './handling-fixture.mjs';
const label=process.argv.find(v=>/^(round-|final)/.test(v))||'round-01',browser=process.argv.includes('firefox')?'firefox':'chrome',out=resolve('tools/out/throw-pass',label+'-'+browser);fs.mkdirSync(out,{recursive:true});
const page=await launchComputeBrowser({port:9692,width:1440,height:1080}),receipt={startedAt:new Date().toISOString(),browserProfile:page.dir,buildSHA256:createHash('sha256').update(fs.readFileSync('index.html')).digest('hex'),checks:[]};
async function boot(path='index.html'){await page.goto(pathToFileURL(resolve(path)).href);await until(async()=>{const r=await page.eval('({ready:!!window.__smearComputeReady,error:document.getElementById("failure")?.style.display==="block"?document.getElementById("failure").textContent:null})');if(r.error)throw Error(r.error);return r.ready;},{timeout:90000});await page.eval('__smear.manual(true)');await installHandlingFixture(page);}
async function flick(pause,reverse=false,cancel=false){await page.eval('__handling.throwSetup()');await page.eval(`__handling.flick(${pause},${reverse})`);const before=await page.eval('__handling.momentum()');await page.eval(`__smear.release(${!cancel});__smearGPU.submit(0)`);const after=await page.eval('__handling.momentum()');return {before,after};}
async function pool(options={}){await page.eval(`__handling.poolSetup(${JSON.stringify(options)})`);const before=await page.eval('__handling.poolRead()');await page.eval('__handling.twist(true);__impactTest.advance(480)');const after=await page.eval('__handling.poolRead()');await page.eval('__handling.hide()');return {before,after};}
function compact(r){const {field,...rest}=r;return rest;}
async function clickSound(){
 // V44 moved Sound into the real pause menu; exercise its native button.
 await page.eval('__smear.controls.mode("fps")');
 const b=await page.eval('(()=>{const r=document.getElementById("play-sound").getBoundingClientRect();return{x:r.x+r.width/2,y:r.y+r.height/2};})()');
 await page.mouse('mousePressed',b.x,b.y);await page.mouse('mouseReleased',b.x,b.y);await page.eval('__smear.manual(true)');
}
try{
 await boot('tools/out/throw-pass/before/index.html');receipt.beforeThrow=await flick(8);const baselinePool=await pool();receipt.beforePool={before:compact(baselinePool.before),after:compact(baselinePool.after)};await page.shot(resolve(out,'before-pool.png'));
 await boot();receipt.throws={};for(const pause of [0,2,4,8,16,32])receipt.throws[pause]=await flick(pause);
 assert(receipt.throws[8].after[0]>receipt.beforeThrow.after[0]*2.5);for(const p of [0,2,4,8])assert(receipt.throws[p].after[0]>5);for(const p of [16,32])assert.deepEqual(receipt.throws[p].after,receipt.throws[p].before);receipt.checks.push('Quick flicks retain achieved rig momentum across 17-67 ms release delays; long intentional stops receive no boost');
 receipt.reversal=await flick(4,true);assert(receipt.reversal.after[0]<0);receipt.cancel=await flick(8,false,true);assert.deepEqual(receipt.cancel.before,receipt.cancel.after);receipt.checks.push('Reversals use the latest direction; cancellation releases without a throw boost');
 receipt.guards={};for(const kind of ['stationary','new-grab','blocked']){
  await page.eval('__handling.throwSetup()');if(kind==='new-grab'){await page.eval('(async()=>{await __handling.flick(4);await __smear.grab(0,"Head");})()');}if(kind==='blocked'){await page.eval('__handling.target[2]=-8.4;__smear.target(__handling.target);__impactTest.advance(40)');}
  const before=await page.eval('__handling.momentum()');await page.eval('__smear.release();__smearGPU.submit(0)');const after=await page.eval('__handling.momentum()');assert.deepEqual(after,before);receipt.guards[kind]={before,after};
 }receipt.checks.push('Stationary grabs, a fresh grab with no history, and wall-blocked motion cannot reuse stale throw energy');
 await page.eval('__handling.throwSetup()');const wheel=await page.eval(`(()=>{const before=__smearGPU.input().target;window.dispatchEvent(new WheelEvent('wheel',{deltaY:-120,bubbles:true,cancelable:true}));const after=__smearGPU.input().target;return {before,after};})()`);receipt.wheel=wheel;
 // Use a genuine pointer-picked grab for distance changes and pointerup delivery.
 await page.eval('__smear.release(false);__smear.reset();__smear.preset("default");__smear.tune({walking:false,recover:false})');await page.eval('__smear.step(45)');const p=await page.eval('__smear.project(0,"Torso")');await page.mouse('mouseMoved',p.x,p.y);await page.mouse('mousePressed',p.x,p.y);await page.eval('__smear.render()');await until(()=>page.eval('__smearGPU.input().held'),{timeout:5000});
 receipt.pointer=await page.eval(`(()=>{const distance=()=>{const i=__smearGPU.input();return Math.hypot(...i.target.map((v,k)=>v-i.rayO[k]));};const before=distance();window.dispatchEvent(new WheelEvent('wheel',{deltaY:-120,bubbles:true,cancelable:true}));const away=distance();window.dispatchEvent(new WheelEvent('wheel',{deltaY:120,bubbles:true,cancelable:true}));return {before,away,back:distance()};})()`);assert(receipt.pointer.away>receipt.pointer.before);assert(Math.abs(receipt.pointer.back-receipt.pointer.before)<.001);await page.mouse('mouseReleased',p.x,p.y);assert.equal(await page.eval('__smearGPU.input().held'),false);receipt.checks.push('Pointer-picked grab releases with mouseup; scroll up pushes away and scroll down returns it');
 receipt.pools={};for(const [name,options]of [['default',{}],['off',{smudge:0}],['extra',{smudge:4}],['dry',{wet:false}],['hover',{hover:true}],['clean',{clean:true}]]){
  const result=await pool(options);receipt.pools[name]={before:compact(result.before),after:compact(result.after)};if(name==='default'){assert(result.after.squeezed>0);await page.shot(resolve(out,'after-pool.png'));}if(['off','dry','hover','clean'].includes(name))assert.equal(result.after.squeezed,0);
 }
 assert(receipt.pools.extra.after.squeezed>receipt.pools.default.after.squeezed);assert(receipt.pools.default.after.outer>baselinePool.after.outer*1.7);assert(receipt.pools.default.after.peak>baselinePool.after.peak*1.4);assert(receipt.pools.default.after.thin>3000);receipt.checks.push('Real E-key twisting leaves swept tracks and moves more liquid into outer ridges; stronger Smudge increases displacement and dry/hover/zero/clean controls do not squeeze');
 const isolated=await page.eval('__handling.isolateSqueeze()');receipt.conservation={before:compact(isolated.before),after:compact(isolated.after)};assert(isolated.after.squeezed>0);assert(Math.abs(isolated.after.total/isolated.before.total-1)<.002);receipt.checks.push('Isolated floor-squeegee transfers conserve mobile liquid within 0.2% fixed-point rounding across floor tile seams');
 // Tap synthesized audio before the separately muted browser output.
 await page.mouse('mousePressed',720,130);await page.mouse('mouseReleased',720,130);await until(()=>page.eval('__smear.compute.audio().state==="running"'),{timeout:5000});
 await page.eval(`(()=>{window.__audioTap=__smear.compute.audioTap();const context=__audioTap.context,source=context.createMediaStreamSource(__audioTap.stream),meter=context.createAnalyser();meter.fftSize=2048;source.connect(meter);window.__audioPeaks=[];const buffer=new Float32Array(meter.fftSize);window.__audioMeter=setInterval(()=>{meter.getFloatTimeDomainData(buffer);__audioPeaks.push(Math.max(...buffer.map(Math.abs)));},8);})()`);
 receipt.audio=[];for(const [pose,speed]of [['head',6],['head',12],['floor',12]]){
  await page.eval(`__impactTest.setup({pose:'${pose}',speed:${speed},damage:0,bleeding:0,reserve:0})`);await sleep(250);const before=await page.eval('__smear.compute.audio()');await page.eval('__audioPeaks=[];__smear.manual(false)');await sleep(900);await page.eval('__smear.manual(true)');const sound=await page.eval('__smear.compute.audio()'),peak=await page.eval('Math.max(...__audioPeaks)');assert(sound.thuds>before.thuds);assert(sound.lastThud.latency<120);assert(peak>.001);receipt.audio.push({pose,speed,before,sound,peak});
 }
 await page.eval('__handling.throwSetup();');const heldBefore=await page.eval('__smear.compute.audio()');await page.eval(`(()=>{const start=__smearGPU.steps;const p=[...__handling.target];window.__ramTimer=setInterval(()=>{__smear.target([p[0],p[1],p[2]-Math.min(4.4,(__smearGPU.steps-start)/120*18)]);},8);__audioPeaks=[];__smear.manual(false);})()`);await sleep(750);await page.eval('clearInterval(__ramTimer);__smear.manual(true)');const heldAfter=await page.eval('__smear.compute.audio()');assert(heldAfter.thuds>heldBefore.thuds);receipt.heldAudio={before:heldBefore,after:heldAfter,peak:await page.eval('Math.max(...__audioPeaks)')};assert(receipt.heldAudio.peak>.001);
 await page.eval('__handling.poolSetup({clean:true});__handling.twist(true)');const quietBefore=await page.eval('__smear.compute.audio()');await page.eval('__smear.manual(false)');await sleep(1500);await page.eval('__smear.manual(true);__handling.twist(false)');const quietAfter=await page.eval('__smear.compute.audio()');assert(quietAfter.thuds-quietBefore.thuds<=1);receipt.scrapeAudio={before:quietBefore.thuds,after:quietAfter.thuds};
 await clickSound();const muted=await page.eval('__smear.compute.audio()');assert.equal(muted.enabled,false);await page.eval('__impactTest.setup({speed:12});__smear.manual(false)');await sleep(700);await page.eval('__smear.manual(true)');assert.equal((await page.eval('__smear.compute.audio()')).thuds,muted.thuds);await clickSound();await sleep(200);assert.equal((await page.eval('__smear.compute.audio()')).thuds,muted.thuds);receipt.checks.push('Clean bloodless wall/head, held wall rams and floor collisions synthesize measurable thuds with under 120 ms GPU event latency; steady floor twisting stays quiet and mute drops events without replay');
 receipt.errors=page.logs.filter(s=>/^EXCEPTION:|^error:/i.test(s));assert.deepEqual(receipt.errors,[]);receipt.result='COMPLETE handling, impact audio and floor squeegee checks';console.log(JSON.stringify({result:receipt.result,checks:receipt.checks,throws:receipt.throws,pools:receipt.pools,audio:receipt.audio},null,2));
}catch(e){receipt.result='FAIL';receipt.error=e.stack;console.error(e.stack);process.exitCode=1;}finally{receipt.logs=page.logs;fs.writeFileSync(resolve(out,'verification.json'),JSON.stringify(receipt,null,2)+'\n');page.kill();}
