import assert from 'node:assert/strict';
import {mkdir,readFile,writeFile} from 'node:fs/promises';import {resolve} from 'node:path';import {pathToFileURL} from 'node:url';import {createHash} from 'node:crypto';
import {launchComputeBrowser} from './compute-browser.mjs';import {until} from './cdp.mjs';import {installImpactFixture} from './impact-fixture.mjs';
const label=process.argv.find(x=>/^(round-|final)/.test(x))||'round-01',out=resolve('tools/out/impact-pass',label+(process.argv.includes('firefox')?'-firefox':''));await mkdir(out,{recursive:true});
const page=await launchComputeBrowser({port:9683,width:1440,height:1080}),receipt={startedAt:new Date().toISOString(),browserProfile:page.dir,buildSHA256:createHash('sha256').update(await readFile('index.html')).digest('hex'),checks:[],cases:{}};
async function boot(file){await page.goto(pathToFileURL(resolve(file)).href);await until(async()=>{const s=await page.eval('({ready:!!window.__smearComputeReady,error:document.getElementById("failure")?.style.display==="block"?document.getElementById("failure").textContent:null})');if(s.error)throw Error(s.error);return s.ready;},{timeout:90000});await page.eval('__smear.manual(true)');await installImpactFixture(page);}
try{
 await boot('tools/out/impact-pass/before/index.html');await page.eval('__impactTest.setup()');await page.eval('__impactTest.advance(24)');receipt.baseline=await page.eval('__impactTest.read()');
 await boot('index.html');await page.mouse('mousePressed',720,130);await page.mouse('mouseReleased',720,130);await until(()=>page.eval('__smear.compute.audio().state==="running"'),{timeout:5000});receipt.audio=await page.eval('__smear.compute.audio()');
 for(const [name,config,ticks]of [['slow',{speed:2},60],['medium',{speed:6},36],['hard',{speed:12},24],['extreme',{speed:18},20],['body',{pose:'body'},24],['floor',{pose:'floor'},30],['ceiling',{pose:'ceiling'},18],['spin',{speed:0,pose:'body',spin:16},24],['glance',{speed:1,tangent:12},24],['off',{damage:0,bleeding:0},24],['empty',{reserve:0},24]]){
  await page.eval(`__impactTest.setup(${JSON.stringify(config)})`);await page.eval(`__impactTest.advance(${ticks})`);const s=await page.eval('__impactTest.read()');receipt.cases[name]=s;await page.shot(resolve(out,name+'.png'));assert.equal(s.overflow,0);assert.equal(s.tileOverflow,0);assert(s.parts.every(p=>p.p.concat(p.v,p.reserve,p.coat,p.wound).every(Number.isFinite)));console.log(name,JSON.stringify({painted:s.painted,opaque:s.opaque,liquid:s.liquid,impacts:s.impacts,spray:s.spray,volume:s.volume,head:s.parts[2]}));
 }
 const c=receipt.cases;assert(c.hard.parts[2].wound>.15);assert(c.hard.painted>Math.max(2000,receipt.baseline.painted*4));assert(c.hard.opaque>1000);assert(c.hard.spray>5);assert(c.hard.liquid>.001);receipt.checks.push('A clean head-first articulated throw wounds the head and immediately leaves a large wet impact print and ballistic spray, exceeding accepted V27 coverage');
 await page.eval('__impactTest.setup({full:true})');await page.eval('__impactTest.advance(24)');receipt.fullPool=await page.eval('__impactTest.read()');assert.equal(receipt.fullPool.spray,0);assert(receipt.fullPool.liquid>c.hard.liquid);assert.equal(receipt.fullPool.overflow,0);receipt.checks.push('When all 900 drop slots are occupied, failed spray allocations remain in the attached splat volume');
 await page.eval('__impactTest.setup({speed:0})');await page.eval('__smear.grab(0,"Head")');await page.eval('__smear.target([-3.5,2,-5.5])');await page.eval('__impactTest.advance(60)');await page.eval('(async()=>{for(let i=1;i<=10;i++){__smear.target([-3.5,2,-5.5-i*.16]);await __impactTest.advance(2);}__smear.release();})()');receipt.release=await page.eval('__impactTest.read()');await page.eval('__impactTest.advance(40)');receipt.grabThrow=await page.eval('__impactTest.read()');assert(receipt.grabThrow.impacts>receipt.release.impacts);assert(receipt.grabThrow.painted>2000);await page.shot(resolve(out,'grab-throw.png'));receipt.checks.push('A normal grab, accelerated target and release produces an actual thrown-body splat without a launch-velocity upload');
 assert(c.medium.volume<c.hard.volume);assert(c.extreme.parts[2].reserve<c.hard.parts[2].reserve);assert(c.hard.parts[2].reserve<c.medium.parts[2].reserve);assert(c.medium.painted<c.hard.painted);receipt.checks.push('Actual collision velocity loss increases head injury and reserve expenditure from medium through extreme throws; hard throws spread further than medium throws');
 for(const name of ['body','floor','ceiling','spin'])assert(c[name].impacts>0&&c[name].painted>1000);receipt.checks.push('Torso-first wall hits, angular strikes, floor impacts and ceiling impacts all generate fresh blood without scraping');
 for(const name of ['slow','glance','off'])assert.equal(c[name].impacts,0,name);assert.equal(c.off.painted,0);assert.equal(c.empty.volume,0);assert.equal(c.empty.painted,0);receipt.checks.push('Slow contact, fast tangential glancing travel and disabled damage produce no injury burst; an empty reserve produces no fresh paint');
 for(const s of Object.values(c)){assert(s.parts.every(p=>p.reserve>=0&&p.coat<=1.65001));assert(s.volume<=s.parts.reduce((n,p)=>n+9-p.reserve,0)*.1001+.0002);}receipt.checks.push('Impact supply debits the finite reserve, retains bounded coating and never exceeds the volume purchased from blood reserves');
 await page.eval('__impactTest.setup()');await page.eval('__impactTest.advance(24)');const hit=await page.eval('__impactTest.read()');await page.eval('__impactTest.hide()');await page.eval('__impactTest.advance(360)');receipt.three=await page.eval('__impactTest.read()');await page.shot(resolve(out,'drain-3s.png'));await page.eval('__impactTest.advance(1440)');receipt.fifteen=await page.eval('__impactTest.read()');await page.shot(resolve(out,'drain-15s.png'));assert(receipt.fifteen.alpha>hit.alpha*.95);assert(receipt.fifteen.liquid<receipt.three.liquid);assert(receipt.three.liquid>0);receipt.checks.push('The impact stain remains while finite wet liquid continues draining through 3 and 15 seconds of release');
 const state=await page.eval('__smear.compute.state()');assert.deepEqual(state.errors,[]);assert.deepEqual(page.logs.filter(x=>/^EXCEPTION:|^error:/i.test(x)),[]);receipt.result='COMPLETE velocity-driven impact checks';console.log(receipt.result,receipt.checks.length);
}catch(e){receipt.result='FAIL';receipt.error=e.stack;console.error(e.stack);process.exitCode=1;}finally{await writeFile(resolve(out,'verification.json'),JSON.stringify(receipt,null,2)+'\n');page.kill();}
