import assert from 'node:assert/strict';import {mkdir,readFile,writeFile} from 'node:fs/promises';import {resolve} from 'node:path';import {pathToFileURL} from 'node:url';import {createHash} from 'node:crypto';
import {launchComputeBrowser} from './compute-browser.mjs';import {until,sleep} from './cdp.mjs';import {installImpactFixture} from './impact-fixture.mjs';
const browser=process.argv.includes('firefox')?'firefox':'chrome',out=resolve('tools/out/impact-pass/native-'+browser);await mkdir(out,{recursive:true});
const page=await launchComputeBrowser({port:9685,width:3000,height:1800}),receipt={startedAt:new Date().toISOString(),viewport:[3000,1800],browser,buildSHA256:createHash('sha256').update(await readFile('index.html')).digest('hex'),browserProfile:page.dir,checks:[],profiles:[]};
try{
 await page.goto(pathToFileURL(resolve('index.html')).href);await until(()=>page.eval('!!window.__smearComputeReady'),{timeout:90000});await page.eval('__smear.manual(true);__smear.perf.show(true)');await page.mouse('mousePressed',1500,130);await page.mouse('mouseReleased',1500,130);await until(()=>page.eval('__smear.compute.audio().state==="running"'),{timeout:5000});receipt.audio=await page.eval('__smear.compute.audio()');await installImpactFixture(page);
 await page.eval(`(()=>{window.__impactAudit={active:false,reads:{},writes:{},canvasReads:0,webGLContexts:0};const imageRead=CanvasRenderingContext2D.prototype.getImageData;CanvasRenderingContext2D.prototype.getImageData=function(...a){if(__impactAudit.active)__impactAudit.canvasReads++;return imageRead.apply(this,a)};const context=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(type,...a){if(__impactAudit.active&&/^webgl/.test(type))__impactAudit.webGLContexts++;return context.call(this,type,...a)};const map=GPUBuffer.prototype.mapAsync;GPUBuffer.prototype.mapAsync=function(...a){if(__impactAudit.active)__impactAudit.reads[this.label]=(__impactAudit.reads[this.label]||0)+1;return map.apply(this,a)};const write=GPUQueue.prototype.writeBuffer;GPUQueue.prototype.writeBuffer=function(b,o,v,...a){if(__impactAudit.active)__impactAudit.writes[b.label]=(__impactAudit.writes[b.label]||0)+v.byteLength;return write.call(this,b,o,v,...a)};})()`);
 for(const pose of ['head','body']){
  await page.eval(`__impactTest.setup({pose:'${pose}',speed:12})`);await sleep(250);
  await page.eval('__smear.perf.clear();__smearGPU.gpuSamples.length=0;__impactAudit.reads={};__impactAudit.writes={};__impactAudit.active=true;__smear.manual(false)');const firstTick=await page.eval('__smearGPU.steps'),started=Date.now();await sleep(6000);await page.eval('__smear.manual(true);__impactAudit.active=false');const elapsed=(Date.now()-started)/1000;
  const report=await page.eval('__smear.perf.report()'),state=await page.eval('__smear.compute.state()'),audit=await page.eval('__impactAudit'),impact=await page.eval('__impactTest.read()'),ticksPerSecond=(state.steps-firstTick)/elapsed;
  assert.deepEqual(state.errors,[]);assert.equal(state.stampOverflow,0);assert.equal(state.tileOverflow,0);assert(impact.impacts>0&&impact.spray>0&&impact.painted>2000);assert(report.summary.fps>55);assert(report.summary.workPercentileMs.p99<5);assert(ticksPerSecond>110&&ticksPerSecond<125);assert(!Object.keys(audit.reads).some(k=>/inspection|pigment|ragdoll/i.test(k)));assert(!Object.keys(audit.writes).some(k=>/pigment|droplet|ragdoll/i.test(k)));receipt.profiles.push({label:pose+'-impact',report,state,audit,ticksPerSecond,impact});receipt.checks.push('Native '+pose+'-first impact at 3000x1800: above 55 FPS, CPU p99 below 5 ms, live 120 Hz simulation, spray and no normal-play pose/paint transfers');await page.shot(resolve(out,pose+'.png'));console.log(JSON.stringify({pose,fps:report.summary.fps,cpuP99:report.summary.workPercentileMs.p99,gpu:report.compute.summary}));
 }
 assert.deepEqual(page.logs.filter(s=>/^EXCEPTION:|^error:/i.test(s)),[]);receipt.result='COMPLETE native impact profiles';console.log(receipt.result);
}catch(e){receipt.result='FAIL';receipt.error=e.stack;console.error(e.stack);process.exitCode=1;}finally{await writeFile(resolve(out,'verification.json'),JSON.stringify(receipt,null,2)+'\n');page.kill();}
