import {useMachineSwitch} from './machine-input.mjs';
import fs from 'node:fs';import assert from 'node:assert/strict';import {resolve} from 'node:path';import {pathToFileURL} from 'node:url';import {spawnSync} from 'node:child_process';import {createHash} from 'node:crypto';import {launch,until,sleep} from './cdp.mjs';
const out=resolve('tools/out/ui-v44-pass/recordings');fs.mkdirSync(out,{recursive:true});const r={at:new Date().toISOString(),sha256:createHash('sha256').update(fs.readFileSync('index.html')).digest('hex'),clips:[]};
for(const name of ['crusher','glass','pinball']){const page=await launch({port:9796,width:1600,height:1000,headless:true}),clip={name,profile:page.dir};r.clips.push(clip);try{
 await page.goto(pathToFileURL(resolve('index.html')).href+'?defaults=1&demo='+name);await until(()=>page.eval('!!window.__smearComputeReady'),{timeout:90000});await page.eval('__smear.manual(true)');await page.mouse('mousePressed',800,120);await page.mouse('mouseReleased',800,120);await page.eval('__smear.manual(true);__smear.fly()');await page.eval('__smear.step(600)');await page.shot(resolve(out,name+'-armed.png'));
 await page.eval(`(()=>{window.__chunks=[];const tap=__smear.compute.audioTap();window.__stream=new MediaStream([...__smearGPU.canvas.captureStream(30).getVideoTracks(),...tap.stream.getAudioTracks()]);window.__recorder=new MediaRecorder(__stream,{mimeType:'video/webm;codecs=vp9,opus',videoBitsPerSecond:14000000});__recorder.ondataavailable=e=>{if(e.data.size)__chunks.push(e.data)};__recorder.start(1000);__smear.render();})()`);
 await sleep(200);await useMachineSwitch(page,{crusher:18,glass:22,pinball:23}[name]);await page.eval('__smear.view([-1.3,1.8,6.2],[-2.6,1.15,3.3])');await page.eval('__smear.manual(false)');await sleep(1800);await page.shot(resolve(out,name+'-working.png'));await sleep(2500);await page.eval('__smear.view([-1.6,1.2,5.5],[-2.6,.22,3.3])');await sleep(2000);await page.eval('__smear.manual(true)');await page.shot(resolve(out,name+'-debris.png'));
 const data=await page.eval(`new Promise(resolve=>{__recorder.onstop=()=>{const f=new FileReader();f.onload=()=>resolve(f.result.split(',')[1]);f.readAsDataURL(new Blob(__chunks,{type:'video/webm'}));__stream.getTracks().forEach(t=>t.stop());};__recorder.stop();})`);fs.writeFileSync(resolve(out,name+'.webm'),Buffer.from(data,'base64'));const result=spawnSync('ffmpeg',['-nostdin','-hide_banner','-loglevel','error','-y','-i',resolve(out,name+'.webm'),'-vf','fps=30','-c:v','libx264','-preset','fast','-crf','18','-pix_fmt','yuv420p','-c:a','aac','-b:a','192k','-movflags','+faststart',resolve(out,name+'.mp4')],{encoding:'utf8',windowsHide:true,timeout:120000});assert.ifError(result.error);assert.equal(result.status,0,result.stderr);clip.audio=await page.eval('__smear.compute.audio()');assert(clip.audio.enabled&&clip.audio.state==='running');clip.props=await page.eval('__smear.props()');assert(clip.props.some(p=>p.broken));assert.deepEqual(page.logs.filter(s=>/^EXCEPTION:|^error:/i.test(s)),[]);console.log('Captured '+name);
 }finally{page.kill();fs.writeFileSync(resolve(out,'capture.json'),JSON.stringify(r,null,2)+'\n');}}
r.result='COMPLETE three native machinery recordings with game audio';fs.writeFileSync(resolve(out,'capture.json'),JSON.stringify(r,null,2)+'\n');console.log(r.result);
