import {useMachineSwitch} from './machine-input.mjs';
import fs from 'node:fs';import assert from 'node:assert/strict';import {resolve} from 'node:path';import {pathToFileURL} from 'node:url';import {createHash} from 'node:crypto';
import {launch,until,sleep} from './cdp.mjs';import {installUtilityFixture} from './utility-fixture.mjs';import {installBatFixture} from './bat-fixture.mjs';
import {installJunkFixture} from './junk-fixture.mjs';
const label=process.argv[2]||'current',out=resolve('tools/out/junk-v43-pass/'+label);fs.mkdirSync(out,{recursive:true});let page;const r={at:new Date().toISOString(),sha256:createHash('sha256').update(fs.readFileSync('index.html')).digest('hex'),checks:[]};const check=s=>{r.checks.push(s);console.log('PASS '+s);};
try{
 page=await launch({port:9793,width:1600,height:1000,headless:true});r.profile=page.dir;await page.goto(process.env.SMEAR_TEST_URL||pathToFileURL(resolve('index.html')).href+'?defaults=1');await until(async()=>{const s=await page.eval('({ready:!!window.__smearComputeReady,error:window.__smearGPU?.errors,failure:document.getElementById("failure")?.textContent})');if(s.error?.length)throw Error(s.error.join('\n'));return s.ready;},{timeout:90000});await page.eval('__smear.manual(true)');await page.mouse('mousePressed',800,120);await page.mouse('mouseReleased',800,120);await installUtilityFixture(page);await installBatFixture(page);
 r.layout=await page.eval('({props:__smearGPU.props.length,surfaces:__smearGPU.surfaces.length,active:__smearGPU.props.filter((p,i)=>i<6).length,storage:__smearGPU.workBuffer.size,errors:__smearGPU.errors})');assert.equal(r.layout.props,24);assert.equal(r.layout.surfaces,221);check('Hardware WebGPU boots with 24 props, 221 world receivers and the original physics/paint capacities');
 await installJunkFixture(page);
 await page.eval('__utilityTest.reset()');r.placement=await page.eval('__junkTest.place(9)');assert.equal(r.placement.status,1);assert.equal(r.placement.slot,18);let group=await page.eval('__smear.props()');assert(group.slice(18,22).every(p=>p.active));await page.eval('__smear.utility.toggle(20)');assert.equal((await page.eval('__junkTest.stats()')).power[18],0);assert(await page.eval('__smearGPU.removeToy(21)'));assert((await page.eval('__smear.props()')).slice(18,22).every(p=>!p.active));
 r.badPlacement=await page.eval('__junkTest.place(9,[-3.8,0,5])');assert.notEqual(r.badPlacement.status,1);await page.eval('__smearGPU.cancelBuddy()');check('Crusher placement, child selection, power and removal treat all four colliders as one machine; occupied placement is rejected');
 r.materials=[];for(const [kind,id,fragment]of [[6,12,8],[7,14,9],[8,16,10]]){
  await page.eval('__utilityTest.reset()');const placed=await page.eval('__junkTest.place('+kind+')');assert.equal(placed.status,1);await page.eval('__smear.tool(1);__smear.view([-3,.45,6.5],[-3,.45,5]);__smear.pointer(800,500)');let count=0;while((await page.eval('__smear.props()'))[id].active&&count<5){await page.eval('__smearGPU.shoot();__smearGPU.submit(0);__smearGPU.device.queue.onSubmittedWorkDone()');count++;}const fragments=(await page.eval('__utilityTest.ord()')).filter(o=>o.kind===fragment);assert(fragments.length>=22);assert(!(await page.eval('__smear.props()'))[id].active);await page.eval('__utilityTest.advance(180)');assert((await page.eval('__utilityTest.ord()')).some(o=>o.kind===fragment));r.materials.push({kind,count,fragments:fragments.length});await page.shot(resolve(out,'material-'+kind+'.png'));
 }check('Pistol hits break glass, ceramic and metal into their own persistent physical fragments');
 await page.eval('__utilityTest.reset()');await page.eval('__junkTest.place(6)');await page.eval('(async()=>{for(let i=8;i<128;i++)await __junkTest.fragment(2,{slot:i,p:[0,2,6],v:[0,0,0]});await __junkTest.fillDrops();await __junkTest.damage(12);})()');assert((await page.eval('__utilityTest.ord()')).filter(o=>o.kind===8).length>=22);check('Glass still produces visible shards with all 120 debris slots and all 900 droplets occupied');
 r.sliding=[];let wetFields=[];for(const scenario of ['dry','wet','control']){
  await page.eval('__utilityTest.reset()');if(scenario!=='dry')await page.eval('__utilityTest.patch({point:[-2.7,0,5],radius:1.6,mass:.5})');const before=await page.eval('__utilityTest.state()');if(scenario!=='control')await page.eval('__junkTest.fragment(8,{p:[-3.2,.095,5],v:[3,0,0]})');await page.eval('__utilityTest.advance(120)');const after=await page.eval('__utilityTest.state()'),ord=await page.eval('__utilityTest.ord()');r.sliding.push({scenario,before:before.total,after:after.total,fragment:ord[8]});assert(Math.abs(after.total-before.total)<.002);if(scenario!=='dry')wetFields.push(await page.eval('__junkTest.field()'));
 }assert(r.sliding[1].fragment.p[0]>r.sliding[0].fragment.p[0]+.3);r.filmDelta=wetFields[0].reduce((n,v,i)=>n+Math.abs(v-wetFields[1][i]),0);assert(r.filmDelta>100);check('Glass slides farther on wet blood than dry floor, redistributes the actual film and conserves its finite supply');
 await page.eval('__utilityTest.reset()');await page.eval('__junkTest.place(6)');await page.eval('__junkTest.surfaceWet(12)');const wetBefore=await page.eval('__utilityTest.state()');await page.eval('__junkTest.damage(12)');await page.eval('__utilityTest.advance(120)');const wetAfter=await page.eval('__utilityTest.state()');r.wetBreak={before:wetBefore.total,after:wetAfter.total};assert(Math.abs(wetBefore.total-wetAfter.total)<.001);check('Breaking a wet glass panel returns its finite liquid to the room');
 await page.eval('__utilityTest.reset()');await page.eval('__smear.view([-3,1.3,6.5],[-3,.7,4.5]);__smear.pointer(800,500);__smear.tool(9)');await page.eval('(async()=>{for(let n=0;n<3;n++)await __junkTest.fragment(8+n,{slot:8+n,p:[-3+n*.03,.7,4.5],v:[0,0,0]});})()');await page.mouse('mousePressed',800,500);await page.eval('__utilityTest.advance(2)');await page.mouse('mouseReleased',800,500);assert.equal((await page.eval('__utilityTest.state()')).debris,3);await page.mouse('mousePressed',800,500,'right');await page.eval('__utilityTest.advance(12)');await page.mouse('mouseReleased',800,500,'right');const recycled=await page.eval('__utilityTest.ord()');assert([8,9,10].every(kind=>recycled.some(o=>o.kind===kind)));assert.equal((await page.eval('__utilityTest.state()')).debris,0);check('Vacuum collection and reverse retain glass, ceramic and metal material identity');
 await page.eval('__utilityTest.reset()');await page.eval('__junkTest.place(8,[-3,0,4])');await page.eval('__smear.view([-3,1.1,6.5],[-3,.5,4]);__smear.pointer(800,500);__smear.tool(10)');const canBefore=(await page.eval('__smear.props()'))[16];await page.mouse('mousePressed',800,500);await page.eval('__utilityTest.advance(60)');await page.mouse('mouseReleased',800,500);const canAfter=(await page.eval('__smear.props()'))[16];assert(canAfter.p[2]>canBefore.p[2]+.35);check('The magnet acquires the new metal cans through the same occluded field as barrels');
 await page.eval('__utilityTest.reset()');await page.eval('__junkTest.place(9)');r.pressSupply=[];
 for(const damage of [1,0]){await page.eval(`(async()=>{const g=__smearGPU,a=new Float32Array(await __destructionFixture.read(g.seedBuffer,0,104*4));a.set([-3,1.05,5],0);a.set([0,0,0,1],4);a.set([0,0,0,.08],32);a.set([0,0,0,100],36);g.device.queue.writeBuffer(g.bodyBuffer,0,a);g.bodyCount=1;__smear.tune({damage:${damage}});Object.assign(g.input().tune,{damage:${damage}});g.device.queue.writeBuffer(g.workBuffer,(g.utilityBase+32+18*8+2)*4,new Float32Array([1.60]));await __junkTest.fillDrops();})()`);const before=await page.eval('__junkTest.bodies()');await page.eval('__junkTest.directMachine()');const after=await page.eval('__junkTest.bodies()');r.pressSupply.push({damage,before:before.slice(32,40),after:after.slice(32,40)});assert(Math.abs(before[35]*.1+before[32]*.02-after[35]*.1-after[32]*.02)<1e-7);if(damage){assert(after[35]<before[35]);assert(after[39]<100);}else assert.deepEqual(after.slice(32,40),before.slice(32,40));}
 await page.eval('__smear.preset("default")');check('Crusher contact pays coating from a finite body reserve even with full droplets; zero damage tuning suppresses injury');
 r.launchContact=[];for(const height of [.95,.65]){await page.eval('__utilityTest.reset()');await page.eval('__junkTest.place(12)');await page.eval('__smear.utility.toggle(22)');await page.eval('__utilityTest.pose(16,[-3,'+height+',5])');await page.eval('__smear.utility.toggle(22)');await page.eval('__junkTest.directMachine()');const first=await page.eval('__junkTest.stats()');await page.eval('__junkTest.directMachine()');const second=await page.eval('__junkTest.stats()');r.launchContact.push({height,first:first.launches,second:second.launches});assert.equal(first.launches,height===.65?1:0);assert.equal(first.launches,second.launches);}check('The spring pad launches a contacting can once per cooldown and ignores one hovering above it');
 r.demos=[];
 for(const name of ['crusher','glass','pinball']){
  await page.eval('__smear.utility.demo('+JSON.stringify(name)+');__smear.manual(true)');await page.eval('__smear.step(0)');const armed=await page.eval('__smear.props()');await page.eval('__utilityTest.advance(600)');const held=await page.eval('__smear.props()'),heldBody=await page.eval('__smear.state()');await page.shot(resolve(out,name+'-armed.png'));r.demos.push({name,armed,held,heldBody});assert(held.every(p=>!p.broken));const machineID={crusher:19,glass:22,pinball:23}[name];assert.deepEqual(held[machineID].p,armed[machineID].p);assert.deepEqual(held[machineID].q,armed[machineID].q);
  await page.eval('__smear.utility.run();__smear.manual(true)');await page.eval('__utilityTest.advance(480)');const after=await page.eval('(async()=>({props:await __smear.props(),ord:await __utilityTest.ord(),body:await __smear.state(),utility:await __utilityTest.state()}))()');r.demos.at(-1).after=after;await page.shot(resolve(out,name+'-running.png'));console.log(name+': active '+after.props.filter(p=>p.active).length+', fragments '+after.ord.filter(p=>p.kind>=8).length+', injuries '+after.utility.words[22]);assert.deepEqual(after.body.errors,[]);assert(after.ord.some(o=>o.kind>=8),'demo must create junk fragments');if(name==='crusher')assert(after.utility.words[22]>0,'press must physically injure its buddy');if(name==='glass')assert(after.utility.words[24]>0);
 }
 check('All three finite-blood demos run through four seconds of actual machine physics');
 await page.eval('__smear.utility.demo("crusher");__smear.manual(true)');await page.eval('__utilityTest.advance(600)');await useMachineSwitch(page,18);await page.eval('__smear.manual(false)');await sleep(2600);await page.eval('__smear.manual(true)');r.nativePress=await page.eval('__junkTest.stats()');assert(r.nativePress.injuries>0);await page.eval('__smear.utility.toggle(19)');const stopped=(await page.eval('__smear.props()'))[19];await page.eval('__utilityTest.advance(120)');assert.deepEqual((await page.eval('__smear.props()'))[19].p,stopped.p);check('Native E on the switch runs the armed crusher; X on its plate stops it at its current position');
 r.logs=page.logs;assert(!page.logs.some(s=>/^error:|^EXCEPTION:/.test(s)));r.result='COMPLETE junk and machine checks';console.log(r.result);
}catch(e){r.result='FAIL';r.error=e.stack;console.error(e.stack);process.exitCode=1;}finally{if(page)page.kill();fs.writeFileSync(resolve(out,'verification.json'),JSON.stringify(r,null,2)+'\n');}
