import fs from 'node:fs';import assert from 'node:assert/strict';import {resolve} from 'node:path';import {createHash} from 'node:crypto';import {launch,until,sleep} from './cdp.mjs';import {useMachineSwitch} from './machine-input.mjs';import {installJunkFixture} from './junk-fixture.mjs';
const out=resolve('tools/out/startup-v47/live'),url='https://tront.xyz/smear/',hash=b=>createHash('sha256').update(b).digest('hex'),r={at:new Date().toISOString(),version:'0.47.0',commit:process.env.SMEAR_RELEASE_COMMIT,url,sha256:hash(fs.readFileSync('index.html')),checks:[]};let page;
const check=s=>{r.checks.push(s);console.log('PASS '+s);};
try{
 fs.mkdirSync(out,{recursive:true});
 const response=await fetch(url+'?v=47&release='+Date.now(),{cache:'no-store',signal:AbortSignal.timeout(20000)});assert.equal(response.status,200);assert.equal(hash(Buffer.from(await response.arrayBuffer())),r.sha256);check('Public HTML exactly matches the verified V47 build');
 const image=await fetch(url+'og-image.png');assert.equal(image.status,200);const png=Buffer.from(await image.arrayBuffer());assert.equal(png.readUInt32BE(16),1200);assert.equal(png.readUInt32BE(20),630);assert.equal((await fetch(url+'favicon.svg')).status,200);const games=await fetch('https://tront.xyz/games/');assert.equal(games.status,200);assert((await games.text()).includes('/smear/'));check('Portfolio link, favicon and 1200x630 OG image remain available');
 page=await launch({port:9754,width:1600,height:1000,headless:true});r.profile=page.dir;await page.init(`let ready=false;Object.defineProperty(window,'__smearComputeReady',{configurable:true,get:()=>ready,set:v=>{ready=v;if(v)window.__readyMS=performance.now();}});`);await page.goto(url+'?v=47&defaults=1&release='+r.commit);await until(()=>page.eval('!!window.__smearComputeReady'),{timeout:90000});r.startup=await page.eval('({readyMs:__readyMS,navigation:performance.getEntriesByType("navigation")[0].toJSON()})');assert((await page.eval('__smear.controls.state()')).paused);
 const button=await page.eval('(()=>{const b=document.getElementById("play-resume").getBoundingClientRect();return{x:b.x+b.width/2,y:b.y+b.height/2};})()');await page.mouse('mousePressed',button.x,button.y);await page.mouse('mouseReleased',button.x,button.y);await until(()=>page.eval('!!document.pointerLockElement'),{timeout:5000});await sleep(200);assert.deepEqual(await page.eval('__smear.ui()'),[]);await page.eval('__smear.manual(true)');const initial=await page.eval('__smear.state()');r.adapter=initial.adapter;assert.equal(initial.version,'0.47.0');assert.equal(initial.adapter.isFallbackAdapter,false);assert.equal(initial.normalPaintReadbacks,0);assert.deepEqual(initial.errors,[]);const lightBefore=await page.eval('__smearGPU.movingLights.map(l=>Array.from(l.data))');await page.eval('__smear.step(120)');const lightAfter=await page.eval('__smearGPU.movingLights.map(l=>Array.from(l.data))');assert.equal(lightAfter.length,2);assert.notDeepEqual(lightBefore,lightAfter);const advanced=await page.eval('__smear.state()');assert.equal(advanced.steps-initial.steps,120);assert(advanced.parts.every(p=>[...p.p,...p.q,...p.v].every(Number.isFinite)));check('Published build captures the mouse, has a quiet HUD, moving LTC emitters and completes 120 ticks on hardware WebGPU');
 for(const type of ['keyDown','keyUp'])await page.call('Input.dispatchKeyEvent',{type,key:'b',code:'KeyB',windowsVirtualKeyCode:66});assert(await page.eval('!document.getElementById("toybox").hidden'));assert.equal(await page.eval('document.querySelectorAll("[data-tool]").length'),14);assert.equal(await page.eval('getComputedStyle(document.getElementById("play-menu")).display'),'none');await page.shot(resolve(out,'live-toybox.png'));for(const type of ['keyDown','keyUp'])await page.call('Input.dispatchKeyEvent',{type,key:'Escape',code:'Escape',windowsVirtualKeyCode:27});check('Published Toybox exposes fourteen tools and releases the cursor without stacking pause');
 await installJunkFixture(page);r.demos=[];for(const [name,id]of [['crusher',18],['glass',22],['pinball',23]]){await page.eval('__smear.utility.demo('+JSON.stringify(name)+');__smear.manual(true);__smear.step(0)');assert.equal((await page.eval('__junkTest.stats()')).power[id],0);await page.eval('__utilityTest.advance(600)');await useMachineSwitch(page,id);assert.equal((await page.eval('__junkTest.stats()')).power[id],1);await page.eval('__utilityTest.advance(480)');const stats=await page.eval('__junkTest.stats()'),pieces=await page.eval('__utilityTest.ord()');assert(pieces.some(p=>p.kind>=8));if(name==='crusher')assert(stats.injuries>0);r.demos.push({name,stats,fragments:pieces.filter(p=>p.kind>=8).length});await page.shot(resolve(out,'live-'+name+'.png'));}check('All three published demos start through native E on real switches and create physical debris');
 r.audio=await page.eval('__smear.compute.audio()');assert(r.audio.enabled&&r.audio.state==='running');assert.equal(await page.eval('window.__smearLights.length'),21);assert.equal(await page.eval('!!__smearGPU.shadowPipeline'),false);assert.deepEqual(page.logs.filter(s=>/^error:|^EXCEPTION:/.test(s)),[]);check('Game audio, 21 LTC emitters and the sun-free renderer remain active without errors');await page.goto(url+'review/v47/');await until(()=>page.eval('document.querySelectorAll("video").length===1'),{timeout:15000});await page.eval('document.fonts.ready');await page.eval('(async()=>{const v=document.querySelector("video");v.muted=true;await v.play();})()');await sleep(750);assert(await page.eval('document.querySelector("video").currentTime>0&&document.querySelector("video").videoWidth===1600'));await page.eval('document.querySelector("video").pause()');await page.shot(resolve(out,'live-proof.png'));check('Published proof page displays UI screenshots and plays the Firefox startup H264 MP4');r.result='COMPLETE live V47 verification';console.log(r.result);
}catch(e){r.result='FAIL';r.error=e.stack;r.logs=page?.logs;console.error(e.stack);process.exitCode=1;}finally{page?.kill();fs.writeFileSync(resolve(out,'live-verification.json'),JSON.stringify(r,null,2)+'\n');}
