// Independent solid-angle quadrature against the shipping horizon-clipped GPU integral.
import fs from 'node:fs';import assert from 'node:assert/strict';import {resolve} from 'node:path';import {pathToFileURL} from 'node:url';import {createHash} from 'node:crypto';
import {launchComputeBrowser} from './compute-browser.mjs';import {until} from './cdp.mjs';import {installBrushFlowFixture} from './brush-flow-fixture.mjs';
const label=process.argv.find(s=>/^(round-|final)/.test(s))||'round-01',browser=process.argv.includes('firefox')?'firefox':'chrome',out=resolve('tools/out/controller-pass',label+'-ltc-'+browser);fs.mkdirSync(out,{recursive:true});
const page=await launchComputeBrowser({port:9697,width:1440,height:1080}),receipt={buildSHA256:createHash('sha256').update(fs.readFileSync('index.html')).digest('hex'),browserProfile:page.dir,checks:[]};
const dot=(a,b)=>a.reduce((s,v,i)=>s+v*b[i],0),cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],norm=a=>a.map(v=>v/Math.hypot(...a));
const cases=[{p:[0,0,1],n:[0,1,0],v:[0,1,0],r:.1},{p:[.2,0,1],n:[0,1,0],v:[0,.25,1],r:.18},{p:[1,1,-7.9],n:[0,0,1],v:[-.5,.4,1],r:.22},{p:[1,.5,2],n:[.7,.25,.65],v:[0,1,1],r:.65},{p:[-4,1,-3],n:[0,1,0],v:[1,.05,0],r:.4},{p:[0,5,0],n:[0,-1,0],v:[0,-1,0],r:.2}].map(c=>({...c,n:norm(c.n),v:norm(c.v)}));
const raw=fs.readFileSync('vendor/ltc/ggx.bin'),table=new Float32Array(raw.buffer,raw.byteOffset,raw.byteLength/4);
function lookup(r,nv,layer){const x=Math.max(0,Math.min(1,r))*63,y=Math.sqrt(Math.max(0,1-Math.max(0,Math.min(1,nv))))*63,a=Math.floor(x),b=Math.floor(y),f=x-a,g=y-b;return Array.from({length:4},(_,k)=>{const at=(i,j)=>table[layer*16384+4*(i+64*j)+k];return (at(a,b)*(1-f)+at(Math.min(a+1,63),b)*f)*(1-g)+(at(a,Math.min(b+1,63))*(1-f)+at(Math.min(a+1,63),Math.min(b+1,63))*f)*g;});}
function reference(c){let t=c.v.map((v,i)=>v-c.n[i]*dot(c.n,c.v));if(dot(t,t)<1e-8)t=cross(Math.abs(c.n[1])>.99?[1,0,0]:[0,1,0],c.n);t=norm(t);const bit=cross(c.n,t),m=lookup(c.r,dot(c.n,c.v),0),amp=lookup(c.r,dot(c.n,c.v),1),det=Math.abs(m[0]*m[3]-m[1]*m[2]),result=[0,0,0],base=[.05,.002,.006],S=256;
 for(let j=0;j<8;j++){const ceiling=j<3,center=ceiling?[-5+j*5,4.8825,0]:[-5.8+(j-3)*2.9,3.88,-7.929],u=ceiling?[.08,0,0]:[1.155,0,0],v=ceiling?[0,0,5.85]:[0,.41,0],n=ceiling?[0,-1,0]:[0,0,1],em=ceiling?[22,23,21]:[3.8,5.2,5.4];if(dot(n,c.p.map((p,i)=>p-center[i]))<=0)continue;const da=4*Math.hypot(...u)*Math.hypot(...v)/(S*S);let ed=0,es=0;
  for(let y=0;y<S;y++)for(let x=0;x<S;x++){const d=center.map((p,i)=>p+u[i]*((x+.5)/S*2-1)+v[i]*((y+.5)/S*2-1)-c.p[i]),len=Math.hypot(...d),w=d.map(p=>p/len),omega=da*Math.abs(dot(n,w))/(len*len),local=[dot(t,w),dot(bit,w),dot(c.n,w)],q=[m[0]*local[0]+m[2]*local[2],local[1],m[1]*local[0]+m[3]*local[2]],l2=dot(q,q);ed+=omega*Math.max(0,local[2])/Math.PI;es+=omega*det*Math.max(0,q[2])/(Math.PI*l2*l2);}
  for(let k=0;k<3;k++)result[k]+=em[k]*(base[k]*.96*ed+(.04*amp[0]+.96*amp[1])*es);
 }return result;}
try{
 await page.goto(pathToFileURL(resolve('index.html')).href);await until(async()=>{const s=await page.eval('({ready:!!window.__smearComputeReady,error:document.getElementById("failure")?.style.display==="block"?document.getElementById("failure").textContent:null})');if(s.error)throw Error(s.error);return s.ready;},{timeout:90000});await page.eval('__smear.manual(true)');
 const vec=a=>'vec3f('+a.map(v=>v.toFixed(9)).join(',')+')';const code='@group(0) @binding(13) var<storage,read_write> probe:array<vec4f>; @compute @workgroup_size(1) fn inspect(){'+cases.map((c,i)=>`probe[${i}]=vec4f(laboratoryLights(${vec(c.p)},${vec(c.n)},${vec(c.v)},vec3f(.05,.002,.006),${c.r},0),1);`).join('')+'}';
 const gpu=await page.eval(`(async()=>{const g=__smearGPU,d=g.device,m=d.createShaderModule({code:__smearComputeShaders.common+'\\n'+__smearComputeShaders.render+'\\n'+${JSON.stringify(code)}}),p=await d.createComputePipelineAsync({layout:'auto',compute:{module:m,entryPoint:'inspect'}}),out=g.buffer('explicit LTC integration',${cases.length*16}),read=g.buffer('explicit LTC read',${cases.length*16},GPUBufferUsage.COPY_DST|GPUBufferUsage.MAP_READ),bg=d.createBindGroup({layout:p.getBindGroupLayout(0),entries:[{binding:2,resource:{buffer:g.constantBuffer}},{binding:12,resource:g.ltcTexture.createView({dimension:'2d-array'})},{binding:13,resource:{buffer:out}}]}),e=d.createCommandEncoder(),pass=e.beginComputePass();pass.setPipeline(p);pass.setBindGroup(0,bg);pass.dispatchWorkgroups(1);pass.end();e.copyBufferToBuffer(out,0,read,0,read.size);d.queue.submit([e.finish()]);await read.mapAsync(GPUMapMode.READ);const a=Array.from(new Float32Array(read.getMappedRange().slice(0)));read.unmap();out.destroy();read.destroy();return a;})()`);
 receipt.raw=gpu;receipt.strength=await page.eval('({strength:__smearGPU.ltcStrength,tune:__smearGPU.lastMaterialTune,errors:__smearGPU.errors})');
 receipt.integrals=cases.map((c,i)=>{const actual=gpu.slice(i*4,i*4+3),expected=reference(c),relative=Math.hypot(...actual.map((v,k)=>v-expected[k]))/Math.max(.005,Math.hypot(...expected));assert(actual.every(Number.isFinite));assert(relative<.002,`LTC case ${i}: ${relative}`);return{...c,actual,expected,relative};});receipt.checks.push('GPU LTC matches independent 256x256 solid-angle quadrature within 0.2% for normal, grazing, clipped and ceiling-facing cases');
 await installBrushFlowFixture(page);await page.eval("__contactPlay.setup('drag')");await page.eval("__smear.grab(0,'Torso',[0,0,.125])");await page.eval('__contactPlay.advance(960);__smear.release();__wallTest.hide();__smear.view([-3.9,1.0,-5.2],[-3.5,2,-8])');
 for(const [name,strength]of [['off',0],['on',1]]){await page.eval(`__smearGPU.ltcStrength=${strength};__smear.render()`);await page.shot(resolve(out,'wall-'+name+'.png'));}
 await page.eval(`(()=>{const g=__smearGPU;for(let id=0;id<16;id++){const r=g.records[id],s=g.surfaces[id],a=new Uint32Array(r.filmWidth*r.filmHeight);for(let y=0;y<r.filmHeight;y++)for(let x=0;x<r.filmWidth;x++){const p=s.center.clone().addScaledVector(s.u,((x+.5)/r.filmWidth-.5)*s.w).addScaledVector(s.v,((y+.5)/r.filmHeight-.5)*s.h);const edge=1-(p.x*p.x/18+p.z*p.z/26);a[x+y*r.filmWidth]=Math.round(Math.max(0,Math.min(.7,edge*2))*(1+.035*Math.sin(p.x*17+p.z*11))*65536);}g.device.queue.writeBuffer(g.wetBuffer,(g.surfaces.length*3136+r.filmOffset)*4,a);}__smear.view([2,1.3,5],[0,0,-1]);})()`);
 for(const [name,strength]of [['off',0],['on',1]]){await page.eval(`__smearGPU.ltcStrength=${strength};__smear.render()`);await page.shot(resolve(out,'pool-'+name+'.png'));}
 receipt.images={};for(const subject of ['wall','pool']){const hashes=['off','on'].map(n=>createHash('sha256').update(fs.readFileSync(resolve(out,subject+'-'+n+'.png'))).digest('hex'));assert.notEqual(...hashes);receipt.images[subject]=hashes;}receipt.checks.push('Actual brushed wall liquid and floor film show distinct area-light reflections without simulation changes');
 receipt.errors=await page.eval('__smearGPU.errors');assert.deepEqual(receipt.errors,[]);assert.deepEqual(page.logs.filter(s=>/^EXCEPTION:|^error:/i.test(s)),[]);receipt.result='COMPLETE LTC integration checks';console.log(JSON.stringify({result:receipt.result,checks:receipt.checks,errors:receipt.integrals.map(i=>i.relative)},null,2));
}catch(e){receipt.result='FAIL';receipt.error=e.stack;console.error(e.stack);process.exitCode=1;}finally{receipt.logs=page.logs;fs.writeFileSync(resolve(out,'verification.json'),JSON.stringify(receipt,null,2));page.kill();}
