import fs from 'node:fs';import assert from 'node:assert/strict';import {resolve} from 'node:path';import {pathToFileURL} from 'node:url';import {spawnSync} from 'node:child_process';import {createHash} from 'node:crypto';import {launch,until,sleep} from './cdp.mjs';import {installImpactFixture} from './impact-fixture.mjs';
const out=resolve('tools/out/props-pass/recordings');fs.mkdirSync(out,{recursive:true});const r={at:new Date().toISOString(),buildSHA256:createHash('sha256').update(fs.readFileSync('index.html')).digest('hex'),clips:[]};
function encode(args){const p=spawnSync('ffmpeg',['-nostdin','-hide_banner','-loglevel','error','-y',...args],{encoding:'utf8',windowsHide:true,timeout:120000});assert.ifError(p.error);assert.equal(p.status,0,p.stderr);}
const page=await launch({port:9741,width:1600,height:1000,headless:true});r.profile=page.dir;r.pid=page.proc.pid;
try{
 await page.goto(pathToFileURL(resolve('index.html')).href+'?defaults=1');await until(()=>page.eval('!!window.__smearComputeReady'),{timeout:90000});await page.eval('__smear.manual(true)');await page.mouse('mousePressed',800,140);await page.mouse('mouseReleased',800,140);await installImpactFixture(page);
 for(const [name,seconds,caption]of [['crate',7,'WET CRATE / TWO BAT STRIKES / FINITE LIQUID RELEASE'],['barrels',9,'EXPLOSIVE BARRELS / CHAIN REACTION / GPU DISMEMBERMENT']]){
  await page.eval('__impactTest.setup({speed:0,pose:"body"})');
  if(name==='crate')await page.eval(`(async()=>{const g=__smearGPU,p=g.props[0].position;g.bodyCount=0;g.syncCounts();__smear.preset('default');__smear.view([p[0]+.2,1.68,p[2]+1.38],p);__smear.pointer(800,500);for(let i=0;i<4;i++){g.spill();g.submit(0);await g.device.queue.onSubmittedWorkDone();}__smear.tool(3);g.updateToolPresentation(0,{tool:3,panel:null,time:0,left:false,batAge:-1});})()`);
  else await page.eval(`(async()=>{const g=__smearGPU,d=g.device,T=g.THREE,b=g.buffer('explicit capture pose',g.bodyBuffer.size,GPUBufferUsage.COPY_DST|GPUBufferUsage.MAP_READ),e=d.createCommandEncoder();e.copyBufferToBuffer(g.bodyBuffer,0,b,0,b.size);d.queue.submit([e.finish()]);await b.mapAsync(GPUMapMode.READ);const a=new Float32Array(b.getMappedRange().slice(0));b.unmap();b.destroy();const hip=new T.Vector3(...a.slice(104,107));for(let i=0;i<15;i++){const p=new T.Vector3(...a.slice(i*104,i*104+3)).sub(hip).add(new T.Vector3(4.45,1.0,-6.55));a.set(p.toArray(),i*104);a.fill(0,i*104+8,i*104+16);}d.queue.writeBuffer(g.bodyBuffer,0,a);__smear.preset('default');__smear.tune({walking:false,recover:false});__smear.view([3.75,1.68,-3.65],g.props[3].position);__smear.pointer(800,500);__smear.tool(1);g.updateToolPresentation(0,{tool:1,panel:null,time:0,left:false});})()`);
  await page.eval(`(()=>{window.__chunks=[];window.__tap=__smear.compute.audioTap();window.__stream=new MediaStream([...__smearGPU.canvas.captureStream(30).getVideoTracks(),...__tap.stream.getAudioTracks()]);window.__recorder=new MediaRecorder(__stream,{mimeType:'video/webm;codecs=vp9,opus',videoBitsPerSecond:14000000,audioBitsPerSecond:192000});__recorder.ondataavailable=e=>{if(e.data.size)__chunks.push(e.data)};__recorder.start(1000);__smear.render();__smear.manual(false);})()`);
  await sleep(1000);
  if(name==='crate'){await page.mouse('mousePressed',800,500);await sleep(1150);await page.mouse('mouseReleased',800,500);await sleep(4850);}
  else{for(let i=0;i<3;i++){await page.mouse('mousePressed',800,500);await sleep(40);await page.mouse('mouseReleased',800,500);await sleep(170);}await sleep(7370);}
  await page.eval('__smear.manual(true)');const data=await page.eval(`new Promise(resolve=>{__recorder.onstop=()=>{const f=new FileReader();f.onload=()=>resolve(f.result.split(',')[1]);f.readAsDataURL(new Blob(__chunks,{type:'video/webm'}));__stream.getTracks().forEach(t=>t.stop());};__recorder.stop();})`);fs.writeFileSync(resolve(out,name+'.webm'),Buffer.from(data,'base64'));
  const props=await page.eval('__smear.props()'),state=await page.eval('__smear.state()');assert.deepEqual(state.errors,[]);assert(props[name==='crate'?0:3].broken);if(name==='barrels'){assert(props[4].broken);assert(state.parts.some(p=>p.severed));}r.clips.push({name,seconds,props,cuts:state.parts.filter(p=>p.severed).length,audio:await page.eval('__smear.compute.audio()')});
  encode(['-i',resolve(out,name+'.webm'),'-vf',`fps=30,tpad=stop_mode=clone:stop_duration=1,drawtext=font=Arial:text='${caption}':x=24:y=h-50:fontsize=24:fontcolor=white:box=1:boxcolor=black@0.7:boxborderw=8`,'-af','apad','-t',String(seconds),'-c:v','libx264','-preset','fast','-crf','18','-pix_fmt','yuv420p','-c:a','aac','-b:a','192k','-movflags','+faststart',resolve(out,name+'.mp4')]);encode(['-ss',name==='crate'?'2.0':'2.1','-i',resolve(out,name+'.mp4'),'-frames:v','1',resolve(out,name+'-review.png')]);console.log('Recorded '+name);
 }
 fs.writeFileSync(resolve(out,'clips.txt'),"file 'crate.mp4'\nfile 'barrels.mp4'\n");encode(['-f','concat','-safe','0','-i',resolve(out,'clips.txt'),'-c','copy','-movflags','+faststart',resolve(out,'smear-v34-crates-barrels.mp4')]);r.passed=true;console.log('COMPLETE V34 prop showcase');
}finally{page.kill();fs.writeFileSync(resolve(out,'capture.json'),JSON.stringify(r,null,2));}
