import fs from 'node:fs';import assert from 'node:assert/strict';import {resolve} from 'node:path';import {pathToFileURL} from 'node:url';import {createHash} from 'node:crypto';import {launch,until,sleep} from './cdp.mjs';import {installDestructionFixture} from './destruction-fixture.mjs';
const label=process.argv[2]||'round-01',out=resolve('tools/out/props-pass/'+label);fs.mkdirSync(out,{recursive:true});
const page=await launch({port:9740,width:1600,height:1000,headless:true}),r={at:new Date().toISOString(),browserProfile:page.dir,buildSHA256:createHash('sha256').update(fs.readFileSync('index.html')).digest('hex'),checks:[]};
const check=s=>{r.checks.push(s);console.log('PASS '+s);};
try{
 await page.goto(pathToFileURL(resolve('index.html')).href+'?defaults=1');await until(async()=>{const s=await page.eval('({ready:!!window.__smearComputeReady,error:window.__smearGPU?.errors})');if(s.error?.length)throw Error(s.error.join('\n'));return s.ready;},{timeout:90000});await page.eval('__smear.manual(true)');await page.mouse('mousePressed',800,140);await page.mouse('mouseReleased',800,140);await installDestructionFixture(page);
 await page.eval(`(()=>{const g=__smearGPU,d=g.device;window.__propsTest={
 async setup(id=0){__smear.manual(true);__smear.reset();__smear.preset('default');await __smear.step(0);g.bodyCount=0;g.syncCounts();g.clearDrops();__smear.clean();const p=g.props[id].position;__smear.view([p[0],p[1],p[2]+1.75],p);__smear.pointer(800,500);__smear.tool(1);await d.queue.onSubmittedWorkDone();},
 async shoot(n=1){for(let i=0;i<n;i++){g.shoot();g.submit(0);await d.queue.onSubmittedWorkDone();}},
 async counters(){const a=new Uint32Array(await __destructionFixture.read(g.workBuffer,0,256));return {mask:a[19],blasts:a[58],cuts:a[59],fragments:a[60]};},
 async debris(){const a=new Uint32Array(await __destructionFixture.read(g.workBuffer,(g.destructionBase+1440)*4,128*24*4));return Array.from({length:128},(_,i)=>a[i*24+23]).reduce((n,k)=>(n[k]=(n[k]||0)+1,n),{});}
 };})()`);
 r.initial=await page.eval('__smear.props()');assert.equal(r.initial.length,8);assert.equal(r.initial.filter(p=>p.active).length,6);assert.equal(r.initial.filter(p=>p.kind==='crate').length,4);assert.equal(r.initial.filter(p=>p.kind==='barrel').length,4);assert(r.initial.every(p=>!p.broken&&p.damage===0));
 r.mapping=await page.eval('__smearGPU.props.flatMap(p=>Object.values(p.faces).map(id=>{const s=__smearGPU.surfaces[id],r=__smearGPU.records[id];return {id,w:s.w,h:s.h,width:r.width,height:r.height};}))');assert.equal(r.mapping.length,48);assert(r.mapping.every(s=>Math.abs(s.width-s.w*160)<=.5&&Math.abs(s.height-s.h*160)<=.5));check('Six original props and two spare slots have 48 paint charts at the existing 160 texels/metre');
 await page.eval('__propsTest.setup(0)');await page.shot(resolve(out,'crate-intact.png'));await page.eval('__propsTest.shoot(2)');r.crateTwo=await page.eval('__smear.props()');assert(!r.crateTwo[0].broken&&r.crateTwo[0].damage>.7);assert((await page.eval('__smear.compute.paintHash(__smearGPU.props[0].faces.zp)')).painted>20);await page.eval('__propsTest.shoot(1)');r.crateThree=await page.eval('__smear.props()');assert(r.crateThree[0].broken);r.crateDebris=await page.eval('__propsTest.debris()');assert(r.crateDebris[3]>=16);assert.equal((await page.eval('__propsTest.counters()')).blasts,0);await page.eval('__destructionFixture.advance(25)');await page.shot(resolve(out,'crate-broken.png'));const wallBefore=await page.eval('__smear.compute.paintHash(16)');await page.eval('__propsTest.shoot(1)');const wallAfter=await page.eval('__smear.compute.paintHash(16)');assert(wallAfter.painted>wallBefore.painted+20);check('Three pistol hits splinter a crate into wood debris; subsequent shots pass through its former collider');
 await page.eval('__propsTest.setup(0)');await page.eval('(async()=>{__smearGPU.melee();__smearGPU.submit(0);await __smearGPU.device.queue.onSubmittedWorkDone();})()');assert(!(await page.eval('__smear.props()'))[0].broken);await page.eval('(async()=>{__smearGPU.melee();__smearGPU.submit(0);await __smearGPU.device.queue.onSubmittedWorkDone();})()');assert((await page.eval('__smear.props()'))[0].broken);check('Two in-range bat strikes break the crate through the normal GPU melee fan');
 await page.eval('__propsTest.setup(0)');await page.eval(`(async()=>{const g=__smearGPU,a=new Float32Array(await __destructionFixture.read(g.seedBuffer,0,g.seedBuffer.size));for(let i=0;i<180;i++){a[i*104+44]=0;a[i*104+75]=0;a[i*104+36]=0;}const p=g.props[0].position;a.set([p[0],p[1],p[2]+1.25],208);a.set([0,0,-18],216);a[252]=1;g.device.queue.writeBuffer(g.bodyBuffer,0,a);g.device.queue.writeBuffer(g.workBuffer,(g.destructionBase+16)*4,new Uint32Array([1]));g.bodyCount=15;g.syncCounts();__smear.tune({walking:false,recover:false});await __destructionFixture.advance(20);})()`);r.collisionDamage=(await page.eval('__smear.props()'))[0].damage;assert(r.collisionDamage>.2);check('A physical 18 m/s detached-head collision damages a crate without a weapon or scripted prop hit');
 await page.eval('__propsTest.setup(5)');await page.eval('(async()=>{for(let i=0;i<2;i++){__smearGPU.melee();__smearGPU.submit(0);await __smearGPU.device.queue.onSubmittedWorkDone();}})()');const boom=await page.eval('(async()=>new Uint32Array(await __destructionFixture.read(__smearGPU.workBuffer,38*4,4))[0])()');assert(boom&0x40000000);assert(!(boom&0x80000000));check('A bat-triggered barrel explosion wins over the simultaneous melee sound event');
 await page.eval('__propsTest.setup(3)');await page.eval('__smear.blast([5.65,.58,-9]);__smearGPU.submit(0)');await page.eval('__destructionFixture.advance(24)');assert(!(await page.eval('__smear.props()'))[3].broken);assert.equal((await page.eval('__smear.props()'))[3].damage,0);check('The room wall blocks blast damage to props behind it');
 await page.eval('__propsTest.setup(3)');await page.shot(resolve(out,'barrel-intact.png'));await page.eval('__propsTest.shoot(3)');const heldChain=await page.eval('__propsTest.counters()');await page.eval('(async()=>{for(let i=0;i<8;i++)__smearGPU.submit(0);await __smearGPU.device.queue.onSubmittedWorkDone();})()');assert.deepEqual(await page.eval('__propsTest.counters()'),heldChain);check('A pending barrel chain waits while simulation is paused');await page.eval('__destructionFixture.advance(48)');r.barrels=await page.eval('__smear.props()');r.chain=await page.eval('__propsTest.counters()');assert(r.barrels[3].broken&&r.barrels[4].broken);assert.equal(r.chain.blasts,2);assert(!r.barrels[5].broken);await page.shot(resolve(out,'barrel-chain.png'));await page.eval('__destructionFixture.advance(360)');assert.equal((await page.eval('__propsTest.counters()')).blasts,2);const dry=await page.eval('__destructionFixture.liquid()');assert.equal(dry.total,0);check('A shot barrel detonates its neighbour once each; distant props survive and dry blasts create no blood');
 await page.eval('__propsTest.setup(0)');await page.eval('(async()=>{__smearGPU.spill();__smearGPU.submit(2);await __smearGPU.device.queue.onSubmittedWorkDone();})()');const painted=await page.eval('__smear.compute.paintHash(__smearGPU.props[0].faces.zp)');assert(painted.painted>100);await page.shot(resolve(out,'crate-painted.png'));
 // Isolate a finite deposit on the actual crate face, with an empty body/drop supply.
 await page.eval(`(async()=>{const g=__smearGPU;g.clearDrops();const e=g.device.createCommandEncoder();e.clearBuffer(g.wetBuffer);g.device.queue.submit([e.finish()]);const r=g.records[g.props[0].faces.zp],a=new Uint32Array(r.filmWidth*r.filmHeight).fill(Math.round(.08*65536));g.device.queue.writeBuffer(g.wetBuffer,(g.surfaces.length*3136+r.filmOffset)*4,a);await g.device.queue.onSubmittedWorkDone();})()`);
 const before=await page.eval('__destructionFixture.liquid()');await page.eval('(async()=>{await __propsTest.shoot(3);await __destructionFixture.advance(120);})()');const after=await page.eval('__destructionFixture.liquid()');r.liquid={before:before.total,after:after.total,airborne:after.airborne};assert(Math.abs(after.total-before.total)<.001);const remaining=await page.eval(`(async()=>{const g=__smearGPU,r=g.records[g.props[0].faces.zp],a=new Uint32Array(await __destructionFixture.read(g.wetBuffer,(g.surfaces.length*3136+r.filmOffset)*4,r.filmWidth*r.filmHeight*4));return a.reduce((a,b)=>a+b,0);})()`);assert.equal(remaining,0);check('Native Spill paints the crate; breaking a wet face releases its finite liquid without a floating pool or duplication');
 await page.eval('__propsTest.setup(0)');const walk=`(async()=>{const p=__smearGPU.props[0].position;__smear.view([p[0],1.68,p[2]+1.5],[p[0],1.68,p[2]]);__smear.key('KeyW',true);for(let i=0;i<65;i++){__smear.playerMove(1/60,1);__smearGPU.submit(2);await __smearGPU.device.queue.onSubmittedWorkDone();await new Promise(r=>setTimeout(r,1));}__smear.key('KeyW',false);})()`;await page.eval(walk);const blocked=(await page.eval('__smear.state()')).player.p;await page.eval('__propsTest.setup(0)');await page.eval('__propsTest.shoot(3)');await page.eval('__smear.manual(false)');await sleep(450);await page.eval('__smear.manual(true)');assert(await page.eval('__smearGPU.props[0].box.broken'));await page.eval(walk);const open=(await page.eval('__smear.state()')).player.p;r.walk={blocked,open};assert(blocked[2]>-1.1&&open[2]<-2.1);check('Player collision blocks an intact crate and opens after its asynchronous destroyed flag arrives');
 await page.eval('__smear.reset();__smear.step(0)');assert((await page.eval('__smear.props()')).every(p=>!p.broken&&p.damage===0));assert(await page.eval('__smearGPU.props.every((p,i)=>i>=6||!p.box.broken)'));check('Reset restores prop health, geometry, collision and barrel fuel');
 const final=await page.eval('__smear.state()');assert.deepEqual(final.errors,[]);assert.equal(final.normalPaintReadbacks,0);r.logs=page.logs;assert(!page.logs.some(s=>/^error:|^EXCEPTION:/.test(s)));r.passed=true;console.log('COMPLETE '+r.checks.length+' prop checks passed');
}catch(e){r.error=e.stack;console.error(e);process.exitCode=1;}finally{fs.writeFileSync(resolve(out,'receipt.json'),JSON.stringify(r,null,2));page.kill();}
