import fs from 'node:fs';import assert from 'node:assert/strict';import {resolve} from 'node:path';import {pathToFileURL} from 'node:url';import {createHash} from 'node:crypto';
import {launch,until,sleep} from './cdp.mjs';import {installImpactFixture} from './impact-fixture.mjs';import {installDestructionFixture} from './destruction-fixture.mjs';import {installUtilityFixture} from './utility-fixture.mjs';
const out=resolve('tools/out/arsenal-v40-pass/'+(process.argv[2]||'current'));fs.mkdirSync(out,{recursive:true});
const receipt={at:new Date().toISOString(),sha256:createHash('sha256').update(fs.readFileSync('index.html')).digest('hex'),checks:[]};let page;
const evaluate=code=>page.eval('(async()=>{'+code+'})()');
const pass=s=>{receipt.checks.push(s);console.log('PASS '+s);};
try{
 page=await launch({port:9784,width:1600,height:1000,headless:true});receipt.profile=page.dir;await page.goto(process.env.SMEAR_TEST_URL||pathToFileURL(resolve('index.html')).href+'?defaults=1');
 await until(async()=>{const s=await page.eval('({ready:!!window.__smearComputeReady,error:document.getElementById("failure")?.style.display==="block"?document.getElementById("failure").textContent:null})');if(s.error)throw Error(s.error);return s.ready;},{timeout:90000});
 await page.eval('__smear.manual(true)');await page.mouse('mousePressed',800,120);await page.mouse('mouseReleased',800,120);await installImpactFixture(page);await installDestructionFixture(page);await installUtilityFixture(page);
 await evaluate(`window.__newArsenal={async state(){const g=__smearGPU,a=await __destructionFixture.read(g.workBuffer,0,g.workBuffer.size),w=new Uint32Array(a),f=new Float32Array(a),d=new Float32Array(await __destructionFixture.read(g.particleBuffer,0,g.particleBuffer.size));let airborne=0;for(let i=0;i<900;i++)if(w[64+i])airborne+=d[i*16+12];return{meta:Array.from(w.slice(g.destructionMeta,g.destructionMeta+32)),contacts:w[60],particles:w[9],airborne,ord:Array.from({length:128},(_,i)=>{const s=g.destructionBase+1440+i*24;return{kind:w[s+23],age:f[s+7],p:Array.from(f.slice(s,s+3)),v:Array.from(f.slice(s+4,s+7))}})}},async aim(part=2){const s=await __smear.state(),p=s.parts[part].p;__smear.view([p[0],p[1],p[2]+2.2],p);__smear.pointer(800,500);},async fire(action){__smearGPU[action]();__smearGPU.submit(0);await __smearGPU.device.queue.onSubmittedWorkDone();}}`);
 const budget=s=>s.parts.reduce((n,p)=>n+p.reserve*.1+p.wet*.02,0);
 for(const full of [false,true]){
  await page.eval(`__impactTest.setup({speed:0,full:${full}})`);await evaluate('await __newArsenal.aim();__smear.tool(12)');const before=await page.eval('__smear.state()');await evaluate('await __newArsenal.fire("shotgun")');const after=await page.eval('__smear.state()'),w=await page.eval('__newArsenal.state()');
  assert.equal(w.meta[19],1);assert(w.meta[20]>=5);assert(after.parts.some(p=>p.severed));assert(budget(after)<budget(before));assert(Math.abs(budget(before)-budget(after)-w.airborne)<2e-6);assert.equal(w.particles,full?900:w.meta[20]*7);
  receipt[full?'fullPool':'shotgun']={pellets:w.meta[20],cuts:after.parts.filter(p=>p.severed).length,bloodBefore:budget(before),bloodAfter:budget(after),airborne:w.airborne};
 }
 pass('Twelve-pellet shotgun severs a close hit and conserves finite blood, including a saturated 900-drop pool');
 await evaluate('await __impactTest.setup({speed:0});__smear.view([-3.5,2,-8.6],[-3.5,2,-6.5]);__smear.pointer(800,500);await __newArsenal.fire("shotgun")');assert.equal((await page.eval('__newArsenal.state()')).meta[20],0);assert((await page.eval('__smear.state()')).parts.every(p=>p.reserve===9));pass('A solid room wall blocks every shotgun pellet and protects the buddy behind it');
 await evaluate('await __impactTest.setup({speed:0});await __newArsenal.aim();__smear.tool(13);await __newArsenal.fire("saw");await __impactTest.advance(15)');
 let w=await page.eval('__newArsenal.state()'),s=await page.eval('__smear.state()');assert(w.meta[23]>0);assert(s.parts.some(p=>p.severed));assert(w.ord.some(p=>p.kind===7&&Math.hypot(...p.v)>10));receipt.sawCut={hits:w.meta[23],cuts:s.parts.filter(p=>p.severed).length};await page.shot(resolve(out,'blade-cut.png'));pass('A sawblade sweeps into a buddy, cuts a joint and continues flying after contact');
 await evaluate('await __utilityTest.reset();__smear.view([-3,2,-5],[-3,2,-8]);__smear.pointer(800,500);__smear.tool(13);await __newArsenal.fire("saw");await __utilityTest.advance(45)');w=await page.eval('__newArsenal.state()');assert(w.meta[22]>0);let blade=w.ord.find(p=>p.kind===7);assert(blade&&blade.v[2]>10);assert.equal(w.meta[0],0);receipt.ricochet=blade;await page.shot(resolve(out,'blade-ricochet.png'));await evaluate('await __utilityTest.advance(720)');assert(!(await page.eval('__newArsenal.state()')).ord.some(p=>p.kind===7));pass('Wall contact reflects a live steel blade without an explosion; it expires after six seconds');
 await evaluate('await __utilityTest.reset();await __utilityTest.patch({point:[-3,0,5],radius:.85,mass:.3});__smear.view([-3,.65,6],[-3,0,5]);__smear.pointer(800,500)');const wetBefore=await page.eval('__utilityTest.state()');await evaluate('await __newArsenal.fire("saw");await __utilityTest.advance(20)');const wetAfter=await page.eval('__utilityTest.state()');w=await page.eval('__newArsenal.state()');assert(w.contacts>0);assert(w.ord.some(p=>p.kind===2));assert(Math.abs(wetBefore.total-wetAfter.total)<wetBefore.total*.025);receipt.wetBlade={contacts:w.contacts,before:wetBefore.total,after:wetAfter.total,sparks:w.ord.filter(p=>p.kind===2).length};pass('Ricocheting blades move finite floor blood and shed real metal sparks on contact');
 await evaluate('await __utilityTest.reset();__smear.view([-3,3,5],[-3,3,-7]);__smear.pointer(800,500);for(let i=0;i<12;i++)await __newArsenal.fire("saw")');w=await page.eval('__newArsenal.state()');assert.equal(w.ord.filter(p=>p.kind===7).length,8);assert.equal(w.meta[21],8);assert(w.ord.slice(8).every(p=>p.kind===0));pass('Sawblades share the eight projectile slots without consuming fragment slots or overwriting active projectiles');
 await evaluate('await __utilityTest.reset();await __utilityTest.pose(0,[-3,.55,4]);__smear.view([-3,.55,6],[-3,.55,4]);__smear.pointer(800,500);await __newArsenal.fire("shotgun");await __utilityTest.advance(1)');assert((await page.eval('__smear.props()'))[0].broken);assert.equal((await page.eval('__newArsenal.state()')).ord.filter(p=>p.kind===5).length,6);pass('Close shotgun impact breaks a crate into six persistent boards plus small chips');
 await evaluate('__smear.reset();await __smear.step(0);__smear.tool(0);__smear.view([0,2.2,5],[0,1,-3]);__smear.render()');s=await page.eval('__smear.state()');assert.deepEqual([...new Set(s.parts.map(p=>p.variant))],['Classic','Runner','Heavy']);
 receipt.variants=await page.eval('__smearGPU.sourceBodies.filter((b,i)=>i%15===0).slice(0,3).map(b=>({half:b.half.toArray(),mass:1/b.im,bound:b.bound}))');assert(receipt.variants[1].mass<receipt.variants[0].mass&&receipt.variants[2].mass>receipt.variants[0].mass);assert(receipt.variants[1].half[0]<receipt.variants[0].half[0]&&receipt.variants[2].half[0]>receipt.variants[0].half[0]);await page.eval('__smear.step(600)');s=await page.eval('__smear.state()');assert(s.maxJoint<.15);assert(s.parts.every(p=>[...p.p,...p.q,...p.v].every(Number.isFinite)));await page.shot(resolve(out,'three-builds.png'));pass('Classic, Runner and Heavy have distinct collision widths and masses and remain finite through five seconds of simulation');
 receipt.caps=await page.eval(`(()=>{const a=[];__smearGPU.scene.traverse(o=>{if(o.userData.severCap){const p=o.geometry.attributes.position;let low=1,high=-1;for(let i=0;i<p.count;i++){low=Math.min(low,p.getY(i));high=Math.max(high,p.getY(i));}a.push({type:o.geometry.type,low,high,vertices:p.count,child:o.userData.severCap.child,radius:o.scale.x});}});return a;})()`);assert.equal(receipt.caps.length,336);assert(receipt.caps.every(c=>c.type==='BufferGeometry'&&c.low<-.3&&c.high<.01));assert(receipt.caps.filter(c=>c.child%15===2).every(c=>c.radius<.062));pass('All 336 exposed sockets use irregular recessed surfaces without cylindrical cap geometry');
 for(const [tool,name]of [[12,'shotgun'],[13,'sawblade']]){await evaluate(`__smear.tool(${tool});__smear.view([0,1.68,5],[0,1.5,-3]);__smearGPU.updateToolPresentation(0,{tool:${tool},panel:null,time:0,left:false});__smear.render()`);await sleep(80);await page.shot(resolve(out,name+'-grip.png'));}
 await evaluate('__smear.controls.mode("cursor");__smear.manual(false)');const tap=async(code,key)=>{for(const type of ['keyDown','keyUp'])await page.call('Input.dispatchKeyEvent',{type,code,key});};
 await tap('KeyZ','z');assert.equal((await page.eval('__smear.controls.state()')).tool,12);let start=(await page.eval('__newArsenal.state()')).meta[19];await page.mouse('mousePressed',800,500);await sleep(1600);await page.mouse('mouseReleased',800,500);let fired=(await page.eval('__newArsenal.state()')).meta[19]-start;assert(fired>=2&&fired<=3);
 await tap('KeyJ','j');assert.equal((await page.eval('__smear.controls.state()')).tool,13);start=(await page.eval('__newArsenal.state()')).meta[21];await page.mouse('mousePressed',800,500);await sleep(1150);await page.eval('__smear.controls.pause()');await page.mouse('mouseReleased',800,500);fired=(await page.eval('__newArsenal.state()')).meta[21]-start;assert(fired>=2&&fired<=3);let paused=(await page.eval('__newArsenal.state()')).meta[21];await sleep(650);assert.equal((await page.eval('__newArsenal.state()')).meta[21],paused);pass('Native Z/J shortcuts select both weapons; held fire respects cadence and pause clears firing');
 receipt.audio=await page.eval('__smear.compute.audio()');assert(receipt.audio.enabled&&receipt.audio.state==='running');receipt.errors=page.logs.filter(x=>/^EXCEPTION:|^error:/i.test(x));assert.deepEqual(receipt.errors,[]);receipt.result='COMPLETE '+receipt.checks.length+' new arsenal and dummy checks';console.log(receipt.result);
}catch(e){receipt.result='FAIL';receipt.error=e.stack;console.error(e.stack);process.exitCode=1;}finally{if(page){receipt.logs=page.logs;page.kill();}fs.writeFileSync(resolve(out,'verification.json'),JSON.stringify(receipt,null,2));}
