import fs from 'node:fs';import assert from 'node:assert/strict';import {resolve} from 'node:path';import {pathToFileURL} from 'node:url';import {spawnSync} from 'node:child_process';import {createHash} from 'node:crypto';
import {launch,until,sleep} from './cdp.mjs';import {installUtilityFixture} from './utility-fixture.mjs';
const out=resolve('tools/out/arsenal-v40-pass/recordings');fs.mkdirSync(out,{recursive:true});const only=process.argv[2];const receipt=only&&fs.existsSync(resolve(out,'capture.json'))?JSON.parse(fs.readFileSync(resolve(out,'capture.json'))):{at:new Date().toISOString(),clips:[]};if(only)receipt.clips=receipt.clips.filter(c=>!c.name.endsWith('-'+only));
const encode=args=>{const r=spawnSync('ffmpeg',['-nostdin','-hide_banner','-loglevel','error','-y',...args],{encoding:'utf8',windowsHide:true,timeout:120000});assert.ifError(r.error);assert.equal(r.status,0,r.stderr);};
for(const [label,scene]of [['before','variants'],['after','variants'],['before','socket'],['after','socket'],['after','shotgun'],['after','sawblade']].filter(([,s])=>!only||s===only)){
 const file=label==='before'?'tools/out/arsenal-v40-pass/before/index.html':'index.html',page=await launch({port:9796,width:1600,height:1000,headless:true}),name=label+'-'+scene,clip={name,profile:page.dir,buildSHA256:createHash('sha256').update(fs.readFileSync(file)).digest('hex')};receipt.clips.push(clip);
 try{
  await page.goto(pathToFileURL(resolve(file)).href+'?defaults=1');await until(()=>page.eval('!!window.__smearComputeReady'),{timeout:90000});await installUtilityFixture(page);await page.eval('__utilityTest.reset()');await page.mouse('mousePressed',800,120);await page.mouse('mouseReleased',800,120);await page.eval('__smear.release(false);__smear.fly()');
  // Same articulated rest poses in both versions; GPU data changes are fixture-only.
  await page.eval(`(async()=>{const g=__smearGPU,a=new Float32Array(await __destructionFixture.read(g.seedBuffer,0,g.seedBuffer.size));for(let doll=0;doll<3;doll++)for(let k=0;k<15;k++){const i=doll*15+k,o=i*104,b=g.sourceBodies[i],p=b.restP.clone();p.x+=(doll-1)*1.05-3.5;p.z+=${scene==='variants'?6:4};const q=b.restQ.clone();a.set(p.toArray(),o);a.set(q.toArray(),o+4);a.fill(0,o+8,o+16);a.set([0,0,0,9],o+32);a.set([0,0,0,100],o+36);a[o+44]=1;a[o+75]=0;}g.device.queue.writeBuffer(g.bodyBuffer,0,a);g.bodyCount=45;g.syncCounts();__smear.tool(0);__smear.view([-2,2,7.9],[-3.5,1,6]);__smear.render();})()`);
  if(scene==='socket')await page.eval(`(async()=>{const g=__smearGPU,a=new Float32Array(await __destructionFixture.read(g.bodyBuffer,0,g.bodyBuffer.size));for(let k=0;k<15;k++)a[k*104]+=4.55;for(let k=15;k<45;k++)a[k*104]+=25;const o=2*104;a[o]+=.36;a[o+1]+=.10;a[o+2]+=.12;g.device.queue.writeBuffer(g.bodyBuffer,0,a);const f=new Uint32Array(180*8);f[2*8]=1;f[2*8+5]=1<<2;f[5]=1<<2;g.device.queue.writeBuffer(g.workBuffer,g.destructionBase*4,f);__smear.view([.75,2.26,4.85],[.03,1.63,4]);__smear.render();})()`);
  if(scene==='shotgun'||scene==='sawblade'){
   await page.eval('__utilityTest.patch({point:[-3.5,0,4],radius:1.4,mass:.24})');await page.eval(`__smear.tool(${scene==='shotgun'?12:13});__smear.view([-3.5,1.68,7.1],[-3.5,1.45,4]);__smear.pointer(800,500)`);
   if(scene==='shotgun')await page.eval('__utilityTest.pose(0,[-1.9,.55,4])');
   await page.eval('__smear.manual(false)');
  }
  await page.eval(`(()=>{window.__chunks=[];const tap=__smear.compute.audioTap();window.__stream=new MediaStream([...__smearGPU.canvas.captureStream(30).getVideoTracks(),...tap.stream.getAudioTracks()]);window.__recorder=new MediaRecorder(__stream,{mimeType:'video/webm;codecs=vp9,opus',videoBitsPerSecond:14000000});__recorder.ondataavailable=e=>{if(e.data.size)__chunks.push(e.data)};__recorder.start(1000);})()`);
  await sleep(500);await page.shot(resolve(out,name+'-start.png'));
  if(scene==='shotgun'||scene==='sawblade'){await page.mouse('mousePressed',800,500);await sleep(scene==='shotgun'?750:550);await page.mouse('mouseReleased',800,500);await sleep(650);await page.eval(scene==='shotgun'?'__smear.view([-3.5,1.68,7.1],[-1.9,.55,4])':'__smear.view([-3.5,1.68,7.1],[-6.3,.18,3.5])');await page.mouse('mousePressed',800,500);await sleep(1000);await page.mouse('mouseReleased',800,500);await sleep(1300);}
  else for(let frame=0;frame<90;frame++){const t=frame/90;await page.eval(scene==='socket'?`__smear.view([${.75-t*.5},2.26,4.85],[.03,1.63,4]);__smear.render()`:`__smear.view([${-2-t*2},2,7.9],[-3.5,1,6]);__smear.render()`);await sleep(30);}
  await page.shot(resolve(out,name+'-end.png'));await page.eval('__smear.manual(true)');
  const data=await page.eval(`new Promise(resolve=>{__recorder.onstop=()=>{const f=new FileReader();f.onload=()=>resolve(f.result.split(',')[1]);f.readAsDataURL(new Blob(__chunks,{type:'video/webm'}));__stream.getTracks().forEach(t=>t.stop());};__recorder.stop();})`);fs.writeFileSync(resolve(out,name+'.webm'),Buffer.from(data,'base64'));encode(['-i',resolve(out,name+'.webm'),'-vf','fps=30','-c:v','libx264','-preset','fast','-crf','18','-pix_fmt','yuv420p','-c:a','aac','-b:a','192k','-movflags','+faststart',resolve(out,name+'.mp4')]);
  clip.audio=await page.eval('__smear.compute.audio()');assert(clip.audio.enabled&&clip.audio.state==='running');assert.deepEqual(page.logs.filter(s=>/^EXCEPTION:|^error:/i.test(s)),[]);console.log('Captured '+name);
 }finally{page.kill();fs.writeFileSync(resolve(out,'capture.json'),JSON.stringify(receipt,null,2));}
}
for(const scene of ['variants','socket'].filter(s=>!only||s===only))encode(['-i',resolve(out,'before-'+scene+'.mp4'),'-i',resolve(out,'after-'+scene+'.mp4'),'-filter_complex',"[0:v]scale=800:500,setpts=PTS-STARTPTS,drawtext=font=Arial:text='V39':x=18:y=18:fontsize=22:fontcolor=white:box=1:boxcolor=black@0.7[a];[1:v]scale=800:500,setpts=PTS-STARTPTS,drawtext=font=Arial:text='V40':x=18:y=18:fontsize=22:fontcolor=white:box=1:boxcolor=black@0.7[b];[a][b]hstack=inputs=2:shortest=1[v];[0:a]pan=stereo|c0=c0|c1=0*c0[al];[1:a]pan=stereo|c0=0*c0|c1=c0[ar];[al][ar]amix=inputs=2:normalize=0[a]",'-map','[v]','-map','[a]','-shortest','-c:v','libx264','-preset','fast','-crf','18','-pix_fmt','yuv420p','-c:a','aac','-movflags','+faststart',resolve(out,'compare-'+scene+'.mp4')]);
receipt.passed=true;fs.writeFileSync(resolve(out,'capture.json'),JSON.stringify(receipt,null,2));console.log('COMPLETE V39/V40 comparisons and new weapon gameplay captures');
