import fs from 'node:fs';import assert from 'node:assert/strict';import {resolve} from 'node:path';import {pathToFileURL} from 'node:url';import {spawnSync} from 'node:child_process';import {createHash} from 'node:crypto';import {launch,until,sleep} from './cdp.mjs';
const out=resolve('tools/out/toybox-pass/recordings');fs.mkdirSync(out,{recursive:true});const receipt={at:new Date().toISOString(),clips:[]};
function encode(args){const p=spawnSync('ffmpeg',['-nostdin','-hide_banner','-loglevel','error','-y',...args],{encoding:'utf8',windowsHide:true,timeout:120000});assert.ifError(p.error);assert.equal(p.status,0,p.stderr);}
async function start(page){await page.eval(`(()=>{window.__chunks=[];const tap=__smear.compute.audioTap();window.__stream=new MediaStream([...__smearGPU.canvas.captureStream(30).getVideoTracks(),...tap.stream.getAudioTracks()]);window.__recorder=new MediaRecorder(__stream,{mimeType:'video/webm;codecs=vp9,opus',videoBitsPerSecond:14000000,audioBitsPerSecond:192000});__recorder.ondataavailable=e=>{if(e.data.size)__chunks.push(e.data)};__recorder.start(1000);__smear.manual(false);})()`);}
async function finish(page,name,title){await page.eval('__smear.manual(true)');const data=await page.eval(`new Promise(resolve=>{__recorder.onstop=()=>{const f=new FileReader();f.onload=()=>resolve(f.result.split(',')[1]);f.readAsDataURL(new Blob(__chunks,{type:'video/webm'}));__stream.getTracks().forEach(t=>t.stop());};__recorder.stop();})`);fs.writeFileSync(resolve(out,name+'.webm'),Buffer.from(data,'base64'));encode(['-i',resolve(out,name+'.webm'),'-vf',`fps=30,drawtext=font=Arial:text='${title}':x=24:y=h-50:fontsize=25:fontcolor=white:box=1:boxcolor=black@0.7:boxborderw=8`,'-c:v','libx264','-preset','fast','-crf','18','-pix_fmt','yuv420p','-c:a','aac','-b:a','192k','-movflags','+faststart',resolve(out,name+'.mp4')]);}
for(const [name,path,version]of [['before','tools/out/toybox-pass/before/index.html','V35'],['after','index.html','V36'],['chain','index.html','V36']]){
 const page=await launch({port:9761,width:1600,height:1000,headless:true});const clip={name,version,profile:page.dir,buildSHA256:createHash('sha256').update(fs.readFileSync(path)).digest('hex')};receipt.clips.push(clip);
 const tap=async code=>{for(const type of ['keyDown','keyUp'])await page.call('Input.dispatchKeyEvent',{type,code,key:code.at(-1)});};
 const click=async()=>{await page.mouse('mousePressed',800,500);await sleep(35);await page.mouse('mouseReleased',800,500);};
 try{
  await page.goto(pathToFileURL(resolve(path)).href+'?defaults=1');await until(()=>page.eval('!!window.__smearComputeReady'),{timeout:90000});await page.eval('__smear.controls.mode("cursor");__smear.manual(true)');await page.mouse('mousePressed',800,140);await page.mouse('mouseReleased',800,140);await page.eval('__smear.reset();__smear.preset("default");__smear.step(0)');await tap('KeyF');
  if(name!=='chain'){
   await page.eval('__smear.view([-6.45,2.2,1.8],[-6.45,.65,-1.8]);__smear.pointer(800,500);__smear.tool(2)');await start(page);await page.mouse('mousePressed',800,500);await sleep(380);await page.mouse('mouseReleased',800,500);await sleep(500);await page.eval('__smear.tool(0)');await page.mouse('mousePressed',800,500);await sleep(200);clip.picked=await page.eval('__smearGPU.input().held');assert.equal(clip.picked,name==='after');
   for(let i=0;i<55;i++){await page.mouse('mouseMoved',800+Math.sin(i/55*Math.PI)*240,500-Math.sin(i/55*Math.PI)*170);if(i===12)await page.call('Input.dispatchKeyEvent',{type:'keyDown',code:'KeyE',key:'e'});if(i===40)await page.call('Input.dispatchKeyEvent',{type:'keyUp',code:'KeyE',key:'e'});await sleep(30);}
   await page.shot(resolve(out,name+'-held.png'));for(let i=1;i<=9;i++){await page.mouse('mouseMoved',800+i*29,500-i*8);await sleep(18);}await page.mouse('mouseReleased',1061,428);await sleep(600);clip.afterThrow=await page.eval('__smear.props()');await page.eval('__smear.view([-1.8,3.8,5],[-4.5,.7,-1.8])');await sleep(3300);await page.shot(resolve(out,name+'-aftermath.png'));await finish(page,name,version+' / '+(name==='before'?'STATIC BREAKABLES':'GRAB / TWIST / THROW / CARRY WET PAINT'));
  }else{
   // Free an original barrel slot before filming. Placement and firing below
   // use the same player commands and native input as the game.
   await page.eval('__smearGPU.removeToy(3)');await page.eval('__smear.view([-3,2.6,7],[-3,0,5]);__smear.pointer(800,500);__smear.tool(0)');await start(page);
   for(const x of [-3,-1.8]){await page.eval('__smear.toybox.place(2);__smear.view(['+x+',2.6,7],['+x+',0,5]);__smear.pointer(800,500)');await sleep(900);await click();await sleep(650);assert.equal((await page.eval('__smear.toybox.state()')).placement,null);}
   clip.arranged=await page.eval('__smear.props()');await page.eval('__smear.view([-3.1,2.4,7.4],[-3,.6,5]);__smear.pointer(800,500);__smear.tool(2)');await page.mouse('mousePressed',800,500);await sleep(360);await page.mouse('mouseReleased',800,500);await page.eval('__smear.tool(1)');await sleep(600);await page.shot(resolve(out,'chain-ready.png'));for(let i=0;i<3;i++){await click();await sleep(200);}await sleep(3200);clip.aftermath=await page.eval('__smear.props()');assert(clip.aftermath[3].broken&&clip.aftermath[7].broken);await page.shot(resolve(out,'chain-aftermath.png'));await finish(page,name,'V36 / PLACE YOUR OWN BARREL CHAIN');
  }
  clip.audio=await page.eval('__smear.compute.audio()');assert(clip.audio.enabled&&clip.audio.state==='running');assert.deepEqual((await page.eval('__smear.state()')).errors,[]);assert(!page.logs.some(s=>/^error:|^EXCEPTION:/.test(s)));console.log('Recorded '+name);
 }finally{clip.logs=page.logs;page.kill();fs.writeFileSync(resolve(out,'capture.json'),JSON.stringify(receipt,null,2));}
}
encode(['-i',resolve(out,'before.mp4'),'-i',resolve(out,'after.mp4'),'-filter_complex','[0:v]scale=960:600,setpts=PTS-STARTPTS[a];[1:v]scale=960:600,setpts=PTS-STARTPTS[b];[a][b]hstack=inputs=2:shortest=1[v]','-map','[v]','-map','1:a','-shortest','-c:v','libx264','-preset','fast','-crf','18','-pix_fmt','yuv420p','-c:a','aac','-b:a','192k','-movflags','+faststart',resolve(out,'smear-v35-v36-toybox.mp4')]);
receipt.passed=true;fs.writeFileSync(resolve(out,'capture.json'),JSON.stringify(receipt,null,2));console.log('COMPLETE toybox MP4 comparison and barrel-chain showcase');
