import fs from 'node:fs';import assert from 'node:assert/strict';import {resolve} from 'node:path';import {pathToFileURL} from 'node:url';import {createHash} from 'node:crypto';
import {launch,until,sleep} from './cdp.mjs';import {aimMachineSwitch,useMachineSwitch} from './machine-input.mjs';import {installUtilityFixture} from './utility-fixture.mjs';import {installJunkFixture} from './junk-fixture.mjs';import {installBatFixture} from './bat-fixture.mjs';
const out=resolve('tools/out/ui-v44-pass/final');fs.mkdirSync(out,{recursive:true});let page;const r={at:new Date().toISOString(),sha256:createHash('sha256').update(fs.readFileSync('index.html')).digest('hex'),checks:[]};
const check=s=>{r.checks.push(s);console.log('PASS '+s);};
const tap=async code=>{for(const type of ['keyDown','keyUp'])await page.call('Input.dispatchKeyEvent',{type,code,key:({Escape:'Escape',Tab:'Tab'})[code]||code.replace(/^Key|^Digit/,''),windowsVirtualKeyCode:({Escape:27,Tab:9})[code]||code.at(-1).charCodeAt(0)});};
const click=async selector=>{const p=await page.eval(`(()=>{const b=document.querySelector(${JSON.stringify(selector)});b.scrollIntoView({block:'center'});const r=b.getBoundingClientRect();return{x:r.x+r.width/2,y:r.y+r.height/2};})()`);await page.mouse('mousePressed',p.x,p.y);await page.mouse('mouseReleased',p.x,p.y);};
const state=()=>page.eval('__smear.controls.state()');
try{
 page=await launch({port:9798,width:1600,height:1000,headless:true});r.profile=page.dir;await page.goto(process.env.SMEAR_TEST_URL||pathToFileURL(resolve('index.html')).href+'?defaults=1');await until(async()=>{if(page.logs.some(s=>/^EXCEPTION:/.test(s)))throw Error(page.logs.join('\n'));return page.eval('!!window.__smearComputeReady');},{timeout:90000});
 await page.shot(resolve(out,'menu.png'));await click('#play-resume');await until(async()=>(await state()).locked,{timeout:5000});await sleep(200);assert.deepEqual(await page.eval('__smear.ui()'),[]);assert.equal(await page.eval('document.querySelectorAll("#machine-start,#cursor-return,#time-status").length'),0);await page.shot(resolve(out,'quiet-room.png'));check('Gameplay has no canvas action buttons or floating machine, cursor or speed buttons');
 for(let n=0;n<3;n++){await tap('KeyB');await until(async()=>!(await state()).locked,{timeout:5000});assert.equal(await page.eval('getComputedStyle(document.getElementById("play-menu")).display'),'none');assert((await state()).paused);if(n===0){await page.shot(resolve(out,'toybox.png'));await click('[data-category="room"]');await click('#toy-add');assert((await page.eval('__smear.buddy.state()')).placement);await tap('Escape');}else await tap(n===1?'Escape':'KeyB');assert.equal((await state()).phase,'cursor');assert(!(await state()).paused);await tap('Tab');await until(async()=>(await state()).locked,{timeout:5000});}check('B and Escape close the Toybox into free cursor; Tab captures deliberately, and Add buddy uses an unobstructed placement preview');
 await tap('Escape');await until(async()=>!(await state()).locked);await click('#play-help');assert(await page.eval('!document.getElementById("play-help-content").hidden'));await click('#play-tune');await until(()=>page.eval('__smear.ui().some(b=>b.label==="Close")'));const close=await page.eval('__smear.ui().find(b=>b.label==="Close")');await page.mouse('mousePressed',close.x+20,close.y+12);await page.mouse('mouseReleased',close.x+20,close.y+12);assert((await state()).paused);assert.equal(await page.eval('getComputedStyle(document.getElementById("play-menu")).display'),'flex');await click('#play-toys');await click('[data-category="tools"]');assert.equal(await page.eval('document.querySelectorAll("[data-tool]").length'),14);await click('#toy-search');await page.call('Input.insertText',{text:'barrel'});assert(await page.eval(`!document.querySelector('[data-kind="2"]').hidden`));await tap('Escape');await tap('Tab');await until(async()=>(await state()).locked);check('Settings return to pause, all fourteen tools are accessible, and search spans categories without stealing hotkeys');
 const before=(await state()).tool;await page.call('Input.dispatchMouseEvent',{type:'mouseWheel',x:800,y:500,deltaY:120,deltaX:0});assert.equal((await state()).tool,(before+1)%14);await tap('KeyT');await sleep(100);assert(await page.eval('document.getElementById("play-state").textContent.includes("0.25")'));await tap('KeyT');await tap('Escape');await until(async()=>!(await state()).locked);check('Wheel changes tools and slow motion has a compact explicit status');
 await page.eval('__smear.manual(true)');await installUtilityFixture(page);await installBatFixture(page);await installJunkFixture(page);
 r.machines=[];for(const [name,id]of [['crusher',18],['glass',22],['pinball',23]]){
  await page.eval('__smear.utility.demo('+JSON.stringify(name)+');__smear.manual(true)');await page.eval('__smear.step(0)');await aimMachineSwitch(page,id,4);await tap('KeyE');assert.equal((await page.eval('__junkTest.stats()')).power[id],0);await useMachineSwitch(page,id);assert.equal((await page.eval('__junkTest.stats()')).power[id],1);await page.eval('__utilityTest.advance(60)');const moving=(await page.eval('__smear.props()'))[id===18?19:id];
  // Spinner's control stays on its fixed pedestal while the blade turns.
  if(id===23){await page.eval('__smear.view([-2.6,1.2,4.65],[-2.6,.785,3.365]);__smear.pointer(800,500)');await tap('KeyE');}
  else await useMachineSwitch(page,id);
  assert.equal((await page.eval('__junkTest.stats()')).power[id],0);await page.eval('__utilityTest.advance(120)');const stopped=(await page.eval('__smear.props()'))[id===18?19:id];assert.deepEqual(stopped.p,moving.p);assert.deepEqual(stopped.q,moving.q);r.machines.push({name,moving,stopped});await page.shot(resolve(out,name+'-switch.png'));
 }check('Native E starts all three demos from a physical switch, rejects out-of-reach use, and stops moving machinery in place');
 await page.eval('__utilityTest.reset()');const placed=await page.eval('__junkTest.place(9,[-2.6,0,3.3],.65)');assert.equal(placed.status,1);await useMachineSwitch(page,18);assert.equal((await page.eval('__junkTest.stats()')).power[18],0);const control=await aimMachineSwitch(page,18);const block=control.point.map((v,k)=>v+(control.origin[k]-v)*.48);await page.eval('__utilityTest.pose(0,'+JSON.stringify(block)+')');await tap('KeyE');assert.equal((await page.eval('__junkTest.stats()')).power[18],0);await page.eval('__smearGPU.removeToy(0)');await aimMachineSwitch(page,18);await page.eval('__smear.tool(0)');await until(async()=>{await page.eval('__smear.render()');return (await page.eval('__smearGPU.cache.control'))&255;},{timeout:5000,label:'physical switch prompt'});await page.mouse('mousePressed',800,500);await page.mouse('mouseReleased',800,500);assert.equal((await page.eval('__junkTest.stats()')).power[18],1);assert(!(await page.eval('__smearGPU.input().held')));check('Rotated press switches stay aligned, solid junk blocks use, and Grab clicks the physical button without grabbing or firing');
 await page.eval('__smear.utility.demo("crusher");__smear.manual(true);__smear.tool(0);__smear.step(0);__smear.view([-1.3,1.8,6.2],[-2.6,1.15,3.3])');await page.eval('__smear.manual(false)');await sleep(100);await page.eval('__smear.manual(true)');await page.shot(resolve(out,'crusher-open.png')); await useMachineSwitch(page,18);await page.eval('__utilityTest.advance(264);__smear.view([-1.3,1.8,6.2],[-2.6,1.15,3.3])');await page.shot(resolve(out,'crusher-closed.png'));assert((await page.eval('__junkTest.stats()')).injuries>0);await page.eval('__utilityTest.advance(264)');await page.shot(resolve(out,'crusher-cycle.png'));check('Revised crusher completes a crushing cycle and injures its loaded buddy');
 for(const [tool,name]of [[1,'pistol'],[4,'grenade'],[5,'rocket'],[12,'shotgun'],[13,'sawblade']]){await page.eval('__smear.tool('+tool+');__smear.manual(false)');await sleep(160);await page.eval('__smear.manual(true)');await page.shot(resolve(out,name+'.png'));}
 r.errors=page.logs.filter(s=>/^error:|^EXCEPTION:/.test(s));assert.deepEqual(r.errors,[]);r.result='COMPLETE '+r.checks.length+' UI and model checks';console.log(r.result);
}catch(e){r.result='FAIL';r.error=e.stack;r.logs=page?.logs;console.error(e.stack);process.exitCode=1;}finally{page?.kill();fs.writeFileSync(resolve(out,'verification.json'),JSON.stringify(r,null,2)+'\n');}
