import fs from 'node:fs';import assert from 'node:assert/strict';import {resolve} from 'node:path';import {pathToFileURL} from 'node:url';import {createHash} from 'node:crypto';
import {launch,until,sleep} from './cdp.mjs';import {installUtilityFixture} from './utility-fixture.mjs';
const out=resolve('tools/out/usability-pass/final'),r={at:new Date().toISOString(),buildSHA256:createHash('sha256').update(fs.readFileSync('index.html')).digest('hex'),checks:[]};fs.mkdirSync(out,{recursive:true});let page;
const pass=s=>{r.checks.push(s);console.log('PASS '+s);};
const key=async(code,down=true)=>page.call('Input.dispatchKeyEvent',{type:down?'keyDown':'keyUp',code,key:{Escape:'Escape',Tab:'Tab'}[code]||code.replace(/^Key|^Digit/,''),windowsVirtualKeyCode:{Escape:27,Tab:9}[code]||code.at(-1).charCodeAt(0)});
const tap=async code=>{await key(code);await key(code,false);};
const click=async(x,y)=>{await page.mouse('mousePressed',x,y);await page.mouse('mouseReleased',x,y);};
async function domClick(selector){const p=await page.eval(`(()=>{const b=document.querySelector(${JSON.stringify(selector)}).getBoundingClientRect();return{x:b.x+b.width/2,y:b.y+b.height/2};})()`);await click(p.x,p.y);}
const state=()=>page.eval('__smear.controls.state()');
const locked=()=>until(async()=>{const s=await state();return s.locked&&!s.paused;},{timeout:5000,label:'native mouse capture'});
const cursor=()=>until(async()=>!(await state()).locked,{timeout:5000,label:'native cursor release'});
try{
 page=await launch({port:9792,width:1600,height:1000,headless:true});r.profile=page.dir;await page.goto(pathToFileURL(resolve('index.html')).href+'?defaults=1');await until(()=>page.eval('!!window.__smearComputeReady'),{timeout:90000});await page.eval(`window.__inputTrace=[];for(const name of ['keydown','keyup','blur','focus','pointerlockchange','pointerlockerror'])window.addEventListener(name,e=>{__inputTrace.push({type:e.type,code:e.code,target:e.target.id,...__smear.controls.state()});},true)`);await domClick('#play-resume');await locked();
 for(let n=0;n<3;n++){await tap('KeyB');await cursor();assert(await page.eval('!document.getElementById("toybox").hidden'));assert.equal(await page.eval('document.querySelector("#toybox section").scrollTop'),0);if(n===0)await page.shot(resolve(out,'toybox-open.png'));assert.equal(await page.eval('getComputedStyle(document.getElementById("play-menu")).display'),'none');await tap(n===1?'Escape':'KeyB');assert(await page.eval('document.getElementById("toybox").hidden'));assert.equal((await state()).phase,'cursor');assert(!(await state()).paused);await tap('Tab');await locked();}
 pass('B toggles the toybox; Escape closes it without recapture or an overlapping pause menu; Tab deliberately resumes look');
 await tap('KeyB');await cursor();await domClick('#toy-search');await page.call('Input.insertText',{text:'barrel'});assert(await page.eval(`document.querySelector('[data-kind="1"]').hidden`));await tap('Escape');await tap('Tab');await locked();pass('Search accepts B in a word, and Escape leaves the search/menu cleanly');
 // C retains carry/free-aim behavior but its visible pointer can now use HUD buttons.
 await key('KeyC');const add=await page.eval('__smear.ui().find(b=>b.label==="Add dummy")'),aim=(await state()).aim;await page.call('Input.dispatchMouseEvent',{type:'mouseMoved',x:800,y:500,buttons:0});const current=(await state()).aim;await page.call('Input.dispatchMouseEvent',{type:'mouseMoved',x:800+(add.x+20-current.x),y:500+(add.y+15-current.y),buttons:0});r.cAim=await state();await click(800,500);await key('KeyC',false);await cursor();assert((await page.eval('__smear.buddy.state()')).placement);assert(!(await state()).paused);await tap('Escape');assert.equal((await state()).phase,'cursor');assert.equal(await page.eval('getComputedStyle(document.getElementById("play-menu")).display'),'none');pass('Holding C can click Add dummy; placement cancellation returns to a usable free cursor');
 await tap('Tab');await locked();await tap('Tab');await cursor();const uiAdd=await page.eval('__smear.ui().find(b=>b.label==="Add dummy")');await click(uiAdd.x+20,uiAdd.y+15);await page.eval('__smear.view([-3,2,7],[-3,0,5]);__smear.pointer(800,500)');await sleep(200);await click(800,500);await until(()=>page.eval('!__smear.buddy.state().placement'),{timeout:5000});assert.equal((await state()).phase,'cursor');await tap('Tab');await locked();pass('Tab exposes the toolbar; Add dummy commits with a free mouse and leaves capture under player control');
 await tap('KeyT');await sleep(100);assert(await page.eval('!document.getElementById("time-status").hidden'));let ticks=await page.eval('__smearGPU.steps');await sleep(1000);r.slowTicks=(await page.eval('__smearGPU.steps'))-ticks;assert(r.slowTicks>=26&&r.slowTicks<=35);await tap('KeyT');await sleep(100);assert(await page.eval('document.getElementById("time-status").hidden'));ticks=await page.eval('__smearGPU.steps');await sleep(1000);r.normalTicks=(await page.eval('__smearGPU.steps'))-ticks;assert(r.normalTicks>=108&&r.normalTicks<=132);pass('T toggles a visible 0.25x badge and measured quarter-speed simulation, then restores 120 Hz');
 await tap('Digit5');await page.shot(resolve(out,'grenade-grip.png'));await tap('Escape');await cursor();
 await installUtilityFixture(page);await page.eval('__utilityTest.reset()');await page.eval('__utilityTest.pose(3,[-3,.60,4])');await page.eval('__utilityTest.pose(0,[-4,.55,4])');await page.eval('__smear.tool(10);__smear.view([-3,1.3,7],[-3,1.3,4]);__smear.pointer(800,500)');
 const initial=await page.eval('__smear.props()');await page.mouse('mousePressed',800,500);await page.eval('__utilityTest.advance(90)');const gathered=await page.eval('__smear.props()');r.magnet={initial:initial[3],gathered:gathered[3]};assert(gathered[3].p[2]>initial[3].p[2]+.3);assert(Math.abs(gathered[0].p[2]-initial[0].p[2])<.03);const words=(await page.eval('__utilityTest.state()')).words;assert(words[17]&(1<<3));await page.shot(resolve(out,'magnet-pull.png'));
 await page.mouse('mousePressed',800,500,'right');await page.mouse('mouseReleased',800,500,'right');await page.eval('__utilityTest.advance(30)');r.magnet.launched=(await page.eval('__smear.props()'))[3];assert(r.magnet.launched.p[2]<r.magnet.gathered.p[2]-2);assert.equal((await page.eval('__utilityTest.state()')).words[16],1);await page.mouse('mouseReleased',800,500);await page.eval('__utilityTest.advance(1)');assert.equal((await page.eval('__utilityTest.state()')).words[16],0);pass('Magnet visibly acquires barrels, ignores wood, and launches over two metres while left mouse remains held instead of reeling them back');
 for(const [id,kind]of [[0,3],[3,2]]){
  await page.eval('__utilityTest.reset()');await page.eval(`__utilityTest.pose(${id},[-3,.6,4])`);await page.eval('__smear.tool(1);__smear.view([-3,.6,6],[-3,.6,4]);__smear.pointer(800,500);__smearGPU.shoot();__smearGPU.submit(0);__smearGPU.device.queue.onSubmittedWorkDone()');let fragments=(await page.eval('__utilityTest.ord()')).filter(o=>o.kind===kind);assert(fragments.length>=5);assert((await page.eval('__smear.props()'))[id].active);await page.eval('__utilityTest.advance(2)');await page.shot(resolve(out,kind===2?'metal-sparks.png':'wood-chips.png'));await page.eval('__utilityTest.advance(120)');assert((await page.eval('__utilityTest.ord()')).some(o=>o.kind===kind));
 }
 pass('Pistol hits shed persistent wood chips or short glowing metal sparks while the struck prop is still intact');
 await page.eval('__utilityTest.reset()');await page.eval('__utilityTest.pose(0,[-3,.55,4])');await page.eval('__smear.tool(3);__smear.view([-3,.7,5.8],[-3,.6,4]);__smear.pointer(800,500);__smearGPU.melee();__smearGPU.submit(0);__smearGPU.device.queue.onSubmittedWorkDone()');assert((await page.eval('__utilityTest.ord()')).filter(o=>o.kind===3).length>=5);pass('A bat strike also sheds chips before the crate breaks');
 r.errors=page.logs.filter(x=>/^EXCEPTION:|^error:/i.test(x));assert.deepEqual(r.errors,[]);r.result='COMPLETE '+r.checks.length+' usability and impact checks';console.log(r.result);
}catch(e){r.error=e.stack;r.result='FAIL';r.state=await state();r.logs=page.logs;r.trace=await page.eval('__inputTrace');console.error(e);process.exitCode=1;}finally{fs.writeFileSync(resolve(out,'verification.json'),JSON.stringify(r,null,2));page?.kill();}
