import fs from 'node:fs';import assert from 'node:assert/strict';import {resolve} from 'node:path';import {pathToFileURL} from 'node:url';import {spawnSync} from 'node:child_process';import {createHash} from 'node:crypto';
import {launch,until,sleep} from './cdp.mjs';import {installUtilityFixture} from './utility-fixture.mjs';
const out=resolve('tools/out/usability-pass/recordings');fs.mkdirSync(out,{recursive:true});const receipt={at:new Date().toISOString(),clips:[]};
function encode(args){const p=spawnSync('ffmpeg',['-nostdin','-hide_banner','-loglevel','error','-y',...args],{encoding:'utf8',windowsHide:true,timeout:120000});assert.ifError(p.error);assert.equal(p.status,0,p.stderr);}
for(const label of ['before','after'])for(const scene of ['grenade','violet','edges','chips']){
 const file=label==='before'?'tools/out/usability-pass/before/index.html':'index.html',page=await launch({port:9794,width:1600,height:1000,headless:true}),name=label+'-'+scene,clip={name,profile:page.dir,buildSHA256:createHash('sha256').update(fs.readFileSync(file)).digest('hex')};receipt.clips.push(clip);
 try{
  await page.goto(pathToFileURL(resolve(file)).href+'?defaults=1');await until(()=>page.eval('!!window.__smearComputeReady'),{timeout:90000});await installUtilityFixture(page);await page.eval('__utilityTest.reset()');await page.mouse('mousePressed',800,120);await page.mouse('mouseReleased',800,120);await page.eval('__smear.release(false);__smear.fly()');
  if(scene==='grenade')await page.eval('__smear.tool(4);__smear.view([0,1.68,5],[0,1.6,-2])');
  if(scene==='violet'){await page.eval('__utilityTest.patch({point:[6,0,2],radius:1.45,mass:.24})');await page.eval('__smear.view([3.3,1.1,4],[7.9,1.9,.2]);__smear.tool(0)');}
  if(scene==='edges')await page.eval(`(()=>{const g=__smearGPU,id=g.surfaces.findIndex(s=>s.n.y>.9&&s.center.y>.4&&s.center.y<2&&s.w>1&&s.h>1),r=g.records[id],s=g.surfaces[id];g.device.queue.writeBuffer(g.wetBuffer,(g.surfaces.length*3136+r.filmOffset)*4,new Uint32Array(r.filmWidth*r.filmHeight).fill(Math.round(.3*65536)));const c=s.center.toArray();__smear.view([c[0]+2,c[1]+1.3,c[2]+2.4],[c[0],c[1]-.15,c[2]]);__smear.tool(0);})()`);
  if(scene==='chips'){await page.eval('__utilityTest.pose(0,[-3,.55,5])');await page.eval('__utilityTest.patch({point:[-3,0,5],radius:.85,mass:.25})');await page.eval('__smear.view([-3,1.4,7.5],[-3,.6,5]);__smear.pointer(800,500);__smear.tool(1)');}
  await page.eval(`(()=>{window.__chunks=[];const tap=__smear.compute.audioTap();window.__stream=new MediaStream([...__smearGPU.canvas.captureStream(30).getVideoTracks(),...tap.stream.getAudioTracks()]);window.__recorder=new MediaRecorder(__stream,{mimeType:'video/webm;codecs=vp9,opus',videoBitsPerSecond:14000000});__recorder.ondataavailable=e=>{if(e.data.size)__chunks.push(e.data)};__recorder.start(1000);__smear.manual(false);})()`);
  await sleep(600);await page.shot(resolve(out,name+'-start.png'));
  if(scene==='chips')for(let n=0;n<2;n++){await page.mouse('mousePressed',800,500);await page.mouse('mouseReleased',800,500);await sleep(300);}
  await sleep(1800);await page.shot(resolve(out,name+'-end.png'));await sleep(700);await page.eval('__smear.manual(true)');
  const data=await page.eval(`new Promise(resolve=>{__recorder.onstop=()=>{const f=new FileReader();f.onload=()=>resolve(f.result.split(',')[1]);f.readAsDataURL(new Blob(__chunks,{type:'video/webm'}));__stream.getTracks().forEach(t=>t.stop());};__recorder.stop();})`);fs.writeFileSync(resolve(out,name+'.webm'),Buffer.from(data,'base64'));encode(['-i',resolve(out,name+'.webm'),'-vf','fps=30','-c:v','libx264','-preset','fast','-crf','18','-pix_fmt','yuv420p','-c:a','aac','-b:a','192k','-movflags','+faststart',resolve(out,name+'.mp4')]);
  clip.audio=await page.eval('__smear.compute.audio()');assert(clip.audio.enabled&&clip.audio.state==='running');assert.deepEqual(page.logs.filter(s=>/^EXCEPTION:|^error:/i.test(s)),[]);console.log('Captured '+name);
 }finally{page.kill();fs.writeFileSync(resolve(out,'capture.json'),JSON.stringify(receipt,null,2));}
}
for(const scene of ['grenade','violet','edges','chips'])encode(['-i',resolve(out,'before-'+scene+'.mp4'),'-i',resolve(out,'after-'+scene+'.mp4'),'-filter_complex',"[0:v]scale=800:500,setpts=PTS-STARTPTS,drawtext=font=Arial:text='V38':x=18:y=18:fontsize=22:fontcolor=white:box=1:boxcolor=black@0.7[a];[1:v]scale=800:500,setpts=PTS-STARTPTS,drawtext=font=Arial:text='V39':x=18:y=18:fontsize=22:fontcolor=white:box=1:boxcolor=black@0.7[b];[a][b]hstack=inputs=2:shortest=1[v];[0:a]pan=stereo|c0=c0|c1=0*c0[al];[1:a]pan=stereo|c0=0*c0|c1=c0[ar];[al][ar]amix=inputs=2:normalize=0[a]",'-map','[v]','-map','[a]','-shortest','-c:v','libx264','-preset','fast','-crf','18','-pix_fmt','yuv420p','-c:a','aac','-movflags','+faststart',resolve(out,'compare-'+scene+'.mp4')]);
receipt.passed=true;fs.writeFileSync(resolve(out,'capture.json'),JSON.stringify(receipt,null,2));console.log('COMPLETE V38/V39 matched gameplay captures');
