import fs from 'node:fs';import assert from 'node:assert/strict';import {resolve} from 'node:path';import {pathToFileURL} from 'node:url';import {spawnSync} from 'node:child_process';import {createHash} from 'node:crypto';import {launch,until,sleep} from './cdp.mjs';
const out=resolve('tools/out/utility-pass/recordings');fs.mkdirSync(out,{recursive:true});const receipt={at:new Date().toISOString(),clips:[]};
function encode(args){const r=spawnSync('ffmpeg',['-nostdin','-hide_banner','-loglevel','error','-y',...args],{encoding:'utf8',windowsHide:true,timeout:120000});assert.ifError(r.error);assert.equal(r.status,0,r.stderr);}
async function start(page){await page.eval(`(()=>{window.__chunks=[];const tap=__smear.compute.audioTap();window.__stream=new MediaStream([...__smearGPU.canvas.captureStream(30).getVideoTracks(),...tap.stream.getAudioTracks()]);window.__recorder=new MediaRecorder(__stream,{mimeType:'video/webm;codecs=vp9,opus',videoBitsPerSecond:14000000,audioBitsPerSecond:192000});__recorder.ondataavailable=e=>{if(e.data.size)__chunks.push(e.data)};__recorder.start(1000);__smear.manual(false);})()`);}
async function finish(page,name,title){await page.eval('__smear.manual(true)');const data=await page.eval(`new Promise(resolve=>{__recorder.onstop=()=>{const f=new FileReader();f.onload=()=>resolve(f.result.split(',')[1]);f.readAsDataURL(new Blob(__chunks,{type:'video/webm'}));__stream.getTracks().forEach(t=>t.stop());};__recorder.stop();})`);fs.writeFileSync(resolve(out,name+'.webm'),Buffer.from(data,'base64'));encode(['-i',resolve(out,name+'.webm'),'-vf',`fps=30,drawtext=font=Arial:text='${title}':x=24:y=h-50:fontsize=25:fontcolor=white:box=1:boxcolor=black@0.7:boxborderw=8`,'-c:v','libx264','-preset','fast','-crf','18','-pix_fmt','yuv420p','-c:a','aac','-b:a','192k','-movflags','+faststart',resolve(out,name+'.mp4')]);}
const scenes=[['machine','THE ACCIDENT LINE / CONVEYOR - CRATE - BARREL CHAIN'],['before','V36 / MATCHED POOL BEFORE CLEANUP TOOLS'],['mop','V37 / FINITE MOP - SOAK / PUSH / DIRTY STREAKS'],['blower','V37 / LEAF BLOWER - WET RIDGES AND SPRAY'],['washer','V37 / PRESSURE WASHER - STAIN REMOVAL AND RUNOFF'],['vacuum','V37 / WET VACUUM - COLLECT / REVERSE'],['magnet','V37 / MAGNET GUN - GATHER / LAUNCH'],['sticky','V37 / STICKY CHARGES - ATTACH / REMOTE DETONATE']];
for(const [name,title]of scenes){
 const path=name==='before'?'tools/out/utility-pass/before/index.html':'index.html';const page=await launch({port:9773,width:1600,height:1000,headless:true});const clip={name,title,profile:page.dir,sha256:createHash('sha256').update(fs.readFileSync(path)).digest('hex')};receipt.clips.push(clip);
 try{
  await page.goto(pathToFileURL(resolve(path)).href+'?defaults=1');await until(()=>page.eval('!!window.__smearComputeReady'),{timeout:90000});await page.eval('__smear.controls.mode("cursor");__smear.manual(true)');await page.mouse('mousePressed',800,140);await page.mouse('mouseReleased',800,140);await page.eval('(async()=>{__smear.reset();__smear.preset("default");__smear.tune({walking:false,recover:false});await __smear.step(0);__smear.fly();})()');
  if(name==='machine'){
   await page.eval('__smear.utility.build();__smear.manual(true);__smear.tool(0);__smear.view([-.3,3.4,6.9],[.1,.65,1.1]);__smear.pointer(800,500)');await start(page);await sleep(1200);await page.shot(resolve(out,'machine-ready.png'));await page.eval('__smear.utility.run()');await sleep(380);await page.shot(resolve(out,'machine-impact.png'));await sleep(3000);await page.eval('__smear.view([1.6,2.5,4.3],[1.3,.25,1.3])');await sleep(3200);clip.props=await page.eval('__smear.props()');assert(clip.props.filter(p=>p.kind==='barrel'&&p.broken).length>=3);
  }else if(name==='magnet'){
   await page.eval('__smear.view([5.65,1.4,-3.5],[5.65,.7,-6.7]);__smear.pointer(800,500);__smear.tool(10)');await start(page);await sleep(400);await page.mouse('mousePressed',800,500);await sleep(1700);await page.mouse('mouseReleased',800,500);await page.shot(resolve(out,'magnet-gather.png'));await page.mouse('mousePressed',800,500,'right');await sleep(90);await page.mouse('mouseReleased',800,500,'right');await sleep(2400);
  }else if(name==='sticky'){
   await page.eval('__smear.view([-2.4,1.75,-.7],[-2.4,1.5,-2.95]);__smear.pointer(800,500);__smear.tool(11)');await start(page);await sleep(350);for(let i=0;i<2;i++){await page.mouse('mousePressed',800,500);await sleep(40);await page.mouse('mouseReleased',800,500);await sleep(600);}await page.shot(resolve(out,'sticky-attached.png'));for(const type of ['keyDown','keyUp'])await page.call('Input.dispatchKeyEvent',{type,code:'KeyG',key:'g'});await sleep(2800);
  }else{
   // Identical real Spill preparation in the released baseline and new build.
   await page.eval('(async()=>{__smear.view([-3,1.68,6.5],[-3,0,5]);__smear.pointer(800,500);for(let i=0;i<9;i++){__smearGPU.spill();__smearGPU.submit(2);}await __smear.step(90);})()');
   const tool={before:0,mop:6,blower:7,washer:8,vacuum:9}[name];await page.eval('__smear.tool('+tool+')');await start(page);await sleep(500);if(name!=='before')await page.mouse('mousePressed',800,500);
   for(let i=0;i<70;i++){await page.mouse('mouseMoved',800+Math.sin(i*.12)*145,500+Math.sin(i*.065)*50);await sleep(35);}if(name!=='before')await page.mouse('mouseReleased',800,500);await sleep(350);
   if(name==='vacuum'){await page.eval('__smear.view([-3,1.68,6.5],[-3,.8,3.8]);__smear.pointer(800,500)');await page.mouse('mousePressed',800,500,'right');await sleep(1800);await page.mouse('mouseReleased',800,500,'right');}else await sleep(1800);
  }
  await page.shot(resolve(out,name+'-after.png'));await finish(page,name,title);clip.audio=await page.eval('__smear.compute.audio()');assert(clip.audio.enabled&&clip.audio.state==='running');assert.deepEqual((await page.eval('__smear.state()')).errors,[]);assert(!page.logs.some(s=>/^error:|^EXCEPTION:/.test(s)));console.log('Recorded '+name);
 }finally{clip.logs=page.logs;page.kill();fs.writeFileSync(resolve(out,'capture.json'),JSON.stringify(receipt,null,2));}
}
encode(['-i',resolve(out,'before.mp4'),'-i',resolve(out,'mop.mp4'),'-filter_complex','[0:v]scale=960:600,setpts=PTS-STARTPTS[a];[1:v]scale=960:600,setpts=PTS-STARTPTS[b];[a][b]hstack=inputs=2:shortest=1[v]','-map','[v]','-map','1:a','-shortest','-c:v','libx264','-preset','fast','-crf','18','-pix_fmt','yuv420p','-c:a','aac','-b:a','192k','-movflags','+faststart',resolve(out,'cleanup-before-after.mp4')]);
fs.writeFileSync(resolve(out,'showcase.txt'),scenes.filter(([n])=>n!=='before').map(([n])=>"file '"+n+".mp4'").join('\n'));encode(['-f','concat','-safe','0','-i',resolve(out,'showcase.txt'),'-c','copy','-movflags','+faststart',resolve(out,'smear-v37-showcase.mp4')]);receipt.passed=true;fs.writeFileSync(resolve(out,'capture.json'),JSON.stringify(receipt,null,2));console.log('COMPLETE V37 footage and matched cleanup comparison');
