// Explicit inspection helpers. None of these downloads run during gameplay.
import {installDestructionFixture} from './destruction-fixture.mjs';
export async function installUtilityFixture(page){
 await installDestructionFixture(page);
 await page.eval(`(()=>{const g=__smearGPU,d=g.device,read=__destructionFixture.read.bind(__destructionFixture);window.__utilityTest={
 async reset(){__smear.manual(true);__smear.reset();await __smear.step(0);__smear.clean();g.clearDrops();g.bodyCount=0;g.syncCounts();__smear.tune({walking:false,recover:false});d.queue.writeBuffer(g.workBuffer,19*4,new Uint32Array([(1<<g.props.length)-1]));__smear.controls.mode('cursor');__smear.manual(true);__smear.pointer(800,500);},
 async state(){const w=new Uint32Array(await read(g.workBuffer,g.utilityBase*4,Math.max(160,32+g.props.length*8)*4));const liquid=await __destructionFixture.liquid();let tanks=(w[0]+w[1])/16777216;for(let i=0;i<g.props.length;i++)tanks+=w[32+i*8]/16777216;return{mop:w[0]/16777216,vac:w[1]/16777216,debris:w[2],words:Array.from(w),mobile:liquid.mobile,residue:liquid.residue,airborne:liquid.airborne,total:liquid.total+tanks,drops:liquid.drops.length};},
 async patch({point=[-3,0,5],radius=.43,mass=1.2,dry=0,paint=true}={}){const id=point[1]>0?16:Math.floor((point[2]+8)/4)*4+Math.floor((point[0]+8)/4),s=g.surfaces[id],r=g.records[id];for(const [bank,value]of [[0,mass],[2,dry]]){const a=new Uint32Array(r.filmWidth*r.filmHeight);for(let y=0;y<r.filmHeight;y++)for(let x=0;x<r.filmWidth;x++){const p=s.center.clone().addScaledVector(s.u,((x+.5)/r.filmWidth-.5)*s.w).addScaledVector(s.v,((y+.5)/r.filmHeight-.5)*s.h);if(p.distanceTo(new g.THREE.Vector3(...point))<radius)a[x+y*r.filmWidth]=Math.round(value*65536);}d.queue.writeBuffer(g.wetBuffer,(g.surfaces.length*3136+bank*g.filmCells+r.filmOffset)*4,a);}if(paint){const a=new Uint32Array(r.width*r.height);for(let y=0;y<r.height;y++)for(let x=0;x<r.width;x++){const p=s.center.clone().addScaledVector(s.u,((x+.5)/r.width-.5)*s.w).addScaledVector(s.v,((y+.5)/r.height-.5)*s.h);if(p.distanceTo(new g.THREE.Vector3(...point))<radius)a[x+y*r.width]=0xee070747;}d.queue.writeBuffer(g.paintBuffer,r.pixelOffset*4,a);}return id;},
 async centroid(){const a=new Uint32Array(await read(g.wetBuffer,g.surfaces.length*3136*4,g.filmCells*4));let mass=0,z=0,x=0;for(let id=0;id<16;id++){const s=g.surfaces[id],r=g.records[id];for(let j=0;j<r.filmHeight;j++)for(let i=0;i<r.filmWidth;i++){const m=a[r.filmOffset+i+j*r.filmWidth];mass+=m;const p=s.center.clone().addScaledVector(s.u,((i+.5)/r.filmWidth-.5)*s.w).addScaledVector(s.v,((j+.5)/r.filmHeight-.5)*s.h);x+=p.x*m;z+=p.z*m;}}return{x:x/mass,z:z/mass,mass};},
 async alpha(id){const r=g.records[id],a=new Uint32Array(await read(g.paintBuffer,r.pixelOffset*4,r.width*r.height*4));return a.reduce((n,v)=>n+(v>>>24),0);},
 async pose(id,p,q=[0,0,0,1],v=[0,0,0]){const a=new Float32Array(await read(g.constantBuffer,g.propDataOffset+id*640,640));a.set(p,0);a.set(q,4);a.set(v,8);a.fill(0,12,16);a.fill(0,32,64);a[60]=1;d.queue.writeBuffer(g.constantBuffer,g.propDataOffset+id*640,a);const mask=new Uint32Array(await read(g.workBuffer,19*4,4));mask[0]&=~(1<<id);d.queue.writeBuffer(g.workBuffer,19*4,mask);await __smear.step(1);},
 async ord(){const a=await read(g.workBuffer,(g.destructionBase+1440)*4,128*24*4),w=new Uint32Array(a),f=new Float32Array(a);return Array.from({length:128},(_,i)=>({kind:w[i*24+23],attached:w[i*24+20],p:Array.from(f.slice(i*24,i*24+3)),v:Array.from(f.slice(i*24+4,i*24+7))}));},
 async counters(){return Array.from(new Uint32Array(await read(g.workBuffer,0,64*4)));},
 advance:n=>__destructionFixture.advance(n)
};})()`);
}
