import {useMachineSwitch} from './machine-input.mjs';
import fs from 'node:fs';import assert from 'node:assert/strict';import {resolve} from 'node:path';import {pathToFileURL} from 'node:url';import {createHash} from 'node:crypto';
import {launch,until,sleep} from './cdp.mjs';import {installUtilityFixture} from './utility-fixture.mjs';import {installImpactFixture} from './impact-fixture.mjs';
const out=resolve('tools/out/utility-pass/'+(process.argv[2]||'development'));fs.mkdirSync(out,{recursive:true});
const r={at:new Date().toISOString(),sha256:createHash('sha256').update(fs.readFileSync('index.html')).digest('hex'),checks:[]};let page;
const pass=s=>{r.checks.push(s);console.log('PASS '+s);};
try{
 page=await launch({port:9770,width:1600,height:1000,headless:true});r.profile=page.dir;await page.goto(pathToFileURL(resolve('index.html')).href+'?defaults=1');
 await until(async()=>{const s=await page.eval('({ready:!!window.__smearComputeReady,error:document.getElementById("failure")?.style.display==="block"?document.getElementById("failure").textContent:null})');if(s.error)throw Error(s.error);return s.ready;},{timeout:90000});
 await page.eval('__smear.manual(true)');await page.mouse('mousePressed',800,120);await page.mouse('mouseReleased',800,120);await installUtilityFixture(page);await installImpactFixture(page);
 const alternate=async down=>page.call('Input.dispatchKeyEvent',{type:down?'keyDown':'keyUp',code:'KeyY',key:'y'});
 const hold=async(tool,ticks,button='left')=>{await page.eval('__smear.tool('+tool+')');if(button==='right')await alternate(true);else await page.mouse('mousePressed',800,500,button);await page.eval('__utilityTest.advance('+ticks+')');if(button==='right')await alternate(false);else await page.mouse('mouseReleased',800,500,button);};
 const state=()=>page.eval('__utilityTest.state()');
 await page.eval('__utilityTest.reset()');await page.eval('__smear.view([-3,1.68,6.5],[-3,0,5]);__smear.pointer(800,500)');
 for(const [key,expected]of [['7',6],['8',7],['9',8],['0',9]]){for(const type of ['keyDown','keyUp'])await page.call('Input.dispatchKeyEvent',{type,code:'Digit'+key,key});assert.equal((await page.eval('__smear.controls.state()')).tool,expected);}
 assert.equal(await page.eval('__smearGPU.utilityTools.length'),6);pass('Native number keys select cleanup tools; all six new procedural tool models exist');
 await page.eval('__utilityTest.patch()');const initial=await state();await hold(6,180);r.mop={initial,after:await state()};assert(r.mop.after.mop>.20);assert(r.mop.after.mop<=.25001);assert(Math.abs(r.mop.after.total-initial.total)<.004);await page.shot(resolve(out,'mop.png'));pass('Native mop fills a finite reservoir while preserving total wet liquid');
 await page.eval('__smear.toybox.place(3);__smear.view([-1.5,2,7],[-1.5,0,5]);__smear.pointer(800,500);__smear.render();__smear.buddy.confirm()');assert.equal((await page.eval('__smear.toybox.state()')).placement,null);assert((await page.eval('__smear.props()'))[8].active);
 await page.eval('__smear.view([-1.5,1.1,6.2],[-1.5,.40,5]);__smear.pointer(800,500)');const beforeWring=await state();await hold(6,90,'right');r.wring={before:beforeWring,after:await state()};assert(r.wring.after.mop<.01);assert(r.wring.after.words[96]>beforeWring.words[96]);assert(Math.abs(r.wring.after.total-beforeWring.total)<.005);pass('An aimed bucket accepts finite mop contents through native Y alternate wringing');
 await page.eval('__utilityTest.pose(8,[-1.5,1.5,5],[0,0,.70710678,.70710678])');const beforeTip=await state();await page.eval('__utilityTest.advance(120)');r.bucket={before:beforeTip,after:await state()};assert(r.bucket.after.words[96]<beforeTip.words[96]);assert(r.bucket.after.drops>0||r.bucket.after.mobile>beforeTip.mobile);assert(Math.abs(r.bucket.after.total-beforeTip.total)<.012);pass('A tilted or thrown bucket pays for airborne paint from its finite payload');
 await page.eval('__utilityTest.reset()');await page.eval('__utilityTest.patch();__smear.view([-3,.65,7],[-3,0,5]);__smear.pointer(800,500)');const b0=await page.eval('__utilityTest.centroid()'),blood0=await state();await hold(7,120);r.blower={before:b0,after:await page.eval('__utilityTest.centroid()'),liquid:await state()};assert(r.blower.after.z<b0.z-.1);assert(Math.abs(r.blower.liquid.total-blood0.total)<.01);pass('Leaf blower transports existing wet liquid directionally without creating supply');
 await page.eval('__utilityTest.reset()');await page.eval('__utilityTest.patch({point:[-.1,0,5]});__smear.view([-2.3,.55,5],[-.1,0,5]);__smear.pointer(800,500)');const seamStart=await state();await hold(7,120);const crossed=await page.eval('(async()=>{const g=__smearGPU,r=g.records[14],a=new Uint32Array(await __destructionFixture.read(g.wetBuffer,(g.surfaces.length*3136+r.filmOffset)*4,r.filmWidth*r.filmHeight*4));return a.reduce((n,v)=>n+v,0)/65536/1600;})()');assert(crossed>.025);assert(Math.abs((await state()).total-seamStart.total)<.01);pass('Air-driven liquid crosses floor-chart seams without stopping or cloning volume');
 await page.eval('__utilityTest.reset()');await page.eval('__utilityTest.patch({mass:0,dry:.5});__smear.view([-3,.65,7],[-3,0,5]);__smear.pointer(800,500)');const dryHash=await page.eval('__smear.compute.paintHash(13)'),dryStart=await state();await hold(7,120);assert.deepEqual(await page.eval('__smear.compute.paintHash(13)'),dryHash);assert(Math.abs((await state()).residue-dryStart.residue)<.001);pass('Blower leaves dry pigment and dry residue in place');
 await page.eval('__smear.view([-3,1.68,6.5],[-3,0,5]);__smear.pointer(800,500)');const alpha0=await page.eval('__utilityTest.alpha(13)');await hold(8,120);r.washer={alphaBefore:alpha0,alphaAfter:await page.eval('__utilityTest.alpha(13)'),liquid:await state()};assert(r.washer.alphaAfter<alpha0*.97);assert(r.washer.liquid.mobile>0);assert(r.washer.liquid.residue<dryStart.residue);pass('Pressure washer strips dry stain into mobile dirty runoff');
 await page.eval('__utilityTest.reset()');await page.eval('__utilityTest.patch();__smear.view([-3,1.68,6.5],[-3,0,5]);__smear.pointer(800,500)');await hold(9,120);const vac=await state();assert(vac.vac>.1);await page.eval('__smear.view([-3,1.68,6.5],[-3,1.68,2]);__smear.pointer(800,500)');await hold(9,90,'right');r.vacuum={before:vac,after:await state()};assert(r.vacuum.after.vac<vac.vac*.6);assert(r.vacuum.after.drops>0||r.vacuum.after.mobile>vac.mobile);assert(Math.abs(r.vacuum.after.total-vac.total)<.01);pass('Wet vacuum collects paid liquid and reverses to spray it back into the room');
 await page.eval('__utilityTest.reset()');await page.eval('');await page.eval('__utilityTest.pose(3,[-3,.60,4])');await page.eval('__smear.view([-3,1.3,7],[-3,.6,4]);__smear.pointer(800,500)');const magnet0=(await page.eval('__smear.props()'))[3];await hold(10,80);r.magnet={before:magnet0,gathered:(await page.eval('__smear.props()'))[3]};assert(r.magnet.gathered.p[2]>magnet0.p[2]+.3);await alternate(true);await alternate(false);await page.eval('__smear.step(4)');r.magnet.launched=(await page.eval('__smear.props()'))[3];assert(r.magnet.launched.v[2]<-5);pass('Magnet gathers a GPU barrel and launches it with native secondary input');
 await page.eval('__impactTest.setup({speed:0})');const head=(await page.eval('__smear.state()')).parts[2].p;await page.eval('__smear.view('+JSON.stringify([head[0],head[1]-.06,head[2]+1.2])+','+JSON.stringify(head)+');__smear.pointer(800,500)');await hold(11,16);let charges=(await page.eval('__utilityTest.ord()')).filter(o=>o.kind===6);r.charge=charges;assert(charges.some(o=>o.attached>0&&o.attached<=180));await page.eval('__utilityTest.advance(12)');charges=(await page.eval('__utilityTest.ord()')).filter(o=>o.kind===6);const parts=(await page.eval('__smear.state()')).parts;assert(charges.every(o=>Math.hypot(...o.p.map((v,i)=>v-parts[o.attached-1].p[i]))<.6));
 for(const type of ['keyDown','keyUp'])await page.call('Input.dispatchKeyEvent',{type,code:'KeyG',key:'g'});await page.eval('__smear.step(2)');assert(!(await page.eval('__utilityTest.ord()')).some(o=>o.kind===6));assert((await page.eval('__utilityTest.counters()'))[58]>0);pass('Sticky charges attach to moving body parts and G detonates them once');
 await page.eval('__smear.utility.build();__smear.manual(true);__smear.render()');r.machineBefore=await page.eval('__smear.props()');await page.shot(resolve(out,'machine-before.png'));await page.eval('__smear.utility.run();__smear.manual(true);__utilityTest.advance(720)');r.machineAfter=await page.eval('__smear.props()');r.machineCounters=await page.eval('__utilityTest.counters()');r.machineParts=(await page.eval('__smear.state()')).parts;await page.shot(resolve(out,'machine-after.png'));assert(r.machineCounters[58]>=3,'physical chain should detonate three barrels');assert(r.machineAfter.filter(p=>p.broken).length>=4);assert(r.machineParts.some(p=>p.severed));pass('Conveyor-driven physical crate impact starts a barrel chain that breaks props and dismembers buddies');
 // A wide crate crosses the belt edges with no contained collision vertex.
 // Let it settle fully, then start via the real button and real frame loop.
 await page.eval('__smear.utility.build();__smear.manual(true);__utilityTest.advance(600)');
 r.armedProps=await page.eval('__smear.props()');assert(r.armedProps[0].p[1]>.85,'armed crate must remain on top of the conveyor');assert(!r.armedProps.some(p=>p.broken));
 await useMachineSwitch(page,11);await page.eval('__smear.manual(false)');await sleep(6000);await page.eval('__smear.manual(true)');
 r.delayedMachine=await page.eval('__smear.props()');assert(r.delayedMachine.filter(p=>p.kind==='barrel'&&p.broken).length>=3);assert.equal(await page.eval('document.getElementById("machine-start")'),null);pass('Settled machine survives five seconds armed and the native machine switch triggers its barrel chain during real-time play');
 // Devices also work when individually placed, switched off and restarted.
 await page.eval('__utilityTest.reset()');await page.eval('__smear.toybox.place(4);__smear.view([-3,2,7],[-3,0,5]);__smear.pointer(800,500);__smear.render();__smear.buddy.confirm()');assert((await page.eval('__smear.props()'))[10].active);assert.equal((await state()).words[113],1);await page.eval('__smear.utility.toggle(10)');assert.equal((await state()).words[113],0);await page.eval('__smear.utility.toggle(10)');assert.equal((await state()).words[113],1);pass('Native placement creates a powered fan; device power can be switched independently');
 await page.eval('__smearGPU.removeToy(10)');await page.eval('__utilityTest.pose(0,[-3,.6,4])');await page.eval('__smear.view([-3,1.0,6.1],[-3,.7,4]);__smear.pointer(800,500)');await hold(11,28);const propCharge=(await page.eval('__utilityTest.ord()')).find(o=>o.kind===6);assert(propCharge?.attached===181);await page.eval('__utilityTest.pose(0,[-2,1.2,4])');await page.eval('__smear.step(2)');const movedCharge=(await page.eval('__utilityTest.ord()')).find(o=>o.kind===6);assert(movedCharge.p[0]>propCharge.p[0]+.85);await page.eval('__smear.utility.detonate();__smear.step(2)');assert(!(await page.eval('__utilityTest.ord()')).some(o=>o.kind===6));pass('Sticky charges retain their local attachment when a prop moves, then detonate remotely');
 // Seed real GPU wood/metal fragments, collect them with native input, reverse.
 await page.eval('__utilityTest.reset()');await page.eval('__smear.view([-3,1.3,6.5],[-3,.7,4.5]);__smear.pointer(800,500)');
 await page.eval(String.raw`(async()=>{const g=__smearGPU,d=g.device,code=__smearComputeShaders.common+'\n'+__smearComputeShaders.compute+'\n@compute @workgroup_size(1) fn debrisProbe(){spawnOrdnance(3u,vec3f(-3,.7,4.5),vec3f(0),.035,11u);spawnOrdnance(2u,vec3f(-3.05,.7,4.5),vec3f(0),.03,12u);}';const module=d.createShaderModule({code}),pipeline=await d.createComputePipelineAsync({layout:d.createPipelineLayout({bindGroupLayouts:[g.computeLayout]}),compute:{module,entryPoint:'debrisProbe'}});g.uniforms(1);const e=d.createCommandEncoder(),p=e.beginComputePass();p.setBindGroup(0,g.computeGroup,[0]);p.setPipeline(pipeline);p.dispatchWorkgroups(1);p.end();d.queue.submit([e.finish()]);await d.queue.onSubmittedWorkDone();})()`);
 await hold(9,2);assert.equal((await state()).debris,2);await hold(9,10,'right');assert.equal((await state()).debris,0);const recycled=await page.eval('__utilityTest.ord()');assert(recycled.some(o=>o.kind===2)&&recycled.some(o=>o.kind===3));pass('Wet vacuum captures and re-ejects small debris while retaining metal versus wood');
 const final=await page.eval('__smear.state()');assert.deepEqual(final.errors,[]);assert.equal(final.normalPaintReadbacks,0);r.audio=await page.eval('__smear.compute.audio()');assert.equal(r.audio.state,'running');assert(!page.logs.some(s=>/^error:|^EXCEPTION:/.test(s)));r.passed=true;console.log('COMPLETE '+r.checks.length+' utility checks passed');
}catch(e){r.error=e.stack;console.error(e.stack);process.exitCode=1;}finally{if(page){r.logs=page.logs;page.kill();}fs.writeFileSync(resolve(out,'receipt.json'),JSON.stringify(r,null,2)+'\n');}
